//! Kubernetes manifest generation

use anyhow::{Context, Result};
use std::fs;
use std::path::{Path, PathBuf};

use crate::manifest::{K8sResources, Manifest, ResourceSpec};

/// Generate Kubernetes manifests (deployment.yaml, service.yaml)
pub(super) fn generate_k8s_manifests(
    bundle_dir: &Path,
    project: &str,
    image_ref: &str,
) -> Result<PathBuf> {
    // Create k8s/ directory
    let k8s_dir = bundle_dir.join("k8s");
    fs::create_dir_all(&k8s_dir)
        .with_context(|| format!("Failed to create k8s directory: {}", k8s_dir.display()))?;

    // Load manifest.toml to get project config
    let manifest_content =
        fs::read_to_string("manifest.toml").with_context(|| "Failed to read manifest.toml")?;
    let manifest: Manifest =
        toml::from_str(&manifest_content).with_context(|| "Failed to parse manifest.toml")?;

    // Find project config in [[app]] array
    let project_name = project.rsplit('/').next().unwrap_or(project);
    let app_config = manifest.app.iter().find(|app| {
        app.name == project_name || app.name == project || app.path.as_deref() == Some(project)
    });

    // Get K8s configuration with defaults
    let port = app_config
        .and_then(|c| c.port)
        .unwrap_or(crate::conventions::framework_defaults("node").port);
    let replicas = app_config.and_then(|c| c.replicas).unwrap_or(1);
    let resources = app_config
        .and_then(|c| c.resources.clone())
        .unwrap_or_else(|| K8sResources {
            requests: Some(ResourceSpec {
                cpu: Some("100m".to_string()),
                memory: Some("128Mi".to_string()),
            }),
            limits: Some(ResourceSpec {
                cpu: Some("500m".to_string()),
                memory: Some("512Mi".to_string()),
            }),
        });

    // Generate deployment.yaml
    let deployment = generate_deployment_yaml(project_name, image_ref, port, replicas, &resources);
    let deployment_path = k8s_dir.join("deployment.yaml");
    fs::write(&deployment_path, &deployment).with_context(|| "Failed to write deployment.yaml")?;

    // Generate service.yaml
    let service = generate_service_yaml(project_name, port);
    let service_path = k8s_dir.join("service.yaml");
    fs::write(&service_path, &service).with_context(|| "Failed to write service.yaml")?;

    Ok(k8s_dir)
}

/// Generate Kubernetes Deployment YAML
pub(super) fn generate_deployment_yaml(
    name: &str,
    image: &str,
    port: u16,
    replicas: u32,
    resources: &K8sResources,
) -> String {
    let requests = resources.requests.as_ref();
    let limits = resources.limits.as_ref();

    let requests_cpu = requests.and_then(|r| r.cpu.as_deref()).unwrap_or("100m");
    let requests_memory = requests
        .and_then(|r| r.memory.as_deref())
        .unwrap_or("128Mi");
    let limits_cpu = limits.and_then(|l| l.cpu.as_deref()).unwrap_or("500m");
    let limits_memory = limits.and_then(|l| l.memory.as_deref()).unwrap_or("512Mi");

    format!(
        r#"# Generated by airis bundle --k8s
# DO NOT EDIT - Regenerate with: airis bundle {name} --k8s
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {name}
  labels:
    app: {name}
spec:
  replicas: {replicas}
  selector:
    matchLabels:
      app: {name}
  template:
    metadata:
      labels:
        app: {name}
    spec:
      containers:
      - name: {name}
        image: {image}
        ports:
        - containerPort: {port}
        resources:
          requests:
            cpu: "{requests_cpu}"
            memory: "{requests_memory}"
          limits:
            cpu: "{limits_cpu}"
            memory: "{limits_memory}"
"#
    )
}

/// Generate Kubernetes Service YAML
pub(super) fn generate_service_yaml(name: &str, port: u16) -> String {
    format!(
        r#"# Generated by airis bundle --k8s
# DO NOT EDIT - Regenerate with: airis bundle {name} --k8s
apiVersion: v1
kind: Service
metadata:
  name: {name}
spec:
  selector:
    app: {name}
  ports:
  - port: {port}
    targetPort: {port}
  type: ClusterIP
"#
    )
}
