packages:
- apps/*
- libs/*
- packages/*
catalog:
  drizzle-orm: ^0.44.7
  eslint: ^9.39.1
  hono: ^4.10.6
  next: ^16.0.3
  playwright: ^1.56.1
  prettier: ^3.6.2
  react: ^19.2.0
  tailwindcss: ^4.1.17
  typescript: ^5.9.3
  vitest: ^4.0.9
  zod: ^4.1.12
  react-dom: ^19.2.0
  react-is: ^19.2.0
