use super::actions::ResolvedActions;
use super::TemplateEngine;
use crate::manifest::Manifest;
use anyhow::Result;

impl TemplateEngine {
    /// Generate .github/workflows/ci.yml from manifest v2
    pub fn render_ci_workflow(&self, manifest: &Manifest) -> Result<String> {
        // Infrastructure-only: no Node.js workspace
        if !manifest.has_workspace() {
            return self.render_infra_ci_workflow(manifest);
        }

        let ci = &manifest.ci;
        let a = ResolvedActions::from_manifest(&ci.actions)?;
        let checkout = &a.checkout;
        let pnpm_action = &a.pnpm;
        let setup_node = &a.setup_node;
        let node_version = manifest.node_version();
        let runner = ci.runner.as_deref().unwrap_or("ubuntu-latest");
        let affected_flag = if ci.affected { " --affected" } else { "" };

        // Runner YAML: "self-hosted, linux" → [self-hosted, linux]
        let runner_yaml = if runner.contains(',') {
            format!("[{}]", runner)
        } else {
            runner.to_string()
        };

        // pnpm store step
        let pnpm_store_step = if let Some(ref store_path) = ci.pnpm_store_path {
            format!(
                "      - name: Configure pnpm store\n        run: pnpm config set store-dir {}",
                store_path
            )
        } else {
            format!(
                "      - name: Cache pnpm store\n        uses: {}\n        with:\n          path: ~/.pnpm-store\n          key: ${{{{ runner.os }}}}-pnpm-${{{{ hashFiles('pnpm-lock.yaml') }}}}\n          restore-keys: ${{{{ runner.os }}}}-pnpm-",
                a.cache
            )
        };

        // Determine CI branch and PR target from profiles
        let deploy_profiles = manifest.deploy_profiles();
        let ci_branch = deploy_profiles
            .iter()
            .find(|(name, p)| p.effective_role(name) == "staging")
            .map(|(_, p)| p.branch.as_deref().unwrap_or("stg"))
            .unwrap_or(&ci.auto_merge.from);
        let pr_target = deploy_profiles
            .iter()
            .find(|(name, p)| p.effective_role(name) == "production")
            .map(|(_, p)| p.branch.as_deref().unwrap_or("main"))
            .unwrap_or(&ci.auto_merge.to);

        let concurrency = if ci.concurrency_cancel {
            "\nconcurrency:\n  group: ${{ github.workflow }}-${{ github.ref }}\n  cancel-in-progress: true\n"
        } else {
            ""
        };

        // Fetch main branch ref for turbo --affected (needs merge base)
        let fetch_main_step = if ci.affected {
            format!(
                "\n      - name: Fetch base branch for turbo --affected\n        run: git fetch origin {pr_target} --depth=1 || true"
            )
        } else {
            String::new()
        };

        // Build CI job (same structure for lint, typecheck, test)
        let build_job = |task: &str, timeout: u8| -> String {
            format!(
                "  {}:\n    runs-on: {}\n    timeout-minutes: {}\n    steps:\n      - uses: {}\n        with:\n          fetch-depth: 2{}\n      - uses: {}\n      - uses: {}\n        with:\n          node-version: '{}'\n{}\n      - run: pnpm install --frozen-lockfile\n      - run: pnpm turbo run {}{}{}",
                task,
                runner_yaml,
                timeout,
                checkout,
                fetch_main_step,
                pnpm_action,
                setup_node,
                node_version,
                pnpm_store_step,
                task,
                affected_flag,
                " --continue" // Run all packages even if one fails
            )
        };

        let job_blocks: Vec<String> = ci
            .jobs
            .iter()
            .map(|(task, timeout)| build_job(task, *timeout))
            .collect();

        Ok(format!(
            "# Auto-generated by airis gen — DO NOT EDIT\n# Change manifest.toml [ci] and [profile] sections instead.\n\nname: CI\n\non:\n  push:\n    branches: [{}]\n  pull_request:\n    branches: [{}]\n{}\njobs:\n{}\n",
            ci_branch,
            pr_target,
            concurrency,
            job_blocks.join("\n\n"),
        ))
    }

    /// Generate CI workflow for infrastructure-only repos (no Node.js)
    pub(super) fn render_infra_ci_workflow(&self, manifest: &Manifest) -> Result<String> {
        let ci = &manifest.ci;
        let a = ResolvedActions::from_manifest(&ci.actions)?;
        let checkout = &a.checkout;
        let runner = ci.runner.as_deref().unwrap_or("ubuntu-latest");
        let runner_yaml = if runner.contains(',') {
            format!("[{}]", runner)
        } else {
            runner.to_string()
        };

        let deploy_profiles = manifest.deploy_profiles();
        let pr_target = deploy_profiles
            .iter()
            .find(|(name, p)| p.effective_role(name) == "production")
            .map(|(_, p)| p.branch.as_deref().unwrap_or("main"))
            .unwrap_or("main");

        let validate_timeout = manifest.ci.validate_timeout.unwrap_or(5);
        Ok(format!(
            "# Auto-generated by airis gen — DO NOT EDIT\n# Change manifest.toml [ci] and [profile] sections instead.\n\nname: CI\n\non:\n  pull_request:\n    branches: [{pr_target}]\n\njobs:\n  validate:\n    runs-on: {runner_yaml}\n    timeout-minutes: {validate_timeout}\n    steps:\n      - uses: {checkout}\n      - name: Validate compose\n        run: docker compose config --quiet\n"
        ))
    }
}
