use super::TemplateEngine;
use crate::manifest::{MANIFEST_FILE, Manifest};
use anyhow::Result;
use indexmap::IndexMap;
use serde::Serialize;

/// Top-level Docker Compose file structure.
#[derive(Debug, Serialize)]
pub(crate) struct ComposeFile {
    #[serde(skip_serializing_if = "IndexMap::is_empty")]
    pub services: IndexMap<String, ComposeService>,
    #[serde(skip_serializing_if = "IndexMap::is_empty")]
    pub networks: IndexMap<String, ComposeNetwork>,
    #[serde(skip_serializing_if = "IndexMap::is_empty")]
    pub volumes: IndexMap<String, serde_json::Value>,
}

#[derive(Debug, Serialize)]
pub(crate) struct ComposeService {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub container_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub build: Option<ComposeBuild>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub working_dir: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deploy: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub command: Option<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub profiles: Vec<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub depends_on: Vec<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub ports: Vec<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub extra_hosts: Vec<String>,
    #[serde(skip_serializing_if = "IndexMap::is_empty")]
    pub environment: IndexMap<String, String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub volumes: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub shm_size: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub restart: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub runtime: Option<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub devices: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub network_mode: Option<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub labels: Vec<String>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub networks: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub healthcheck: Option<ComposeHealthcheck>,
}

#[derive(Debug, Serialize)]
pub(crate) struct ComposeBuild {
    pub context: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dockerfile: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub target: Option<String>,
}

#[derive(Debug, Serialize)]
pub(crate) struct ComposeNetwork {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    pub external: bool,
}

#[derive(Debug, Serialize)]
pub(crate) struct ComposeHealthcheck {
    pub test: Vec<String>,
    pub interval: String,
    pub timeout: String,
    pub retries: u64,
    pub start_period: String,
}

impl TemplateEngine {
    pub fn render_docker_compose(&self, manifest: &Manifest) -> Result<String> {
        let compose = self.build_compose_file(manifest, ".")?;

        let yaml = serde_yml::to_string(&compose)?;

        let project = &manifest.workspace.name;
        let header = format!(
            "# ============================================================\n\
             # {project}\n\
             # ============================================================\n\
             # Generated by `airis gen` - DO NOT EDIT MANUALLY\n\
             # Source of truth: manifest.toml\n\
             #\n\
             # Use `airis up` to start. Profiles control which services run.\n\
             # ============================================================\n\n"
        );

        Ok(format!("{header}{yaml}"))
    }

    pub(crate) fn build_compose_file(
        &self,
        manifest: &Manifest,
        root: &str,
    ) -> Result<ComposeFile> {
        let proxy_network = manifest
            .orchestration
            .networks
            .as_ref()
            .and_then(|n| n.proxy.clone());

        let default_external = manifest
            .orchestration
            .networks
            .as_ref()
            .map(|n| n.default_external)
            .unwrap_or(false);

        // Auto-generate artifact isolation volumes from workspace.clean.dirs + package paths
        let workdir = &manifest.workspace.workdir;
        let clean_dirs = &manifest.workspace.clean.dirs;
        let package_paths = manifest.all_workspace_paths_in(root);

        let mut artifact_volume_mounts: Vec<String> = Vec::new();
        let mut artifact_volume_names: Vec<String> = Vec::new();
        for pkg_path in &package_paths {
            for dir in clean_dirs {
                let dir_clean = dir.trim_start_matches('.');
                let path_clean = pkg_path.replace(['/', '-'], "_");
                let vol_name = format!("ws_{}_{}", dir_clean, path_clean);
                let mount = format!("{}:{}/{}/{}", vol_name, workdir, pkg_path, dir);
                artifact_volume_mounts.push(mount);
                if !artifact_volume_names.contains(&vol_name) {
                    artifact_volume_names.push(vol_name);
                }
            }
        }

        // Build services
        let mut services = IndexMap::new();
        for (name, svc) in &manifest.service {
            // Merge artifact volumes into services that have a build config
            let merged_volumes = if svc.build.is_some() {
                [artifact_volume_mounts.clone(), svc.volumes.clone()].concat()
            } else {
                svc.volumes.clone()
            };

            // Resolve env_groups into env map
            let mut resolved_env = IndexMap::new();
            for group_name in &svc.env_groups {
                if let Some(group) = manifest.env_group.get(group_name) {
                    for (k, v) in group {
                        resolved_env.insert(k.clone(), v.clone());
                    }
                }
            }
            for (k, v) in &svc.env {
                resolved_env.insert(k.clone(), v.clone());
            }

            let internal_port = svc.port.unwrap_or_else(|| {
                svc.ports
                    .first()
                    .and_then(|p| p.split(':').next_back())
                    .and_then(|p| p.parse::<u16>().ok())
                    .unwrap_or(crate::conventions::framework_defaults("node").port)
            });

            let container_name = svc
                .container_name
                .clone()
                .unwrap_or_else(|| format!("{}-{}", manifest.workspace.name, name));

            let build = svc.build.as_ref().map(|b| {
                let dockerfile = b.dockerfile.clone().unwrap_or_else(|| {
                    manifest
                        .app
                        .iter()
                        .find(|a| a.name == *name)
                        .and_then(|a| a.path.as_ref())
                        .map(|path| format!("{}/Dockerfile", path))
                        .unwrap_or_else(|| format!("{}/Dockerfile", name))
                });
                ComposeBuild {
                    context: b.context.clone(),
                    dockerfile: Some(dockerfile),
                    target: b.target.clone(),
                }
            });

            // GPU deploy section
            let deploy = if let Some(gpu) = &svc.gpu {
                Some(serde_json::json!({
                    "resources": {
                        "reservations": {
                            "devices": [{
                                "driver": gpu.driver,
                                "count": gpu.count,
                                "capabilities": gpu.capabilities,
                            }]
                        }
                    }
                }))
            } else if let Some(deploy) = &svc.deploy {
                deploy
                    .replicas
                    .map(|r| serde_json::json!({ "replicas": r }))
            } else {
                None
            };

            // Healthcheck from service config
            let healthcheck = svc.health_path.as_ref().map(|hp| {
                let port = internal_port;
                ComposeHealthcheck {
                    test: vec![
                        "CMD-SHELL".to_string(),
                        format!(
                            "node -e \"require('http').request({{hostname:'localhost',port:{port},path:'{hp}',timeout:5000}},(r)=>{{process.exit(r.statusCode===200?0:1)}}).on('error',()=>process.exit(1)).end()\""
                        ),
                    ],
                    interval: "30s".to_string(),
                    timeout: "10s".to_string(),
                    retries: 3,
                    start_period: "40s".to_string(),
                }
            });

            services.insert(
                name.clone(),
                ComposeService {
                    container_name: Some(container_name),
                    build,
                    image: svc.image.clone(),
                    working_dir: svc.working_dir.clone(),
                    deploy,
                    command: svc.command.clone(),
                    profiles: svc.profiles.clone(),
                    depends_on: svc.depends_on.clone(),
                    ports: svc.ports.clone(),
                    extra_hosts: svc.extra_hosts.clone(),
                    environment: resolved_env,
                    volumes: merged_volumes,
                    shm_size: svc.shm_size.clone(),
                    restart: svc.restart.clone(),
                    runtime: svc.runtime.clone(),
                    devices: svc.devices.clone(),
                    network_mode: svc.network_mode.clone(),
                    labels: svc.labels.clone(),
                    networks: svc.networks.clone(),
                    healthcheck,
                },
            );
        }

        // Collect volume names
        let mut volume_names: Vec<String> = artifact_volume_names;
        for svc in manifest.service.values() {
            for vol in &svc.volumes {
                if let Some(name) = vol.split(':').next()
                    && !name.starts_with('.')
                    && !name.starts_with('/')
                    && !volume_names.contains(&name.to_string())
                {
                    volume_names.push(name.to_string());
                }
            }
        }

        // Build networks
        let mut networks = IndexMap::new();
        let network_defs = manifest
            .orchestration
            .networks
            .as_ref()
            .map(|n| &n.define)
            .filter(|d| !d.is_empty());

        networks.insert(
            "default".to_string(),
            ComposeNetwork {
                name: Some(format!("{}_default", manifest.workspace.name)),
                external: default_external,
            },
        );

        if let Some(defs) = network_defs {
            for (net_name, net_val) in defs {
                networks.insert(
                    net_name.clone(),
                    ComposeNetwork {
                        name: net_val.name.clone(),
                        external: net_val.external,
                    },
                );
            }
        } else {
            networks.insert(
                "traefik".to_string(),
                ComposeNetwork {
                    name: Some("traefik_default".to_string()),
                    external: true,
                },
            );
            if let Some(pn) = &proxy_network {
                networks.insert(
                    pn.clone(),
                    ComposeNetwork {
                        name: None,
                        external: true,
                    },
                );
            }
        }

        // Build volumes map (just empty objects for declarations)
        let mut volumes = IndexMap::new();
        for vol_name in &volume_names {
            volumes.insert(vol_name.clone(), serde_json::json!(null));
        }

        Ok(ComposeFile {
            services,
            networks,
            volumes,
        })
    }

    pub(super) fn prepare_pnpm_workspace_data(
        &self,
        manifest: &Manifest,
    ) -> Result<serde_json::Value> {
        Ok(serde_json::json!({
            "packages": manifest.packages.workspaces,
            "manifest": MANIFEST_FILE,
        }))
    }

    // Keep prepare_docker_compose_data for backward compatibility with tests
    #[cfg(test)]
    pub(super) fn prepare_docker_compose_data(
        &self,
        manifest: &Manifest,
        root: &str,
    ) -> Result<serde_json::Value> {
        let compose = self.build_compose_file(manifest, root)?;

        // Convert to JSON for test backward compatibility
        let services: Vec<serde_json::Value> = compose
            .services
            .iter()
            .map(|(name, svc)| {
                let mut val = serde_json::json!({
                    "name": name,
                    "volumes": svc.volumes,
                    "port": svc.ports.first()
                        .and_then(|p| p.split(':').next_back())
                        .and_then(|p| p.parse::<u64>().ok())
                        .unwrap_or(3000),
                });
                if let Some(ref hp) = svc.healthcheck {
                    val["health_path"] = serde_json::json!(hp.test.get(1).unwrap_or(&String::new()));
                }
                val
            })
            .collect();

        let volume_names: Vec<String> = compose.volumes.keys().cloned().collect();

        Ok(serde_json::json!({
            "project": manifest.workspace.name,
            "workdir": manifest.workspace.workdir,
            "services": services,
            "volume_names": volume_names,
        }))
    }
}
