use super::TemplateEngine;
use crate::manifest::{MANIFEST_FILE, Manifest};
use anyhow::Result;
use serde_json::json;

impl TemplateEngine {
    pub fn render_docker_compose(&self, manifest: &Manifest) -> Result<String> {
        let data = self.prepare_docker_compose_data(manifest, ".")?;
        let project = data["project"].as_str().unwrap_or("");
        let services = data["services"].as_array();
        let volume_names = data["volume_names"].as_array();
        let proxy_network = data["proxy_network"].as_str();
        let default_external = data["default_external"].as_bool().unwrap_or(false);
        let network_defs = data["network_defs"].as_object();

        let mut out = String::new();

        // Header comment block
        out.push_str(&format!(
            "# ============================================================\n\
             # {project}\n\
             # ============================================================\n\
             # Generated by `airis gen` - DO NOT EDIT MANUALLY\n\
             # Source of truth: manifest.toml\n\
             #\n\
             # Use `airis up` to start. Profiles control which services run.\n\
             # ============================================================\n\
             \n\
             services:\n"
        ));

        // Services section
        if let Some(services) = services {
            for svc in services {
                let name = svc["name"].as_str().unwrap_or("");
                out.push_str(&format!("  {name}:\n"));

                // container_name
                if let Some(cn) = svc["container_name"].as_str() {
                    out.push_str(&format!("    container_name: {cn}\n"));
                }

                // build or image
                if let Some(build) = svc["build"].as_object() {
                    out.push_str("    build:\n");
                    if let Some(ctx) = build.get("context").and_then(|v| v.as_str()) {
                        out.push_str(&format!("      context: {ctx}\n"));
                    }
                    if let Some(df) = build.get("dockerfile").and_then(|v| v.as_str()) {
                        out.push_str(&format!("      dockerfile: {df}\n"));
                    }
                    if let Some(target) = build.get("target").and_then(|v| v.as_str()) {
                        out.push_str(&format!("      target: {target}\n"));
                    }
                } else if let Some(image) = svc["image"].as_str() {
                    out.push_str(&format!("    image: {image}\n"));
                }

                // working_dir
                if let Some(wd) = svc["working_dir"].as_str() {
                    out.push_str(&format!("    working_dir: {wd}\n"));
                }

                // gpu deploy or replicas deploy
                if let Some(gpu) = svc["gpu"].as_object() {
                    let driver = gpu
                        .get("driver")
                        .and_then(|v| v.as_str())
                        .unwrap_or("nvidia");
                    let count = gpu.get("count").and_then(|v| v.as_str()).unwrap_or("all");
                    let capabilities = gpu.get("capabilities").and_then(|v| v.as_array());
                    let caps_str = capabilities
                        .map(|arr| {
                            arr.iter()
                                .filter_map(|v| v.as_str())
                                .collect::<Vec<_>>()
                                .join(", ")
                        })
                        .unwrap_or_else(|| "gpu".to_string());
                    out.push_str("    deploy:\n");
                    out.push_str("      resources:\n");
                    out.push_str("        reservations:\n");
                    out.push_str("          devices:\n");
                    out.push_str(&format!(
                        "            - driver: {driver}\n\
                         \x20             count: {count}\n\
                         \x20             capabilities: [{caps_str}]\n"
                    ));
                } else if let Some(deploy) = svc["deploy"].as_object()
                    && let Some(replicas) = deploy.get("replicas").and_then(|v| v.as_u64())
                {
                    out.push_str(&format!("    deploy:\n      replicas: {replicas}\n"));
                }

                // command (raw, unescaped)
                if let Some(cmd) = svc["command"].as_str() {
                    out.push_str(&format!("    command: {cmd}\n"));
                }

                // profiles
                if let Some(profiles) = svc["profiles"].as_array()
                    && !profiles.is_empty()
                {
                    out.push_str("    profiles:\n");
                    for p in profiles {
                        if let Some(s) = p.as_str() {
                            out.push_str(&format!("      - \"{s}\"\n"));
                        }
                    }
                }

                // depends_on
                if let Some(deps) = svc["depends_on"].as_array()
                    && !deps.is_empty()
                {
                    out.push_str("    depends_on:\n");
                    for d in deps {
                        if let Some(s) = d.as_str() {
                            out.push_str(&format!("      - {s}\n"));
                        }
                    }
                }

                // ports
                if let Some(ports) = svc["ports"].as_array()
                    && !ports.is_empty()
                {
                    out.push_str("    ports:\n");
                    for p in ports {
                        if let Some(s) = p.as_str() {
                            out.push_str(&format!("      - \"{s}\"\n"));
                        }
                    }
                }

                // extra_hosts
                if let Some(hosts) = svc["extra_hosts"].as_array()
                    && !hosts.is_empty()
                {
                    out.push_str("    extra_hosts:\n");
                    for h in hosts {
                        if let Some(s) = h.as_str() {
                            out.push_str(&format!("      - \"{s}\"\n"));
                        }
                    }
                }

                // environment
                if let Some(env) = svc["env"].as_object()
                    && !env.is_empty()
                {
                    out.push_str("    environment:\n");
                    for (k, v) in env {
                        let val = v.as_str().unwrap_or("");
                        out.push_str(&format!("      {k}: \"{val}\"\n"));
                    }
                }

                // volumes
                if let Some(vols) = svc["volumes"].as_array()
                    && !vols.is_empty()
                {
                    out.push_str("    volumes:\n");
                    for v in vols {
                        if let Some(s) = v.as_str() {
                            out.push_str(&format!("      - {s}\n"));
                        }
                    }
                }

                // shm_size
                if let Some(shm) = svc["shm_size"].as_str() {
                    out.push_str(&format!("    shm_size: \"{shm}\"\n"));
                }

                // restart
                if let Some(restart) = svc["restart"].as_str() {
                    out.push_str(&format!("    restart: {restart}\n"));
                }

                // runtime
                if let Some(runtime) = svc["runtime"].as_str() {
                    out.push_str(&format!("    runtime: {runtime}\n"));
                }

                // devices
                if let Some(devices) = svc["devices"].as_array()
                    && !devices.is_empty()
                {
                    out.push_str("    devices:\n");
                    for d in devices {
                        if let Some(s) = d.as_str() {
                            out.push_str(&format!("      - {s}\n"));
                        }
                    }
                }

                // network_mode
                if let Some(nm) = svc["network_mode"].as_str() {
                    out.push_str(&format!("    network_mode: {nm}\n"));
                }

                // labels
                if let Some(labels) = svc["labels"].as_array()
                    && !labels.is_empty()
                {
                    out.push_str("    labels:\n");
                    for l in labels {
                        if let Some(s) = l.as_str() {
                            out.push_str(&format!("      - \"{s}\"\n"));
                        }
                    }
                }

                // networks
                if let Some(networks) = svc["networks"].as_array()
                    && !networks.is_empty()
                {
                    out.push_str("    networks:\n");
                    for n in networks {
                        if let Some(s) = n.as_str() {
                            out.push_str(&format!("      - {s}\n"));
                        }
                    }
                }

                // healthcheck
                if let Some(hp) = svc["health_path"].as_str() {
                    let port = svc["port"].as_u64().unwrap_or(3000);
                    let interval = svc
                        .get("health_interval")
                        .and_then(|v| v.as_str())
                        .unwrap_or("30s");
                    let timeout = svc
                        .get("health_timeout")
                        .and_then(|v| v.as_str())
                        .unwrap_or("10s");
                    let retries = svc
                        .get("health_retries")
                        .and_then(|v| v.as_u64())
                        .unwrap_or(3);
                    let start_period = svc
                        .get("health_start_period")
                        .and_then(|v| v.as_str())
                        .unwrap_or("40s");
                    out.push_str("    healthcheck:\n");
                    out.push_str(&format!(
                        "      test: [\"CMD-SHELL\", \"node -e \\\"require('http').request({{hostname:'localhost',port:{port},path:'{hp}',timeout:5000}},(r)=>{{process.exit(r.statusCode===200?0:1)}}).on('error',()=>process.exit(1)).end()\\\"\"]\n"
                    ));
                    out.push_str(&format!("      interval: {interval}\n"));
                    out.push_str(&format!("      timeout: {timeout}\n"));
                    out.push_str(&format!("      retries: {retries}\n"));
                    out.push_str(&format!("      start_period: {start_period}\n"));
                }

                // Blank line after each service
                out.push('\n');
            }
        }

        // Extra blank line after services
        out.push('\n');

        // Networks section
        if let Some(defs) = network_defs {
            out.push_str("networks:\n");
            out.push_str(&format!(
                "  default:\n    name: {project}_default\n    external: {default_external}\n"
            ));
            for (net_name, net_val) in defs {
                let external = net_val
                    .get("external")
                    .and_then(|v| v.as_bool())
                    .unwrap_or(false);
                out.push_str(&format!("  {net_name}:\n    external: {external}\n"));
                if let Some(n) = net_val.get("name").and_then(|v| v.as_str()) {
                    out.push_str(&format!("    name: {n}\n"));
                }
            }
        } else {
            out.push_str("networks:\n");
            out.push_str(&format!(
                "  default:\n    name: {project}_default\n    external: {default_external}\n"
            ));
            out.push_str("  traefik:\n    name: traefik_default\n    external: true\n");
            if let Some(pn) = proxy_network {
                out.push_str(&format!("  {pn}:\n    external: true\n"));
            }
        }

        // Volumes section
        out.push_str("\nvolumes:\n");
        if let Some(vols) = volume_names {
            for v in vols {
                if let Some(s) = v.as_str() {
                    out.push_str(&format!("  {s}:\n"));
                }
            }
        }

        Ok(out)
    }

    pub(super) fn prepare_pnpm_workspace_data(
        &self,
        manifest: &Manifest,
    ) -> Result<serde_json::Value> {
        Ok(json!({
            "packages": manifest.packages.workspaces,
            "manifest": MANIFEST_FILE,
        }))
    }

    pub(super) fn prepare_docker_compose_data(
        &self,
        manifest: &Manifest,
        root: &str,
    ) -> Result<serde_json::Value> {
        // Get proxy network from orchestration.networks config (None if not set)
        let proxy_network = manifest
            .orchestration
            .networks
            .as_ref()
            .and_then(|n| n.proxy.clone());

        let default_external = manifest
            .orchestration
            .networks
            .as_ref()
            .map(|n| n.default_external)
            .unwrap_or(false);

        // Auto-generate artifact isolation volumes from workspace.clean.dirs + package paths
        let workdir = &manifest.workspace.workdir;
        let clean_dirs = &manifest.workspace.clean.dirs;
        let package_paths = manifest.all_workspace_paths_in(root);

        let mut artifact_volume_mounts: Vec<String> = Vec::new();
        let mut artifact_volume_names: Vec<String> = Vec::new();
        for pkg_path in &package_paths {
            for dir in clean_dirs {
                let dir_clean = dir.trim_start_matches('.');
                let path_clean = pkg_path.replace(['/', '-'], "_");
                let vol_name = format!("ws_{}_{}", dir_clean, path_clean);
                let mount = format!("{}:{}/{}/{}", vol_name, workdir, pkg_path, dir);
                artifact_volume_mounts.push(mount);
                if !artifact_volume_names.contains(&vol_name) {
                    artifact_volume_names.push(vol_name);
                }
            }
        }

        // Build services — each service defines its own build/image in manifest
        let services: Vec<serde_json::Value> = manifest
            .service
            .iter()
            .map(|(name, svc)| {
                // Merge artifact volumes into services that have a build config (not external images)
                let merged_volumes = if svc.build.is_some() {
                    [artifact_volume_mounts.clone(), svc.volumes.clone()].concat()
                } else {
                    svc.volumes.clone()
                };

                // Resolve env_groups: expand group references into env map
                let mut resolved_env = indexmap::IndexMap::new();
                for group_name in &svc.env_groups {
                    if let Some(group) = manifest.env_group.get(group_name) {
                        for (k, v) in group {
                            resolved_env.insert(k.clone(), v.clone());
                        }
                    }
                }
                // Explicit env overrides env_group values
                for (k, v) in &svc.env {
                    resolved_env.insert(k.clone(), v.clone());
                }

                // No auto-watch — bind mount is gone, use `airis up` to rebuild
                // Extract internal port: explicit port > ports mapping > default 3000
                let internal_port = svc.port.unwrap_or_else(|| {
                    svc.ports
                        .first()
                        .and_then(|p| p.split(':').next_back())
                        .and_then(|p| p.parse::<u16>().ok())
                        .unwrap_or(crate::conventions::framework_defaults("node").port)
                });

                // Convention defaults: derive values from manifest when not explicitly set
                let container_name = svc
                    .container_name
                    .clone()
                    .unwrap_or_else(|| format!("{}-{}", manifest.workspace.name, name));

                // Apply build defaults: dockerfile from matching app path
                let build = svc.build.as_ref().map(|b| {
                    let dockerfile = b.dockerfile.clone().unwrap_or_else(|| {
                        manifest
                            .app
                            .iter()
                            .find(|a| a.name == *name)
                            .and_then(|a| a.path.as_ref())
                            .map(|path| format!("{}/Dockerfile", path))
                            .unwrap_or_else(|| format!("{}/Dockerfile", name))
                    });
                    let mut build_json = json!({
                        "context": b.context,
                        "dockerfile": dockerfile,
                    });
                    if let Some(ref target) = b.target {
                        build_json["target"] = json!(target);
                    }
                    build_json
                });

                json!({
                    "name": name,
                    "image": svc.image,
                    "build": build,
                    "port": internal_port,
                    "ports": svc.ports,
                    "command": svc.command,
                    "volumes": merged_volumes,
                    "env": resolved_env,
                    "profiles": svc.profiles,
                    "depends_on": svc.depends_on,
                    "restart": svc.restart,
                    "shm_size": svc.shm_size,
                    "container_name": container_name,
                    "working_dir": svc.working_dir,
                    "extra_hosts": svc.extra_hosts,
                    "deploy": svc.deploy,
                    "devices": svc.devices,
                    "runtime": svc.runtime,
                    "gpu": svc.gpu,
                    "health_path": svc.health_path,
                    "mem_limit": svc.mem_limit,
                    "cpus": svc.cpus,
                    "network_mode": svc.network_mode,
                    "labels": svc.labels,
                    "networks": svc.networks,
                })
            })
            .collect();

        // Collect all named volume declarations: artifact volumes + service-specific volumes
        let mut volume_names: Vec<String> = artifact_volume_names;
        for svc in manifest.service.values() {
            for vol in &svc.volumes {
                // Named volumes have format "name:/path" (no ./ or / prefix)
                if let Some(name) = vol.split(':').next()
                    && !name.starts_with('.')
                    && !name.starts_with('/')
                    && !volume_names.contains(&name.to_string())
                {
                    volume_names.push(name.to_string());
                }
            }
        }

        let network_defs = manifest
            .orchestration
            .networks
            .as_ref()
            .map(|n| &n.define)
            .filter(|d| !d.is_empty());

        Ok(json!({
            "project": manifest.workspace.name,
            "workdir": manifest.workspace.workdir,
            "services": services,
            "proxy_network": proxy_network,
            "default_external": default_external,
            "volume_names": volume_names,
            "network_defs": network_defs,
        }))
    }
}
