use super::TemplateEngine;
use anyhow::{Context, Result};

impl TemplateEngine {
    /// Render a production Dockerfile for a service using turbo prune pattern.
    pub fn render_service_dockerfile(
        &self,
        app: &crate::manifest::ProjectDefinition,
        pnpm_version: &str,
    ) -> Result<String> {
        let deploy = app
            .deploy
            .as_ref()
            .context("deploy config is required for service Dockerfile generation")?;

        let framework = app.framework.as_deref().unwrap_or("node");
        let conventions = crate::conventions::framework_defaults(framework);
        let variant = deploy.variant.as_deref().unwrap_or(match framework {
            "nextjs" => "nextjs",
            "python" => "python",
            _ => "node",
        });
        let path = app.path.as_deref().unwrap_or(&app.name);
        let scope = app.scope.as_deref().unwrap_or("@workspace");
        let port = deploy.port.unwrap_or(conventions.port);

        let entrypoint = deploy
            .entrypoint
            .clone()
            .unwrap_or_else(|| format!("{}/{}", path, conventions.entrypoint));

        // Pre-compute build arg lines
        let build_args_lines: Vec<String> = deploy
            .build_args
            .iter()
            .flat_map(|arg| vec![format!("ARG {}", arg), format!("ENV {}=${{{}}}", arg, arg)])
            .collect();

        // Build package manager install command from manifest
        let pm_install_cmd = if pnpm_version.is_empty() {
            "npm install -g pnpm".to_string()
        } else {
            format!("npm install -g pnpm@{}", pnpm_version)
        };

        // Python projects maintain their own Dockerfiles — skip generation
        if variant == "python" {
            anyhow::bail!(
                "Python projects use hand-written Dockerfiles. \
                 Ensure {}/Dockerfile exists.",
                path
            );
        }

        let node_image = crate::channel::defaults::NODE_LTS_IMAGE;
        let is_nextjs = variant == "nextjs";
        let is_node = variant == "node" || variant == "worker";
        let is_worker = variant == "worker";
        let health_path = deploy.health_path.as_deref().unwrap_or("/health");
        let health_interval = &deploy.health_interval;
        let health_timeout = deploy.health_timeout.as_deref().unwrap_or("10s");
        let health_start_period = deploy.health_start_period.as_deref().unwrap_or("30s");
        let health_retries = deploy.health_retries.unwrap_or(3);

        // Build extra_apk string
        let extra_apk_str: String = deploy
            .extra_apk
            .iter()
            .map(|pkg| format!(" {}", pkg))
            .collect();

        let mut out = String::new();

        // Header
        use std::fmt::Write;
        writeln!(out, "# Auto-generated by airis gen").unwrap();
        writeln!(
            out,
            "# DO NOT EDIT - change manifest.toml [app.deploy] instead."
        )
        .unwrap();
        writeln!(out, "#").unwrap();
        writeln!(out, "# Single image for all environments (local/stg/prd).").unwrap();
        writeln!(
            out,
            "# Environment differences are handled by env vars (Doppler) and compose command."
        )
        .unwrap();
        writeln!(out, "#").unwrap();
        writeln!(
            out,
            "# Variant: {} | Package: {}/{}",
            variant, scope, app.name
        )
        .unwrap();
        writeln!(out).unwrap();

        // base stage
        writeln!(
            out,
            "# ── base ──────────────────────────────────────────────────────────"
        )
        .unwrap();
        writeln!(out, "FROM {} AS base", node_image).unwrap();
        writeln!(
            out,
            "RUN apk add --no-cache libc6-compat{} \\",
            extra_apk_str
        )
        .unwrap();
        writeln!(out, " && {}", pm_install_cmd).unwrap();
        writeln!(out).unwrap();

        // pruner stage
        writeln!(
            out,
            "# ── pruner ────────────────────────────────────────────────────────"
        )
        .unwrap();
        writeln!(out, "FROM base AS pruner").unwrap();
        writeln!(out, "WORKDIR /app").unwrap();
        writeln!(out, "ENV PNPM_HOME=\"/pnpm/global\"").unwrap();
        writeln!(out, "ENV PATH=\"$PNPM_HOME:$PATH\"").unwrap();
        writeln!(out, "RUN pnpm add -g turbo").unwrap();
        writeln!(out, "COPY . .").unwrap();
        writeln!(out, "RUN turbo prune {}/{} --docker", scope, app.name).unwrap();
        writeln!(out).unwrap();

        // deps stage
        writeln!(
            out,
            "# ── deps ──────────────────────────────────────────────────────────"
        )
        .unwrap();
        writeln!(out, "FROM base AS deps").unwrap();
        writeln!(out, "WORKDIR /app").unwrap();
        writeln!(out, "COPY --from=pruner /app/out/json/ .").unwrap();
        writeln!(
            out,
            "RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install"
        )
        .unwrap();
        writeln!(out).unwrap();

        // builder stage
        writeln!(
            out,
            "# ── builder ───────────────────────────────────────────────────────"
        )
        .unwrap();
        writeln!(out, "FROM deps AS builder").unwrap();
        writeln!(out, "WORKDIR /app").unwrap();
        writeln!(out, "COPY --from=pruner /app/out/full/ .").unwrap();
        writeln!(out, "COPY --from=pruner /app/tsconfig.base.json ./").unwrap();
        for line in &build_args_lines {
            writeln!(out, "{}", line).unwrap();
        }
        writeln!(
            out,
            "RUN pnpm turbo run build --filter={}/{}",
            scope, app.name
        )
        .unwrap();
        if is_node {
            writeln!(
                out,
                "RUN pnpm deploy --legacy --filter={}/{} --prod /app/deploy",
                scope, app.name
            )
            .unwrap();
        }
        writeln!(out).unwrap();

        // runtime stage
        writeln!(
            out,
            "# ── runtime ───────────────────────────────────────────────────────"
        )
        .unwrap();
        writeln!(out, "FROM {}", node_image).unwrap();
        writeln!(out, "WORKDIR /app").unwrap();
        writeln!(out).unwrap();
        writeln!(out, "RUN apk add --no-cache libc6-compat wget").unwrap();
        writeln!(out).unwrap();

        if is_nextjs {
            writeln!(out, "COPY --from=builder /app/{}/.next/standalone ./", path).unwrap();
            writeln!(
                out,
                "COPY --from=builder /app/{}/.next/static ./{}/.next/static",
                path, path
            )
            .unwrap();
            writeln!(
                out,
                "COPY --from=builder /app/{}/public ./{}/public",
                path, path
            )
            .unwrap();
        } else {
            writeln!(
                out,
                "COPY --from=builder /app/{}/dist ./{}/dist",
                path, path
            )
            .unwrap();
            writeln!(
                out,
                "COPY --from=builder /app/deploy/package.json ./{}/",
                path
            )
            .unwrap();
            writeln!(
                out,
                "COPY --from=builder /app/deploy/node_modules ./{}/node_modules",
                path
            )
            .unwrap();
        }
        writeln!(out).unwrap();

        writeln!(
            out,
            "RUN addgroup -g 1001 -S nodejs && adduser -S nodejs -u 1001"
        )
        .unwrap();
        writeln!(out, "USER nodejs").unwrap();
        writeln!(out).unwrap();

        if !is_worker {
            writeln!(out, "EXPOSE {}", port).unwrap();
            writeln!(out).unwrap();
            writeln!(
                out,
                "HEALTHCHECK --interval={} --timeout={} --start-period={} --retries={} \\",
                health_interval, health_timeout, health_start_period, health_retries
            )
            .unwrap();
            writeln!(
                out,
                "  CMD wget -q --spider http://localhost:{}{} || exit 1",
                port, health_path
            )
            .unwrap();
            writeln!(out).unwrap();
        }

        writeln!(out, "CMD [\"node\", \"{}\"]", entrypoint).unwrap();

        Ok(out)
    }
}
