use super::actions::ResolvedActions;
use super::TemplateEngine;
use crate::manifest::Manifest;
use anyhow::{Context, Result};

impl TemplateEngine {
    /// Generate .github/workflows/e2e-staging.yml from manifest
    pub fn render_e2e_workflow(&self, manifest: &Manifest) -> Result<String> {
        let ci = &manifest.ci;
        let a = ResolvedActions::from_manifest(&ci.actions)?;
        let checkout = &a.checkout;
        let doppler_action = &a.doppler;
        let upload_artifact_version = &a.upload_artifact;

        let runner = ci.runner.as_deref().unwrap_or("ubuntu-latest");
        let runner_yaml = if runner.contains(',') {
            format!("[{}]", runner)
        } else {
            runner.to_string()
        };

        // Find staging profile
        let deploy_profiles = manifest.deploy_profiles();
        let stg_profile = deploy_profiles
            .iter()
            .find(|(name, p)| p.effective_role(name) == "staging");

        let stg_branch = stg_profile
            .map(|(_, p)| p.branch.as_deref().unwrap_or("stg"))
            .unwrap_or("stg");

        let doppler = stg_profile
            .and_then(|(_, p)| p.env_source.doppler_config())
            .context("E2E workflow requires a staging profile with Doppler env_source")?;
        let doppler_config = &doppler.config;
        let doppler_secret = &doppler.secret;

        // E2E config with defaults
        let e2e = &ci.e2e;
        let trigger_workflow = e2e.trigger_workflow.as_deref().unwrap_or("Deploy");
        let test_filter = e2e.test_filter.as_deref().unwrap_or("staging-smoke");
        let timeout = e2e.timeout.unwrap_or(15);

        // Playwright image from inject (value may already contain "FROM " prefix)
        let playwright_image = manifest
            .inject
            .get("playwright_image")
            .map(|v| match v {
                crate::manifest::InjectValue::Simple(s) => s.clone(),
                crate::manifest::InjectValue::Template { template, .. } => template.clone(),
            })
            .unwrap_or_else(|| "FROM mcr.microsoft.com/playwright:v1.52.0-noble".to_string());

        let workspace_name = &manifest.workspace.name;
        let package_manager = &manifest.workspace.package_manager;

        Ok(format!(
            "\
# Auto-generated by airis gen — DO NOT EDIT
# Change manifest.toml [ci.e2e] and [profile] sections instead.

name: E2E Staging

on:
  workflow_run:
    workflows: [\"{trigger_workflow}\"]
    types: [completed]
    branches: [{stg_branch}]
  workflow_dispatch:
    inputs:
      test_filter:
        description: \"Test file filter (e.g., staging-smoke)\"
        required: false
        default: \"{test_filter}\"

concurrency:
  group: ${{{{ github.workflow }}}}-${{{{ github.ref }}}}
  cancel-in-progress: true

jobs:
  e2e:
    name: E2E Tests
    runs-on: {runner_yaml}
    if: ${{{{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}}}
    timeout-minutes: {timeout}
    steps:
      - uses: {checkout}
      - uses: {doppler_action}

      - name: Resolve staging URLs from Doppler
        env:
          DOPPLER_TOKEN: ${{{{ secrets.{doppler_secret} }}}}
        run: |
          DOMAIN=\"$(doppler secrets get CORPORATE_DOMAIN --plain -c {doppler_config})\"
          if [ -z \"$DOMAIN\" ]; then
            echo \"::error::CORPORATE_DOMAIN not found in Doppler {doppler_config} config\"
            exit 1
          fi
          echo \"E2E_BASE_URL=https://${{DOMAIN}}\" >> \"$GITHUB_ENV\"
          echo \"STAGING_CORPORATE_URL=https://${{DOMAIN}}\" >> \"$GITHUB_ENV\"
          echo \"STAGING_DASHBOARD_URL=https://dashboard.${{DOMAIN}}\" >> \"$GITHUB_ENV\"

      - name: Build test image
        run: |
          docker build -t {workspace_name}-e2e -f - . <<'DOCKERFILE'
          {playwright_image}
          WORKDIR /app
          RUN corepack enable && corepack prepare {package_manager} --activate
          COPY package.json pnpm-lock.yaml pnpm-workspace.yaml tsconfig.base.json ./
          COPY libs/ libs/
          COPY e2e/ e2e/
          COPY playwright.config.ts playwright.staging.config.ts ./
          RUN pnpm install --frozen-lockfile
          RUN pnpm --filter './libs/*' build
          DOCKERFILE

      - name: Run E2E tests against staging
        run: |
          TEST_FILTER=\"${{{{ github.event.inputs.test_filter || '{test_filter}' }}}}\"
          docker run --rm \\
            -e E2E_BASE_URL \\
            -e STAGING_CORPORATE_URL \\
            -e STAGING_DASHBOARD_URL \\
            -e CI=true \\
            {workspace_name}-e2e \\
            npx playwright test \"$TEST_FILTER\" --config=playwright.staging.config.ts

      - name: Upload test results
        uses: {upload_artifact_version}
        if: always()
        with:
          name: playwright-report
          path: e2e/report/
          retention-days: 7

  notify:
    name: Notify Results
    runs-on: {runner_yaml}
    needs: e2e
    if: always()
    steps:
      - name: Report status
        run: |
          if [ \"${{{{ needs.e2e.result }}}}\" = \"success\" ]; then
            echo \"✅ E2E tests passed on staging\"
          else
            echo \"❌ E2E tests failed on staging\"
            exit 1
          fi
"
        ))
    }
}
