use super::TemplateEngine;
use crate::manifest::Manifest;
use anyhow::Result;

pub(super) const NPMRC_CONTENT: &str = "\
# Auto-generated by airis init
# DO NOT EDIT — regenerate with: airis gen
# Ensures pnpm store stays inside the container volume
store-dir=/pnpm/store
virtual-store-dir=/pnpm/virtual-store
";

impl TemplateEngine {
    /// Generate .env.example from manifest.toml [env] section
    pub fn render_env_example(&self, manifest: &Manifest) -> Result<String> {
        let mut lines = vec![
            "# Auto-generated by airis init".to_string(),
            "# DO NOT commit .env file - this is just an example".to_string(),
            "# Copy to .env and fill in actual values".to_string(),
            "".to_string(),
        ];

        // Required variables
        if !manifest.env.required.is_empty() {
            lines.push("# Required environment variables".to_string());
            for var in &manifest.env.required {
                let validation = manifest.env.validation.get(var);
                if let Some(v) = validation
                    && let Some(desc) = &v.description
                {
                    lines.push(format!("# {}", desc));
                }
                let example_value = validation
                    .and_then(|v| v.example.as_ref())
                    .map(|e| e.as_str())
                    .unwrap_or("your_value_here");
                lines.push(format!("{}={}", var, example_value));
            }
            lines.push("".to_string());
        }

        // Optional variables
        if !manifest.env.optional.is_empty() {
            lines.push("# Optional environment variables".to_string());
            for var in &manifest.env.optional {
                let validation = manifest.env.validation.get(var);
                if let Some(v) = validation
                    && let Some(desc) = &v.description
                {
                    lines.push(format!("# {}", desc));
                }
                let example_value = validation
                    .and_then(|v| v.example.as_ref())
                    .map(|e| e.as_str())
                    .unwrap_or("");
                lines.push(format!("# {}={}", var, example_value));
            }
        }

        Ok(lines.join("\n"))
    }

    /// Generate .envrc for direnv
    /// Adds .airis/bin to PATH and sets COMPOSE_PROJECT_NAME
    pub fn render_envrc(&self, manifest: &Manifest) -> Result<String> {
        let lines = vec![
            "# Auto-generated by airis init".to_string(),
            "# Enable with: direnv allow".to_string(),
            "".to_string(),
            "# Add guards to PATH".to_string(),
            "export PATH=\"$PWD/.airis/bin:$PATH\"".to_string(),
            "".to_string(),
            "# Docker Compose".to_string(),
            "export COMPOSE_PROFILES=\"${COMPOSE_PROFILES:-shell,web}\"".to_string(),
            format!(
                "export COMPOSE_PROJECT_NAME=\"{}\"",
                manifest.workspace.name
            ),
        ];

        Ok(lines.join("\n"))
    }

    /// Generate .npmrc for pnpm store isolation
    pub fn render_npmrc(&self) -> Result<String> {
        Ok(NPMRC_CONTENT.to_string())
    }
}
