use super::TemplateEngine;
use crate::manifest::{Manifest, CatalogEntry};
use anyhow::Context;
use anyhow::Result;
use indexmap::IndexMap;

impl TemplateEngine {
    /// Render root package.json.
    ///
    /// Root package.json now uses "catalog:" protocol for shared dependencies,
    /// delegating actual resolution and locking to pnpm.
    pub fn render_package_json(
        &self,
        manifest: &Manifest,
        _resolved_catalog: &IndexMap<String, String>,
    ) -> Result<String> {
        let mut obj = serde_json::Map::new();

        obj.insert(
            "name".to_string(),
            serde_json::json!(manifest.workspace.name),
        );
        obj.insert("version".to_string(), serde_json::json!("0.0.0"));
        obj.insert("private".to_string(), serde_json::json!(true));
        obj.insert("type".to_string(), serde_json::json!("module"));
        
        if !manifest.workspace.package_manager.is_empty() {
            obj.insert(
                "packageManager".to_string(),
                serde_json::json!(manifest.workspace.package_manager),
            );
        }

        if !manifest.packages.workspaces.is_empty() {
            obj.insert(
                "workspaces".to_string(),
                serde_json::to_value(&manifest.packages.workspaces)?,
            );
        }

        // Add root dependencies from manifest.packages.root
        let root_pkg = &manifest.packages.root;

        if !root_pkg.scripts.is_empty() {
            obj.insert(
                "scripts".to_string(),
                serde_json::to_value(&root_pkg.scripts)?,
            );
        }

        if !root_pkg.dependencies.is_empty() {
            let mut deps = serde_json::Map::new();
            for (k, v) in &root_pkg.dependencies {
                // If it's in the manifest catalog, use "catalog:"
                let version = if manifest.packages.catalog.contains_key(k) {
                    "catalog:".to_string()
                } else {
                    v.clone()
                };
                deps.insert(k.clone(), serde_json::json!(version));
            }
            obj.insert("dependencies".to_string(), serde_json::Value::Object(deps));
        }

        if !root_pkg.dev_dependencies.is_empty() {
            let mut dev_deps = serde_json::Map::new();
            for (k, v) in &root_pkg.dev_dependencies {
                let version = if manifest.packages.catalog.contains_key(k) {
                    "catalog:".to_string()
                } else {
                    v.clone()
                };
                dev_deps.insert(k.clone(), serde_json::json!(version));
            }
            obj.insert("devDependencies".to_string(), serde_json::Value::Object(dev_deps));
        }

        if !root_pkg.engines.is_empty() {
            obj.insert(
                "engines".to_string(),
                serde_json::to_value(&root_pkg.engines)?,
            );
        }

        // pnpm specific config
        if !root_pkg.pnpm.overrides.is_empty()
            || !root_pkg.pnpm.peer_dependency_rules.ignore_missing.is_empty()
        {
            let mut pnpm = serde_json::Map::new();
            if !root_pkg.pnpm.overrides.is_empty() {
                pnpm.insert(
                    "overrides".to_string(),
                    serde_json::to_value(&root_pkg.pnpm.overrides)?,
                );
            }
            obj.insert("pnpm".to_string(), serde_json::Value::Object(pnpm));
        }

        // Update generation marker
        obj.insert("_generated".to_string(), serde_json::json!({
            "by": "airis gen",
            "mode": "full",
            "warning": "This file is fully generated by airis gen. Do not edit manually."
        }));

        let package_json = serde_json::Value::Object(obj);
        let content = serde_json::to_string_pretty(&package_json)
            .context("Failed to serialize package.json")?;
        Ok(format!("{content}\n"))
    }

    /// Render pnpm-workspace.yaml with catalogs support.
    pub fn render_pnpm_workspace(&self, manifest: &Manifest) -> Result<String> {
        let mut out = String::from(
            "# Auto-generated by airis gen\n\
             # DO NOT EDIT - change manifest.toml instead.\n\
             \n\
             packages:\n",
        );
        for pkg in &manifest.packages.workspaces {
            out.push_str(&format!("  - \"{pkg}\"\n"));
        }

        if !manifest.packages.catalog.is_empty() {
            out.push_str("\ncatalog:\n");
            for (name, entry) in &manifest.packages.catalog {
                let version = match entry {
                    CatalogEntry::Version(v) => v.clone(),
                    CatalogEntry::Policy(p) => p.as_str().to_string(),
                    CatalogEntry::Empty(_) => "latest".to_string(),
                    CatalogEntry::Follow(f) => format!("catalog:{}", f.follow),
                };
                out.push_str(&format!("  \"{}\": \"{}\"\n", name, version));
            }
        }
        
        Ok(out)
    }
}
