use super::TemplateEngine;
use crate::manifest::Manifest;
use anyhow::Context;
use anyhow::Result;
use indexmap::IndexMap;

impl TemplateEngine {
    /// Render root package.json.
    ///
    /// The root package.json is tool-owned and fully generated from manifest.toml.
    pub fn render_package_json(
        &self,
        manifest: &Manifest,
        resolved_catalog: &IndexMap<String, String>,
    ) -> Result<String> {
        let mut obj = serde_json::Map::new();

        obj.insert(
            "name".to_string(),
            serde_json::json!(manifest.workspace.name),
        );
        obj.insert("version".to_string(), serde_json::json!("0.0.0"));
        obj.insert("private".to_string(), serde_json::json!(true));
        obj.insert("type".to_string(), serde_json::json!("module"));
        
        if !manifest.workspace.package_manager.is_empty() {
            obj.insert(
                "packageManager".to_string(),
                serde_json::json!(manifest.workspace.package_manager),
            );
        }

        if !manifest.packages.workspaces.is_empty() {
            obj.insert(
                "workspaces".to_string(),
                serde_json::to_value(&manifest.packages.workspaces)?,
            );
        }

        // Add root dependencies from manifest.packages.root
        let root_pkg = &manifest.packages.root;

        if !root_pkg.scripts.is_empty() {
            obj.insert(
                "scripts".to_string(),
                serde_json::to_value(&root_pkg.scripts)?,
            );
        }

        if !root_pkg.dependencies.is_empty() {
            let mut deps = serde_json::Map::new();
            for (k, v) in &root_pkg.dependencies {
                let version = if v == "catalog" || v == "catalog:" {
                    resolved_catalog.get(k).cloned().unwrap_or_else(|| v.clone())
                } else {
                    v.clone()
                };
                deps.insert(k.clone(), serde_json::json!(version));
            }
            obj.insert("dependencies".to_string(), serde_json::Value::Object(deps));
        }

        if !root_pkg.dev_dependencies.is_empty() {
            let mut dev_deps = serde_json::Map::new();
            for (k, v) in &root_pkg.dev_dependencies {
                let version = if v == "catalog" || v == "catalog:" {
                    resolved_catalog.get(k).cloned().unwrap_or_else(|| v.clone())
                } else {
                    v.clone()
                };
                dev_deps.insert(k.clone(), serde_json::json!(version));
            }
            obj.insert("devDependencies".to_string(), serde_json::Value::Object(dev_deps));
        }

        if !root_pkg.engines.is_empty() {
            obj.insert(
                "engines".to_string(),
                serde_json::to_value(&root_pkg.engines)?,
            );
        }

        // pnpm specific config
        if !root_pkg.pnpm.overrides.is_empty()
            || !root_pkg.pnpm.peer_dependency_rules.ignore_missing.is_empty()
        {
            let mut pnpm = serde_json::Map::new();
            if !root_pkg.pnpm.overrides.is_empty() {
                pnpm.insert(
                    "overrides".to_string(),
                    serde_json::to_value(&root_pkg.pnpm.overrides)?,
                );
            }
            obj.insert("pnpm".to_string(), serde_json::Value::Object(pnpm));
        }

        // Update generation marker
        obj.insert("_generated".to_string(), serde_json::json!({
            "by": "airis gen",
            "mode": "full",
            "warning": "This file is fully generated by airis gen. Do not edit manually."
        }));

        let package_json = serde_json::Value::Object(obj);
        let content = serde_json::to_string_pretty(&package_json)
            .context("Failed to serialize package.json")?;
        Ok(format!("{content}\n"))
    }

    pub fn render_pnpm_workspace(&self, manifest: &Manifest) -> Result<String> {
        let mut out = String::from(
            "# Auto-generated by airis init\n\
             # DO NOT EDIT - change manifest.toml instead.\n\
             #\n\
             # NOTE: No catalog section needed!\n\
             # airis resolves versions from manifest.toml [packages.catalog] and writes\n\
             # them directly to package.json. This is a superior approach because:\n\
             # - Works with any package manager (pnpm/npm/yarn/bun)\n\
             # - Supports \"latest\", \"lts\", \"follow\" policies via airis\n\
             # - No dependency on pnpm's catalog feature\n\
             #\n\
             # Use manifest.toml [packages.catalog] for version management:\n\
             #   [packages.catalog]\n\
             #   next = \"latest\"      # airis resolves to ^16.0.3\n\
             #   react = \"lts\"        # airis resolves to ^18.3.1\n\
             #\n\
             # Then reference in dependencies:\n\
             #   [packages.root.devDependencies]\n\
             #   next = \"catalog:\"    # → ^16.0.3 in package.json\n\
             \n\
             packages:\n",
        );
        for pkg in &manifest.packages.workspaces {
            out.push_str(&format!("  - \"{pkg}\"\n"));
        }
        Ok(out)
    }
}
