use super::TemplateEngine;
use crate::manifest::Manifest;
use anyhow::Context;
use anyhow::Result;
use indexmap::IndexMap;

impl TemplateEngine {
    /// Render root package.json in hybrid mode.
    ///
    /// Managed fields: name, version, private, type, packageManager, workspaces.
    /// All other fields (dependencies, scripts, engines, pnpm config) are user-managed.
    pub fn render_package_json(
        &self,
        manifest: &Manifest,
        _resolved_catalog: &IndexMap<String, String>,
    ) -> Result<String> {
        let managed_fields = [
            "name",
            "version",
            "private",
            "type",
            "packageManager",
            "workspaces",
        ];

        // Read existing package.json if it exists
        let package_json_path = std::path::Path::new("package.json");
        let mut package_json = if package_json_path.exists() {
            let existing = std::fs::read_to_string(package_json_path)
                .context("Failed to read existing root package.json")?;
            serde_json::from_str::<serde_json::Value>(&existing)
                .context("Failed to parse existing root package.json")?
        } else {
            serde_json::json!({})
        };

        let obj = package_json
            .as_object_mut()
            .ok_or_else(|| anyhow::anyhow!("Root package.json is not a JSON object"))?;

        // Update only managed fields
        obj.insert(
            "name".to_string(),
            serde_json::json!(manifest.workspace.name),
        );
        obj.insert("version".to_string(), serde_json::json!("0.0.0"));
        obj.insert("private".to_string(), serde_json::json!(true));
        obj.insert("type".to_string(), serde_json::json!("module"));
        obj.insert(
            "packageManager".to_string(),
            serde_json::json!(manifest.workspace.package_manager),
        );

        if !manifest.packages.workspaces.is_empty() {
            obj.insert(
                "workspaces".to_string(),
                serde_json::to_value(&manifest.packages.workspaces)?,
            );
        }

        // Update generation marker
        obj.insert("_generated".to_string(), serde_json::json!({
            "by": "airis gen",
            "managed_fields": managed_fields,
            "warning": "Only the fields listed in managed_fields are updated by airis gen. Everything else is yours."
        }));

        // Serialize to pretty JSON
        let content = serde_json::to_string_pretty(&package_json)
            .context("Failed to serialize package.json")?;
        Ok(format!("{content}\n"))
    }

    pub fn render_pnpm_workspace(&self, manifest: &Manifest) -> Result<String> {
        let data = self.prepare_pnpm_workspace_data(manifest)?;
        let packages = data["packages"]
            .as_array()
            .context("Expected packages to be an array")?;

        let mut out = String::from(
            "# Auto-generated by airis init\n\
             # DO NOT EDIT - change manifest.toml instead.\n\
             #\n\
             # NOTE: No catalog section needed!\n\
             # airis resolves versions from manifest.toml [packages.catalog] and writes\n\
             # them directly to package.json. This is a superior approach because:\n\
             # - Works with any package manager (pnpm/npm/yarn/bun)\n\
             # - Supports \"latest\", \"lts\", \"follow\" policies via airis\n\
             # - No dependency on pnpm's catalog feature\n\
             #\n\
             # Use manifest.toml [packages.catalog] for version management:\n\
             #   [packages.catalog]\n\
             #   next = \"latest\"      # airis resolves to ^16.0.3\n\
             #   react = \"lts\"        # airis resolves to ^18.3.1\n\
             #\n\
             # Then reference in dependencies:\n\
             #   [packages.root.devDependencies]\n\
             #   next = \"catalog:\"    # → ^16.0.3 in package.json\n\
             \n\
             packages:\n",
        );
        for pkg in packages {
            let pkg_str = pkg.as_str().context("Expected package to be a string")?;
            out.push_str(&format!("  - \"{pkg_str}\"\n"));
        }
        Ok(out)
    }
}
