use super::{TemplateEngine, toml_value_to_json};
use crate::manifest::Manifest;
use anyhow::{Context, Result};
use serde_json::json;

impl TemplateEngine {
    /// Render tsconfig.base.json — shared compilerOptions only (no baseUrl/paths).
    ///
    /// All values are manifest-driven with smart defaults:
    /// - target: auto-detected from Node version, or `[typescript].target`
    /// - lib: defaults to [target], or `[typescript].lib`
    /// - types: defaults to ["node"] (TS6 requires explicit), or `[typescript].types`
    /// - module/moduleResolution: or `[typescript].module` / `[typescript].module_resolution`
    pub fn render_tsconfig_base(&self, manifest: &Manifest) -> Result<String> {
        let mut compiler_options = serde_json::Map::new();
        let ts = &manifest.typescript;

        // Derive ES target: manifest override → auto-detect from Node version → fallback
        let auto_target =
            crate::conventions::parse_node_version_from_image(&manifest.workspace.image)
                .map(crate::conventions::node_version_to_es_target)
                .unwrap_or("ES2023");
        let target = ts.target.as_deref().unwrap_or(auto_target);
        let module = ts.module.as_deref().unwrap_or("ESNext");
        let module_resolution = ts.module_resolution.as_deref().unwrap_or("bundler");
        let lib: Vec<&str> = ts
            .lib
            .as_ref()
            .map(|v| v.iter().map(|s| s.as_str()).collect())
            .unwrap_or_else(|| vec![target]);
        let types: Vec<&str> = ts
            .types
            .as_ref()
            .map(|v| v.iter().map(|s| s.as_str()).collect())
            .unwrap_or_else(|| vec!["node"]);

        // Build compilerOptions from resolved values
        compiler_options.insert("target".into(), json!(target));
        compiler_options.insert("module".into(), json!(module));
        compiler_options.insert("moduleResolution".into(), json!(module_resolution));
        compiler_options.insert("lib".into(), json!(lib));
        compiler_options.insert("types".into(), json!(types));
        compiler_options.insert("strict".into(), json!(true));
        compiler_options.insert("esModuleInterop".into(), json!(true));
        compiler_options.insert("skipLibCheck".into(), json!(true));
        compiler_options.insert("forceConsistentCasingInFileNames".into(), json!(true));
        compiler_options.insert("resolveJsonModule".into(), json!(true));
        compiler_options.insert("isolatedModules".into(), json!(true));

        // TS6: ignoreDeprecations for baseUrl and other deprecated options
        // Added unconditionally to base so all packages inherit it
        compiler_options.insert("ignoreDeprecations".into(), json!("6.0"));

        // Merge extra compilerOptions from [typescript.compiler_options]
        for (key, value) in &ts.compiler_options {
            compiler_options.insert(key.clone(), toml_value_to_json(value));
        }

        let tsconfig = json!({
            "_generated": "DO NOT EDIT — regenerated by airis gen from manifest.toml [typescript]",
            "compilerOptions": serde_json::Value::Object(compiler_options),
        });

        let content = serde_json::to_string_pretty(&tsconfig)
            .context("Failed to serialize tsconfig.base.json")?;
        Ok(format!("{content}\n"))
    }

    /// Render per-package tsconfig.json based on framework and manifest overrides.
    ///
    /// Framework-specific defaults:
    /// - nextjs: lib += ["DOM"], jsx = "preserve"
    /// - react-vite: lib += ["DOM"], jsx = "react-jsx"
    /// - node: inherits base as-is
    pub fn render_package_tsconfig(
        &self,
        package: &crate::manifest::ProjectDefinition,
        manifest: &crate::manifest::Manifest,
        rel_path_to_root: &str,
        ts_major: u32,
    ) -> Result<String> {
        let ts = &manifest.typescript;
        let pkg_ts = package.tsconfig.as_ref();

        // Resolve target for lib defaults
        let auto_target =
            crate::conventions::parse_node_version_from_image(&manifest.workspace.image)
                .map(crate::conventions::node_version_to_es_target)
                .unwrap_or("ES2023");
        let target = ts.target.as_deref().unwrap_or(auto_target);

        let framework = package.framework.as_deref().unwrap_or("node");
        let is_browser = matches!(framework, "nextjs" | "react-vite");

        let mut compiler_options = serde_json::Map::new();

        // lib: package override → framework default → base inherits
        let lib = pkg_ts.and_then(|t| t.lib.as_ref());
        if let Some(lib_entries) = lib {
            compiler_options.insert("lib".into(), json!(lib_entries));
        } else if is_browser {
            compiler_options.insert("lib".into(), json!([target, "DOM"]));
        }

        // jsx: package override → framework default
        let jsx = pkg_ts.and_then(|t| t.jsx.as_deref());
        if let Some(jsx_val) = jsx {
            compiler_options.insert("jsx".into(), json!(jsx_val));
        } else {
            match framework {
                "nextjs" => {
                    compiler_options.insert("jsx".into(), json!("preserve"));
                }
                "react-vite" => {
                    compiler_options.insert("jsx".into(), json!("react-jsx"));
                }
                _ => {}
            }
        }

        // types: package override (if explicitly set)
        if let Some(types_entries) = pkg_ts.and_then(|t| t.types.as_ref()) {
            compiler_options.insert("types".into(), json!(types_entries));
        }

        // Next.js specific
        if framework == "nextjs" {
            compiler_options.insert("plugins".into(), json!([{"name": "next"}]));
            // @/ path alias for tsc (Next.js dev server resolves this automatically, but tsc --noEmit needs it)
            compiler_options.insert("paths".into(), json!({"@/*": ["./src/*"]}));
        }

        // outDir for buildable libs
        if package.kind.as_deref() == Some("lib") {
            compiler_options.insert("outDir".into(), json!("./dist"));
            compiler_options.insert("declaration".into(), json!(true));
        }

        // TS6 ignoreDeprecations
        if ts_major >= 6 {
            compiler_options.insert("ignoreDeprecations".into(), json!("6.0"));
        }

        // Merge extra compilerOptions from [app.tsconfig.compiler_options]
        if let Some(pkg_ts) = pkg_ts {
            for (key, value) in &pkg_ts.compiler_options {
                compiler_options.insert(key.clone(), toml_value_to_json(value));
            }
        }

        // Build includes
        let include = match framework {
            "nextjs" => json!([
                "next-env.d.ts",
                "src/**/*.ts",
                "src/**/*.tsx",
                ".next/types/**/*.ts"
            ]),
            "react-vite" => json!(["src/**/*.ts", "src/**/*.tsx", "vite-env.d.ts"]),
            _ => json!(["src/**/*.ts", "src/**/*.tsx"]),
        };

        let exclude = json!(["node_modules", "dist", "coverage", "tests"]);

        let mut tsconfig = serde_json::Map::new();
        tsconfig.insert(
            "_generated".into(),
            json!("DO NOT EDIT — regenerated by airis gen from manifest.toml"),
        );
        tsconfig.insert(
            "extends".into(),
            json!(format!("{rel_path_to_root}tsconfig.base.json")),
        );
        if !compiler_options.is_empty() {
            tsconfig.insert(
                "compilerOptions".into(),
                serde_json::Value::Object(compiler_options),
            );
        }
        tsconfig.insert("include".into(), include);
        tsconfig.insert("exclude".into(), exclude);

        let content = serde_json::to_string_pretty(&serde_json::Value::Object(tsconfig))
            .context("Failed to serialize package tsconfig.json")?;
        Ok(format!("{content}\n"))
    }

    /// Render CSS module type declaration for Next.js apps (TS6 TS2882 fix).
    pub fn render_css_declaration(&self) -> String {
        "// DO NOT EDIT (generated by airis gen)\ndeclare module '*.css' {}\n".to_string()
    }

    /// Render root tsconfig.json — IDE config with baseUrl + paths + ignoreDeprecations.
    ///
    /// `workspace_paths` is a list of (package_name, relative_path) pairs auto-discovered
    /// from workspace patterns. `ts_major` controls whether `ignoreDeprecations` is added.
    pub fn render_tsconfig_root(
        &self,
        manifest: &Manifest,
        workspace_paths: &[(String, String)],
        ts_major: u32,
    ) -> Result<String> {
        let mut paths = serde_json::Map::new();

        // Auto-generated paths from workspace discovery
        for (pkg_name, rel_path) in workspace_paths {
            paths.insert(pkg_name.clone(), json!([format!("{}/src", rel_path)]));
        }

        // Merge user-specified paths from [typescript.paths]
        for (alias, target) in &manifest.typescript.paths {
            paths.insert(alias.clone(), json!([target]));
        }

        let mut compiler_options = serde_json::Map::new();
        compiler_options.insert("noEmit".to_string(), json!(true));
        compiler_options.insert("baseUrl".to_string(), json!("."));

        if !paths.is_empty() {
            compiler_options.insert("paths".to_string(), serde_json::Value::Object(paths));
        }

        if ts_major >= 6 {
            compiler_options.insert("ignoreDeprecations".to_string(), json!("6.0"));
        }

        // Build include patterns from workspace patterns
        let workspace_patterns = if !manifest.packages.workspaces.is_empty() {
            &manifest.packages.workspaces
        } else {
            &manifest.workspace.workspaces
        };

        let mut include: Vec<String> = Vec::new();
        for pattern in workspace_patterns {
            if pattern.starts_with('!') {
                continue;
            }
            // Convert glob pattern to ts include pattern
            // "apps/*" → "apps/**/*.ts", "apps/**/*.tsx"
            // "products/**" → "products/**/*.ts", "products/**/*.tsx"
            let base = pattern.trim_end_matches('*').trim_end_matches('/');
            include.push(format!("{}/**/*.ts", base));
            include.push(format!("{}/**/*.tsx", base));
        }
        if include.is_empty() {
            include.push("**/*.ts".to_string());
            include.push("**/*.tsx".to_string());
        }

        let tsconfig = json!({
            "_generated": "DO NOT EDIT — regenerated by airis gen from manifest.toml [typescript]",
            "extends": "./tsconfig.base.json",
            "compilerOptions": serde_json::Value::Object(compiler_options),
            "include": include,
            "exclude": [
                "node_modules",
                "**/node_modules",
                "dist",
                "**/dist",
                ".next",
                "**/.next",
                "coverage",
            ],
        });

        let content =
            serde_json::to_string_pretty(&tsconfig).context("Failed to serialize tsconfig.json")?;
        Ok(format!("{content}\n"))
    }
}
