//! Dockerfile generation for various runtime families

use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use crate::channel::{RuntimeFamily, Toolchain};

/// Generate Dockerfile based on runtime family
pub fn generate_dockerfile_for_toolchain(
    target: &str,
    toolchain: &Toolchain,
    build_args: &BTreeMap<String, String>,
) -> String {
    match toolchain.family {
        RuntimeFamily::Node => {
            // Detect if this is a Next.js project from package.json
            let is_nextjs = detect_nextjs(target);
            if is_nextjs {
                generate_nextjs_dockerfile(target, &toolchain.version, build_args)
            } else {
                generate_node_dockerfile(target, &toolchain.version, build_args)
            }
        }
        RuntimeFamily::Bun => generate_bun_dockerfile(target, &toolchain.image, build_args),
        RuntimeFamily::Deno => generate_deno_dockerfile(target, &toolchain.image, build_args),
        RuntimeFamily::Edge => generate_edge_dockerfile(target, &toolchain.image, build_args),
        RuntimeFamily::Rust => generate_rust_dockerfile(target, build_args),
        RuntimeFamily::Python => generate_python_dockerfile(target, build_args),
    }
}

// Dockerfile templates — inline string literals (no external template files)
const NEXTJS_DOCKERFILE: &str = r#"# syntax=docker/dockerfile:1.7
# Auto-generated by airis build --docker
# Target: {{target}}

# ---- base ----
FROM node:{{node_version}}-alpine AS base
RUN apk add --no-cache libc6-compat \
 && {{{pm_install_cmd}}}

# ---- deps ----
FROM base AS deps
WORKDIR /app
COPY pnpm-lock.yaml package.json pnpm-workspace.yaml .npmrc* ./
COPY apps/ apps/
COPY libs/ libs/
RUN pnpm install --frozen-lockfile

# ---- build ----
FROM base AS build
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY --from=deps /app/apps ./apps
COPY --from=deps /app/libs ./libs
COPY . .
{{extra_args}}ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
ENV NEXT_TELEMETRY_DISABLED=1
RUN pnpm -r build \
 && mkdir -p {{target}}/public

# ---- prod ----
FROM node:{{node_version}}-alpine AS prod
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs \
 && adduser --system --uid 1001 nextjs

COPY --from=build /app/{{target}}/public ./public
COPY --from=build --chown=nextjs:nodejs /app/{{target}}/.next/standalone ./
COPY --from=build --chown=nextjs:nodejs /app/{{target}}/.next/static ./{{target}}/.next/static

USER nextjs
EXPOSE {{port}}
ENV PORT={{port}} HOSTNAME="0.0.0.0"

CMD ["node", "{{target}}/server.js"]
"#;

const NODE_DOCKERFILE: &str = r#"# syntax=docker/dockerfile:1.7
# Auto-generated by airis build --docker
# Target: {{target}}

# ---- base ----
FROM node:{{node_version}}-alpine AS base
RUN apk add --no-cache libc6-compat \
 && {{{pm_install_cmd}}}

# ---- deps ----
FROM base AS deps
WORKDIR /app
COPY pnpm-lock.yaml package.json pnpm-workspace.yaml ./
COPY apps/ apps/
COPY libs/ libs/
RUN pnpm fetch

# ---- build ----
FROM base AS build
WORKDIR /app
COPY --from=deps /root/.local/share/pnpm/store /root/.local/share/pnpm/store
COPY . .
{{extra_args}}ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
RUN pnpm install --offline --frozen-lockfile \
 && pnpm -r --filter='./{{target}}...' build

# ---- prod ----
FROM node:{{node_version}}-alpine AS prod
WORKDIR /app
ENV NODE_ENV=production

RUN addgroup --system --gid 1001 nodejs \
 && adduser --system --uid 1001 appuser

COPY --from=build --chown=appuser:nodejs /app/{{target}}/dist ./dist
COPY --from=build --chown=appuser:nodejs /app/{{target}}/package.json ./

USER appuser
EXPOSE {{port}}
ENV PORT={{port}}

CMD ["node", "dist/index.js"]
"#;

const BUN_DOCKERFILE: &str = r#"# syntax=docker/dockerfile:1.7
# Auto-generated by airis build --docker (Bun)
# Target: {{target}}

FROM {{image}} AS deps
WORKDIR /app
COPY package.json bun.lockb ./
RUN bun install --frozen-lockfile

FROM {{image}} AS build
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
{{extra_args}}ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
RUN bun run build

FROM {{image}} AS prod
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app/dist ./dist
COPY --from=build /app/package.json ./
EXPOSE {{port}}
CMD ["bun", "run", "dist/index.js"]
"#;

const DENO_DOCKERFILE: &str = r#"# syntax=docker/dockerfile:1.7
# Auto-generated by airis build --docker (Deno)
# Target: {{target}}

FROM {{image}} AS build
WORKDIR /app
COPY . .
{{extra_args}}RUN deno cache src/main.ts
RUN deno compile --allow-net --allow-env --output=app src/main.ts

FROM gcr.io/distroless/cc AS prod
COPY --from=build /app/app /app
EXPOSE {{port}}
CMD ["/app"]
"#;

const EDGE_DOCKERFILE: &str = r#"# syntax=docker/dockerfile:1.7
# Auto-generated by airis build --docker (Edge/WASM)
# Target: {{target}}

FROM {{image}} AS build
WORKDIR /app
COPY . .
{{extra_args}}RUN deno task build

FROM {{image}} AS prod
WORKDIR /app
COPY --from=build /app/dist ./dist
EXPOSE {{port}}
CMD ["deno", "run", "--allow-net", "--allow-env", "dist/index.js"]
"#;

const RUST_DOCKERFILE: &str = r#"# syntax=docker/dockerfile:1.7
# Auto-generated by airis build --docker (Rust)
# Target: {{target}}

FROM {{rust_image}} AS deps
WORKDIR /app
COPY Cargo.toml Cargo.lock ./
RUN mkdir src && echo "fn main() {}" > src/main.rs
RUN cargo fetch

FROM {{rust_image}} AS build
WORKDIR /app
{{extra_args}}COPY . .
RUN cargo build --release

FROM gcr.io/distroless/cc AS prod
COPY --from=build /app/target/release/{{app_name}} /app
EXPOSE {{port}}
CMD ["/app"]
"#;

const PYTHON_DOCKERFILE: &str = r#"# syntax=docker/dockerfile:1.7
# Auto-generated by airis build --docker (Python)
# Target: {{target}}

FROM {{python_image}} AS deps
WORKDIR /app
COPY requirements*.txt ./
RUN pip install --no-cache-dir -r requirements.txt

FROM {{python_image}} AS prod
WORKDIR /app
{{extra_args}}COPY --from=deps /usr/local /usr/local
COPY . .
EXPOSE {{port}}
CMD ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "{{port}}"]
"#;

fn render_dockerfile_template(
    template: &str,
    vars: &std::collections::HashMap<&str, String>,
) -> String {
    let mut result = template.to_string();
    for (key, value) in vars {
        result = result.replace(&format!("{{{{{}}}}}", key), value);
    }
    result
}

/// Detect if a Node.js project uses Next.js by checking package.json
pub(crate) fn detect_nextjs(target: &str) -> bool {
    let pkg_json_path = Path::new(target).join("package.json");
    if !pkg_json_path.exists() {
        return false;
    }

    let content = match fs::read_to_string(&pkg_json_path) {
        Ok(c) => c,
        Err(_) => return false,
    };

    let json: serde_json::Value = match serde_json::from_str(&content) {
        Ok(j) => j,
        Err(_) => return false,
    };

    // Check dependencies and devDependencies for "next"
    let has_next_dep = json["dependencies"]
        .as_object()
        .is_some_and(|deps| deps.contains_key("next"));
    let has_next_dev_dep = json["devDependencies"]
        .as_object()
        .is_some_and(|deps| deps.contains_key("next"));

    has_next_dep || has_next_dev_dep
}

fn build_extra_args(build_args: &BTreeMap<String, String>) -> String {
    build_args
        .keys()
        .map(|k| format!("ARG {}\n", k))
        .collect()
}

fn generate_nextjs_dockerfile(
    target: &str,
    node_version: &str,
    build_args: &BTreeMap<String, String>,
) -> String {
    let mut vars = std::collections::HashMap::new();
    vars.insert("target", target.to_string());
    vars.insert("node_version", node_version.to_string());
    vars.insert("extra_args", build_extra_args(build_args));
    vars.insert(
        "port",
        crate::conventions::framework_defaults("nextjs")
            .port
            .to_string(),
    );
    vars.insert("pm_install_cmd", "npm install -g pnpm".to_string());
    render_dockerfile_template(NEXTJS_DOCKERFILE, &vars)
}

fn generate_node_dockerfile(
    target: &str,
    node_version: &str,
    build_args: &BTreeMap<String, String>,
) -> String {
    let mut vars = std::collections::HashMap::new();
    vars.insert("target", target.to_string());
    vars.insert("node_version", node_version.to_string());
    vars.insert("extra_args", build_extra_args(build_args));
    vars.insert(
        "port",
        crate::conventions::framework_defaults("node")
            .port
            .to_string(),
    );
    vars.insert("pm_install_cmd", "npm install -g pnpm".to_string());
    render_dockerfile_template(NODE_DOCKERFILE, &vars)
}

fn generate_bun_dockerfile(
    target: &str,
    image: &str,
    build_args: &BTreeMap<String, String>,
) -> String {
    let mut vars = std::collections::HashMap::new();
    vars.insert("target", target.to_string());
    vars.insert("image", image.to_string());
    vars.insert("extra_args", build_extra_args(build_args));
    vars.insert(
        "port",
        crate::conventions::framework_defaults("node")
            .port
            .to_string(),
    );
    render_dockerfile_template(BUN_DOCKERFILE, &vars)
}

fn generate_deno_dockerfile(
    target: &str,
    image: &str,
    build_args: &BTreeMap<String, String>,
) -> String {
    let mut vars = std::collections::HashMap::new();
    vars.insert("target", target.to_string());
    vars.insert("image", image.to_string());
    vars.insert("extra_args", build_extra_args(build_args));
    vars.insert(
        "port",
        crate::conventions::framework_defaults("node")
            .port
            .to_string(),
    );
    render_dockerfile_template(DENO_DOCKERFILE, &vars)
}

fn generate_edge_dockerfile(
    target: &str,
    image: &str,
    build_args: &BTreeMap<String, String>,
) -> String {
    let mut vars = std::collections::HashMap::new();
    vars.insert("target", target.to_string());
    vars.insert("image", image.to_string());
    vars.insert("extra_args", build_extra_args(build_args));
    vars.insert(
        "port",
        crate::conventions::framework_defaults("cloudflare-worker")
            .port
            .to_string(),
    );
    render_dockerfile_template(EDGE_DOCKERFILE, &vars)
}

fn generate_rust_dockerfile(target: &str, build_args: &BTreeMap<String, String>) -> String {
    let app_name = target.rsplit('/').next().unwrap_or(target);
    let mut vars = std::collections::HashMap::new();
    vars.insert("target", target.to_string());
    vars.insert("app_name", app_name.to_string());
    vars.insert("extra_args", build_extra_args(build_args));
    vars.insert(
        "rust_image",
        crate::channel::defaults::RUST_IMAGE.to_string(),
    );
    vars.insert(
        "port",
        crate::conventions::framework_defaults("rust")
            .port
            .to_string(),
    );
    render_dockerfile_template(RUST_DOCKERFILE, &vars)
}

fn generate_python_dockerfile(target: &str, build_args: &BTreeMap<String, String>) -> String {
    let mut vars = std::collections::HashMap::new();
    vars.insert("target", target.to_string());
    vars.insert("extra_args", build_extra_args(build_args));
    vars.insert(
        "python_image",
        crate::channel::defaults::PYTHON_IMAGE.to_string(),
    );
    vars.insert(
        "port",
        crate::conventions::framework_defaults("python")
            .port
            .to_string(),
    );
    render_dockerfile_template(PYTHON_DOCKERFILE, &vars)
}
