use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

pub const LOCK_FILE: &str = "airis.lock";

/// Resolved versions and toolchain state for the workspace.
/// Single source of truth for all resolved versions.
#[derive(Debug, Serialize, Deserialize, Default, Clone)]
pub struct Lock {
    /// Schema version (future proofing)
    pub version: u32,

    /// Resolved catalog versions: name -> version (e.g., "react" -> "^19.0.0")
    #[serde(default)]
    pub catalog: BTreeMap<String, String>,

    /// Resolved app-specific dependencies: app_name -> dep_name -> version
    #[serde(default)]
    pub apps: BTreeMap<String, BTreeMap<String, String>>,

    /// Resolved toolchain versions
    #[serde(default)]
    pub toolchain: ToolchainLock,
}

#[derive(Debug, Serialize, Deserialize, Default, Clone)]
pub struct ToolchainLock {
    /// Resolved package manager (e.g., "pnpm@10.22.0")
    pub package_manager: String,
    /// Resolved node version (e.g., "22.12.0")
    pub node: String,
}

impl Lock {
    pub fn load<P: AsRef<Path>>(path: P) -> Result<Self> {
        let content = fs::read_to_string(&path)
            .with_context(|| format!("Failed to read {:?}", path.as_ref()))?;

        let lock: Lock = toml::from_str(&content)
            .with_context(|| format!("Failed to parse {:?}", path.as_ref()))?;

        Ok(lock)
    }

    /// Get a resolved catalog version if it exists.
    pub fn get_catalog(&self, name: &str) -> Option<&String> {
        self.catalog.get(name)
    }

    /// Update a resolved catalog version.
    pub fn update_catalog(&mut self, name: String, version: String) {
        self.catalog.insert(name, version);
    }

    /// Get a resolved app dependency version if it exists.
    pub fn get_app_dep(&self, app_name: &str, dep_name: &str) -> Option<&String> {
        self.apps.get(app_name).and_then(|deps| deps.get(dep_name))
    }

    /// Update a resolved app dependency version.
    pub fn update_app_dep(&mut self, app_name: String, dep_name: String, version: String) {
        self.apps
            .entry(app_name)
            .or_default()
            .insert(dep_name, version);
    }

    pub fn save<P: AsRef<Path>>(&self, path: P) -> Result<()> {
        let content =
            toml::to_string_pretty(self).with_context(|| "Failed to serialize airis.lock")?;

        let header = "# This file is auto-generated by airis. DO NOT EDIT.\n\
                      # It contains the resolved versions for your workspace.\n\n";

        fs::write(path.as_ref(), format!("{}{}", header, content))
            .with_context(|| format!("Failed to write {:?}", path.as_ref()))?;

        Ok(())
    }
}
