use std::fs;
use std::io::{self, BufRead, Write};
use std::path::Path;

use anyhow::Result;
use colored::Colorize;

use crate::commands::generate::registry::load_generation_registry;
use crate::commands::guards::GUARDS_DIR;
use crate::commands::guards::scripts::is_airis_guard;

/// Uninstall airis from the current workspace by removing shims, hooks, and generated files.
pub fn uninstall() -> Result<()> {
    println!("{}", "🗑️  Uninstalling airis from current workspace...".bright_blue());
    println!();

    // 1. Remove markers from Git hooks
    remove_git_hooks_markers()?;

    // 2. Remove local shims and guards
    remove_local_shims()?;

    // 3. Remove generated files (Registry based)
    remove_generated_files()?;

    println!();
    println!("{}", "✅ Workspace uninstalled successfully.".green());
    println!("   Note: Your manifest.toml and .airis/backups remain untouched.");
    println!("   To remove global shims, run: airis guards uninstall --global");
    
    Ok(())
}

fn remove_git_hooks_markers() -> Result<()> {
    let hooks_dir = Path::new(".git/hooks");
    if !hooks_dir.exists() {
        return Ok(());
    }

    println!("🧹 Cleaning Git hooks...");
    let mut cleaned = 0;

    for entry in fs::read_dir(hooks_dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_file() {
            if clean_file_markers(&path, "# >>> airis start", "# <<< airis end")? {
                println!("   {} {}", "✓".green(), path.display());
                cleaned += 1;
            }
        }
    }

    if cleaned == 0 {
        println!("   No airis markers found in hooks.");
    }
    Ok(())
}

fn remove_local_shims() -> Result<()> {
    let local_bins = [Path::new("bin"), Path::new(GUARDS_DIR)];
    
    for bin_dir in &local_bins {
        if !bin_dir.exists() {
            continue;
        }

        println!("🧹 Removing local shims from {}...", bin_dir.display());
        let mut removed = 0;

        for entry in fs::read_dir(bin_dir)? {
            let entry = entry?;
            let path = entry.path();
            if path.is_file() {
                if is_airis_guard(&path).unwrap_or(false) || 
                   fs::read_to_string(&path).unwrap_or_default().contains("Auto-generated by airis") {
                    fs::remove_file(&path)?;
                    println!("   {} {}", "✓".green(), path.display());
                    removed += 1;
                }
            }
        }

        if removed == 0 {
            println!("   No airis shims found.");
        }

        // Try to remove the directory if empty
        if fs::read_dir(bin_dir)?.next().is_none() {
            fs::remove_dir(bin_dir)?;
        }
    }
    Ok(())
}

fn remove_generated_files() -> Result<()> {
    let registry_path = Path::new(".airis/generated.toml");
    if !registry_path.exists() {
        return Ok(());
    }

    let generated_paths = load_generation_registry(registry_path);
    if generated_paths.is_empty() {
        return Ok(());
    }

    println!("\n📋 The following files were generated by airis:");
    for path in &generated_paths {
        println!("   - {}", path);
    }

    print!("\nDo you want to delete these generated files? (y/N): ");
    io::stdout().flush()?;

    let mut input = String::new();
    io::stdin().read_line(&mut input)?;

    if input.trim().to_lowercase() == "y" {
        for path_str in &generated_paths {
            let path = Path::new(path_str);
            if path.exists() {
                fs::remove_file(path)?;
                println!("   {} {}", "✓".green(), path_str);
            }
        }
        fs::remove_file(registry_path)?;
        println!("   {} .airis/generated.toml", "✓".green());
    } else {
        println!("   Skipping file deletion.");
    }

    Ok(())
}

/// Clean a file by removing blocks between start and end markers
fn clean_file_markers(path: &Path, start_marker: &str, end_marker: &str) -> Result<bool> {
    let content = fs::read_to_string(path)?;
    if !content.contains(start_marker) {
        return Ok(false);
    }

    let file = fs::File::open(path)?;
    let reader = io::BufReader::new(file);
    let mut new_lines = Vec::new();
    let mut inside_block = false;
    let mut found = false;

    for line in reader.lines() {
        let line = line?;
        if line.contains(start_marker) {
            inside_block = true;
            found = true;
            continue;
        }
        if line.contains(end_marker) {
            inside_block = false;
            continue;
        }
        if !inside_block {
            new_lines.push(line);
        }
    }

    if found {
        fs::write(path, new_lines.join("\n") + "\n")?;
    }
    Ok(found)
}
