use std::fs;
#[cfg(unix)]
use std::os::unix::fs::PermissionsExt;
use std::path::PathBuf;

use anyhow::{Context, Result};
use colored::Colorize;
use serde_json::Value;

/// Directory name for airis-managed hooks inside ~/.claude/hooks/
const AIRIS_HOOKS_DIR: &str = "airis";

/// Get the ~/.claude/ directory path
fn claude_home() -> Result<PathBuf> {
    let home = dirs::home_dir().context("Could not determine home directory")?;
    Ok(home.join(".claude"))
}

/// Get the hooks directory path (~/.claude/hooks/airis/)
fn hooks_dir() -> Result<PathBuf> {
    Ok(claude_home()?.join("hooks").join(AIRIS_HOOKS_DIR))
}

/// Get the commands directory path (~/.claude/commands/)
fn commands_dir() -> Result<PathBuf> {
    Ok(claude_home()?.join("commands"))
}

/// Get the settings.json path (~/.claude/settings.json)
fn settings_path() -> Result<PathBuf> {
    Ok(claude_home()?.join("settings.json"))
}

// ── Command file content ────────────────────────────────────────────

fn playwright_cli_command() -> &'static str {
    r#"---
description: Browser automation via playwright-cli (snapshot → action → verify)
allowed-tools: Bash, Read
---

# playwright-cli

Use `playwright-cli` for browser automation. Prefer snapshot-driven refs over CSS selectors.

## Workflow
1. `playwright-cli open <url>` — open browser
2. `playwright-cli snapshot` — get element refs
3. `playwright-cli click <ref>` / `playwright-cli fill <ref> <text>` — interact
4. `playwright-cli screenshot` — verify result visually

## Core Commands
| Command | Usage |
|---------|-------|
| `open [url]` | Open browser (optionally navigate) |
| `snapshot` | Capture accessibility tree with refs |
| `click <ref>` | Click element by ref |
| `fill <ref> <text>` | Fill input field |
| `type <text>` | Type into focused element |
| `select <ref> <val>` | Select dropdown option |
| `screenshot [ref]` | Screenshot page or element |
| `hover <ref>` | Hover over element |
| `press <key>` | Press keyboard key |
| `goto <url>` | Navigate to URL |
| `eval <js> [ref]` | Run JS on page/element |
| `console` | View console messages |
| `network` | List network requests |

## Auth Persistence
- `state-save [file]` — save cookies/storage to file
- `state-load <file>` — restore auth state from file

## Tips
- Always `snapshot` before interacting — refs change after DOM updates
- Use `screenshot` to verify visual state, not just DOM
- For SPAs, wait after navigation: `playwright-cli snapshot` retries internally
"#
}

// ── Hook script content ─────────────────────────────────────────────

fn docker_first_guard_script() -> &'static str {
    r##"#!/usr/bin/env bash
# Auto-generated by airis guards --hooks
# Blocks host-level package manager usage in Claude Code

INPUT=$(cat)
COMMAND=$(python3 -c "
import json, sys
data = json.loads(sys.stdin.read())
print(data.get('tool_input', {}).get('command', ''))
" <<< "$INPUT")

# Allow commands through docker compose exec
if echo "$COMMAND" | grep -qE '^docker (compose |)exec'; then
  exit 0
fi

BLOCKED=(
  '^npm (install|i |ci|add|update|remove|uninstall)'
  '^yarn (install|add|remove)'
  '^pnpm (install|i |add|remove|update)'
  '^pip3? install'
  '^brew install'
  '^apt(-get)? install'
  '^cargo install'
)

for pattern in "${BLOCKED[@]}"; do
  if echo "$COMMAND" | grep -qE "$pattern"; then
    cat >&2 <<EOF
BLOCKED: Docker-First violation

  Command: $COMMAND

This installs packages directly on the host.
Use docker compose exec instead:

  docker compose exec <service> $COMMAND

Why: Docker-First ensures reproducible environments.
Host pollution causes "works on my machine" bugs.
EOF
    exit 2
  fi
done

exit 0
"##
}

fn docker_first_edit_guard_script() -> &'static str {
    r##"#!/usr/bin/env bash
# Auto-generated by airis guards --hooks
# Blocks Docker-First violations in Edit/Write tool calls.
# Checks BOTH the new content being written AND the existing file content.

set -euo pipefail

INPUT=$(cat)
FILE_PATH=$(python3 -c "
import json, sys
data = json.loads(sys.stdin.read())
print(data.get('tool_input', {}).get('file_path', ''))
" <<< "$INPUT")

BASENAME=$(basename "$FILE_PATH")

# Only check Docker/CI target files by name pattern
# Skip everything else (source code, docs, configs, scripts, etc.)
if [[ ! "$BASENAME" =~ ^(Dockerfile|Dockerfile\..+|compose\.ya?ml|docker-compose\.ya?ml|ci\.ya?ml|deploy\.ya?ml)$ ]]; then
  exit 0
fi

NEW_CONTENT=$(python3 -c "
import json, sys
data = json.loads(sys.stdin.read())
# Write tool uses 'content', Edit tool uses 'new_string'
print(data.get('tool_input', {}).get('content', '') or data.get('tool_input', {}).get('new_string', ''))
" <<< "$INPUT")

# Check function: scans text for violations
# Args: $1=text_to_check, $2=source_label ("new content" or "existing file")
check_violations() {
  local text="$1"
  local source="$2"

  # Host-specific absolute paths
  if echo "$text" | grep -qE '(/Users/[a-z]|~/)'; then
    cat >&2 <<BLOCK
BLOCKED: Host path in Docker/CI file ($source)

  Host-specific path (/Users/..., ~/) detected in $BASENAME.
  This WILL fail in CI.

  Fix: Use container-internal paths only.
  - pnpm store: PNPM_STORE_DIR=/pnpm/store (named volume)
  - node_modules: /app/node_modules (named volume)
  - /home/app is OK (container user), /Users/kazuki is NOT

  If this violation is in existing code, fix it before making other changes.
BLOCK
    return 1
  fi

  # Local .pnpm-store path
  if echo "$text" | grep -qE '\.pnpm-store|\.pnpm/store|node_modules/\.pnpm'; then
    cat >&2 <<BLOCK
BLOCKED: Local pnpm store path in Docker/CI file ($source)

  .pnpm-store or .pnpm/store are host-local paths.
  Use PNPM_STORE_DIR=/pnpm/store with a named volume.

  If this violation is in existing code, fix it before making other changes.
BLOCK
    return 1
  fi

  # Bind mount of node_modules (compose files only)
  if [[ "$BASENAME" =~ ^(compose\.ya?ml|docker-compose\.ya?ml)$ ]]; then
    if echo "$text" | grep -qE '\./node_modules\s*:|\./\.pnpm'; then
      cat >&2 <<BLOCK
BLOCKED: Bind mount of node_modules in compose file ($source)

  node_modules MUST use named volumes, not bind mounts.

  Correct: node_modules:/app/node_modules   (named volume)
  Wrong:   ./node_modules:/app/node_modules  (bind mount)

  If this violation is in existing code, fix it before making other changes.
BLOCK
      return 1
    fi
  fi

  # PNPM_STORE_DIR pointing to host paths
  if echo "$text" | grep -qE "PNPM_STORE_DIR\s*=\s*[\"']?\.(\/|pnpm)|PNPM_STORE_DIR\s*=\s*[\"']?(/Users|/home|~/)"; then
    cat >&2 <<BLOCK
BLOCKED: PNPM_STORE_DIR set to host-local path ($source)

  PNPM_STORE_DIR must point to a named volume mount.

  Correct: PNPM_STORE_DIR=/pnpm/store
  Wrong:   PNPM_STORE_DIR=./.pnpm-store

  If this violation is in existing code, fix it before making other changes.
BLOCK
    return 1
  fi

  return 0
}

# Check new content being written
check_violations "$NEW_CONTENT" "new content" || exit 2

# Check existing file content (catches pre-existing violations)
if [[ -f "$FILE_PATH" ]]; then
  EXISTING=$(cat "$FILE_PATH" 2>/dev/null || true)
  if [[ -n "$EXISTING" ]]; then
    check_violations "$EXISTING" "existing file" || exit 2
  fi
fi

exit 0
"##
}

fn stop_test_check_script() -> &'static str {
    r#"#!/usr/bin/env bash
# Auto-generated by airis guards --hooks
# Runs quick test check when Claude finishes responding

# Only run inside airis projects (manifest.toml present)
find_manifest() {
  local dir="$PWD"
  while [[ "$dir" != "/" ]]; do
    [[ -f "$dir/manifest.toml" ]] && echo "$dir" && return 0
    dir="$(dirname "$dir")"
  done
  return 1
}

ROOT=$(find_manifest) || exit 0
cd "$ROOT"

# Detect project type and run tests
if [[ -f Cargo.toml ]]; then
  cargo test 2>&1 | tail -5
  STATUS=$?
elif [[ -f pyproject.toml ]]; then
  if command -v pytest &>/dev/null; then
    pytest --tb=no -q 2>&1 | tail -5
    STATUS=$?
  else
    exit 0
  fi
elif [[ -f package.json ]]; then
  if command -v npm &>/dev/null; then
    npm test 2>&1 | tail -10
    STATUS=$?
  else
    exit 0
  fi
else
  exit 0
fi

if [[ $STATUS -ne 0 ]]; then
  echo "" >&2
  echo "STOP: Tests are failing. Fix them before declaring work done." >&2
  exit 2
fi

exit 0
"#
}

// ── Hook definitions for settings.json ──────────────────────────────

fn airis_pre_tool_use_entry() -> Value {
    serde_json::json!({
        "matcher": "Bash",
        "hooks": [{
            "type": "command",
            "command": "bash ~/.claude/hooks/airis/docker-first-guard.sh"
        }]
    })
}

fn airis_edit_guard_entry() -> Value {
    serde_json::json!({
        "matcher": "Edit|Write",
        "hooks": [{
            "type": "command",
            "command": "bash ~/.claude/hooks/airis/docker-first-edit-guard.sh"
        }]
    })
}

fn airis_stop_entry() -> Value {
    serde_json::json!({
        "matcher": "",
        "hooks": [{
            "type": "command",
            "command": "bash ~/.claude/hooks/airis/stop-test-check.sh",
            "timeout": 30
        }]
    })
}

// ── Public commands ─────────────────────────────────────────────────

/// Install global Claude Code hooks to ~/.claude/
pub fn setup_global() -> Result<()> {
    println!("{}", "🛡️  Setting up Claude Code Docker-First hooks...".bright_blue());
    println!();

    // 1. Create hooks directory
    let dir = hooks_dir()?;
    fs::create_dir_all(&dir)
        .with_context(|| format!("Failed to create {}", dir.display()))?;

    // 2. Write docker-first-guard.sh
    let guard_path = dir.join("docker-first-guard.sh");
    fs::write(&guard_path, docker_first_guard_script())
        .with_context(|| format!("Failed to write {}", guard_path.display()))?;
    #[cfg(unix)]
    fs::set_permissions(&guard_path, fs::Permissions::from_mode(0o755))?;
    println!("   {} {}", "✓".green(), guard_path.display().to_string().dimmed());

    // 3. Write docker-first-edit-guard.sh
    let edit_guard_path = dir.join("docker-first-edit-guard.sh");
    fs::write(&edit_guard_path, docker_first_edit_guard_script())
        .with_context(|| format!("Failed to write {}", edit_guard_path.display()))?;
    #[cfg(unix)]
    fs::set_permissions(&edit_guard_path, fs::Permissions::from_mode(0o755))?;
    println!("   {} {}", "✓".green(), edit_guard_path.display().to_string().dimmed());

    // 5. Write stop-test-check.sh
    let stop_path = dir.join("stop-test-check.sh");
    fs::write(&stop_path, stop_test_check_script())
        .with_context(|| format!("Failed to write {}", stop_path.display()))?;
    #[cfg(unix)]
    fs::set_permissions(&stop_path, fs::Permissions::from_mode(0o755))?;
    println!("   {} {}", "✓".green(), stop_path.display().to_string().dimmed());

    // 6. Write global command files (~/.claude/commands/)
    let cmd_dir = commands_dir()?;
    fs::create_dir_all(&cmd_dir)
        .with_context(|| format!("Failed to create {}", cmd_dir.display()))?;

    let pw_path = cmd_dir.join("playwright-cli.md");
    fs::write(&pw_path, playwright_cli_command())
        .with_context(|| format!("Failed to write {}", pw_path.display()))?;
    println!("   {} {}", "✓".green(), pw_path.display().to_string().dimmed());

    // 7. Merge hooks into settings.json
    let settings = settings_path()?;
    let mut value = if settings.exists() {
        let content = fs::read_to_string(&settings)
            .with_context(|| format!("Failed to read {}", settings.display()))?;
        serde_json::from_str(&content)
            .with_context(|| format!("Failed to parse {}", settings.display()))?
    } else {
        serde_json::json!({})
    };

    merge_airis_hooks(&mut value)?;

    let pretty = serde_json::to_string_pretty(&value)?;
    fs::write(&settings, pretty)
        .with_context(|| format!("Failed to write {}", settings.display()))?;
    println!("   {} {}", "✓".green(), settings.display().to_string().dimmed());

    println!();
    println!("{}", "✅ Claude Code hooks installed".green());
    println!();
    println!("  {} Docker-First Bash guard blocks host package managers", "•".dimmed());
    println!("  {} Docker-First Edit guard blocks host paths in Docker/CI files", "•".dimmed());
    println!("  {} Stop hook runs tests when Claude finishes", "•".dimmed());
    println!("  {} /playwright-cli command for browser automation", "•".dimmed());

    Ok(())
}

/// Show current setup status
pub fn status() -> Result<()> {
    println!("{}", "Claude Code Hook Status".bright_blue().bold());
    println!();

    let dir = hooks_dir()?;

    // Check hook scripts
    let guard_ok = dir.join("docker-first-guard.sh").exists();
    let edit_guard_ok = dir.join("docker-first-edit-guard.sh").exists();
    let stop_ok = dir.join("stop-test-check.sh").exists();

    println!("  Hook scripts:");
    print_status("  docker-first-guard.sh", guard_ok);
    print_status("  docker-first-edit-guard.sh", edit_guard_ok);
    print_status("  stop-test-check.sh", stop_ok);

    // Check settings.json
    let settings = settings_path()?;
    let (pre_tool_ok, stop_hook_ok) = if settings.exists() {
        let content = fs::read_to_string(&settings)?;
        let value: Value = serde_json::from_str(&content).unwrap_or(serde_json::json!({}));
        (
            has_airis_hook(&value, "PreToolUse"),
            has_airis_hook(&value, "Stop"),
        )
    } else {
        (false, false)
    };

    // Check command files
    let cmd_dir = commands_dir()?;
    let pw_ok = cmd_dir.join("playwright-cli.md").exists();

    println!();
    println!("  Command files:");
    print_status("  playwright-cli.md", pw_ok);

    println!();
    println!("  settings.json entries:");
    print_status("  PreToolUse (Docker-First guard)", pre_tool_ok);
    print_status("  Stop (test check)", stop_hook_ok);

    let all_ok = guard_ok && edit_guard_ok && stop_ok && pre_tool_ok && stop_hook_ok && pw_ok;
    println!();
    if all_ok {
        println!("{}", "✅ All hooks installed and configured".green());
    } else {
        println!("{}", "⚠️  Some hooks are missing. Run `airis guards install --hooks` to install.".yellow());
    }

    Ok(())
}

/// Remove airis-managed hooks
pub fn uninstall() -> Result<()> {
    println!("{}", "🗑️  Removing airis Claude Code hooks...".bright_blue());
    println!();

    // 1. Remove hooks directory
    let dir = hooks_dir()?;
    if dir.exists() {
        fs::remove_dir_all(&dir)
            .with_context(|| format!("Failed to remove {}", dir.display()))?;
        println!("   {} Removed {}", "✓".green(), dir.display().to_string().dimmed());
    } else {
        println!("   {} {} (not found)", "–".dimmed(), dir.display().to_string().dimmed());
    }

    // 2. Remove airis entries from settings.json
    let settings = settings_path()?;
    if settings.exists() {
        let content = fs::read_to_string(&settings)?;
        let mut value: Value = serde_json::from_str(&content)
            .with_context(|| format!("Failed to parse {}", settings.display()))?;

        remove_airis_hooks(&mut value);

        let pretty = serde_json::to_string_pretty(&value)?;
        fs::write(&settings, pretty)?;
        println!("   {} Cleaned {}", "✓".green(), settings.display().to_string().dimmed());
    }

    println!();
    println!("{}", "✅ airis hooks removed".green());

    Ok(())
}

// ── Internal helpers ────────────────────────────────────────────────

fn print_status(label: &str, ok: bool) {
    if ok {
        println!("  {} {}", "✓".green(), label);
    } else {
        println!("  {} {}", "✗".red(), label);
    }
}

/// Check if settings.json has an airis hook in the given event
fn has_airis_hook(settings: &Value, event: &str) -> bool {
    settings
        .get("hooks")
        .and_then(|h| h.get(event))
        .and_then(|arr| arr.as_array())
        .map(|entries| entries.iter().any(|e| is_airis_entry(e)))
        .unwrap_or(false)
}

/// Check if a hook entry is airis-managed (command contains "airis/")
fn is_airis_entry(entry: &Value) -> bool {
    // Check in hooks array within entry
    if let Some(hooks) = entry.get("hooks").and_then(|h| h.as_array()) {
        return hooks.iter().any(|hook| {
            hook.get("command")
                .and_then(|c| c.as_str())
                .map(|cmd| cmd.contains("airis/"))
                .unwrap_or(false)
        });
    }
    false
}

/// Merge airis hooks into settings.json value, preserving existing user hooks
fn merge_airis_hooks(settings: &mut Value) -> Result<()> {
    // Ensure hooks object exists
    if settings.get("hooks").is_none() {
        settings["hooks"] = serde_json::json!({});
    }

    // Process PreToolUse — Bash guard + Edit/Write guard
    merge_event_hooks_multi(
        settings,
        "PreToolUse",
        vec![airis_pre_tool_use_entry(), airis_edit_guard_entry()],
        true,
    )?;

    // Process Stop
    merge_event_hooks(settings, "Stop", airis_stop_entry(), false)?;

    Ok(())
}

/// Merge multiple airis hook entries into an event array
/// If `prepend` is true, adds airis entries at the beginning; otherwise at the end
fn merge_event_hooks_multi(
    settings: &mut Value,
    event: &str,
    airis_entries: Vec<Value>,
    prepend: bool,
) -> Result<()> {
    let hooks = settings["hooks"]
        .as_object_mut()
        .context("hooks is not an object")?;

    let entries = hooks
        .entry(event)
        .or_insert_with(|| serde_json::json!([]))
        .as_array_mut()
        .context(format!("hooks.{} is not an array", event))?;

    // Remove existing airis entries
    entries.retain(|e| !is_airis_entry(e));

    // Add airis entries
    if prepend {
        for (i, entry) in airis_entries.into_iter().enumerate() {
            entries.insert(i, entry);
        }
    } else {
        for entry in airis_entries {
            entries.push(entry);
        }
    }

    Ok(())
}

/// Merge a single airis hook entry into an event array
/// If `prepend` is true, adds airis entry at the beginning; otherwise at the end
fn merge_event_hooks(
    settings: &mut Value,
    event: &str,
    airis_entry: Value,
    prepend: bool,
) -> Result<()> {
    let hooks = settings["hooks"]
        .as_object_mut()
        .context("hooks is not an object")?;

    let entries = hooks
        .entry(event)
        .or_insert_with(|| serde_json::json!([]))
        .as_array_mut()
        .context(format!("hooks.{} is not an array", event))?;

    // Remove existing airis entries
    entries.retain(|e| !is_airis_entry(e));

    // Add airis entry
    if prepend {
        entries.insert(0, airis_entry);
    } else {
        entries.push(airis_entry);
    }

    Ok(())
}

/// Remove all airis-managed hooks from settings.json
fn remove_airis_hooks(settings: &mut Value) {
    if let Some(hooks) = settings.get_mut("hooks").and_then(|h| h.as_object_mut()) {
        for (_event, entries) in hooks.iter_mut() {
            if let Some(arr) = entries.as_array_mut() {
                arr.retain(|e| !is_airis_entry(e));
            }
        }
    }
}

// ── Tests ───────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn test_merge_hooks_empty() {
        let mut settings = json!({});
        merge_airis_hooks(&mut settings).unwrap();

        let pre = settings["hooks"]["PreToolUse"].as_array().unwrap();
        assert_eq!(pre.len(), 2); // Bash guard + Edit guard
        assert!(is_airis_entry(&pre[0]));
        assert!(is_airis_entry(&pre[1]));

        let stop = settings["hooks"]["Stop"].as_array().unwrap();
        assert_eq!(stop.len(), 1);
        assert!(is_airis_entry(&stop[0]));
    }

    #[test]
    fn test_merge_hooks_preserves_existing() {
        let user_hook = json!({
            "matcher": "Bash",
            "hooks": [{"type": "command", "command": "my-custom-hook.sh"}]
        });
        let mut settings = json!({
            "hooks": {
                "PreToolUse": [user_hook.clone()],
                "Stop": [user_hook.clone()]
            }
        });

        merge_airis_hooks(&mut settings).unwrap();

        // PreToolUse: airis entries first (Bash guard + Edit guard), then user
        let pre = settings["hooks"]["PreToolUse"].as_array().unwrap();
        assert_eq!(pre.len(), 3);
        assert!(is_airis_entry(&pre[0])); // Bash guard prepended
        assert!(is_airis_entry(&pre[1])); // Edit guard prepended
        assert!(!is_airis_entry(&pre[2])); // user preserved

        // Stop: user first, then airis
        let stop = settings["hooks"]["Stop"].as_array().unwrap();
        assert_eq!(stop.len(), 2);
        assert!(!is_airis_entry(&stop[0])); // user preserved
        assert!(is_airis_entry(&stop[1])); // airis appended
    }

    #[test]
    fn test_merge_hooks_replaces_airis() {
        let mut settings = json!({});
        merge_airis_hooks(&mut settings).unwrap();
        // Run again — should not duplicate
        merge_airis_hooks(&mut settings).unwrap();

        let pre = settings["hooks"]["PreToolUse"].as_array().unwrap();
        assert_eq!(pre.len(), 2); // Still just Bash guard + Edit guard

        let stop = settings["hooks"]["Stop"].as_array().unwrap();
        assert_eq!(stop.len(), 1);
    }

    #[test]
    fn test_generate_guard_script() {
        let script = docker_first_guard_script();
        assert!(script.contains("BLOCKED=("));
        assert!(script.contains("npm (install|i |ci|add|update|remove|uninstall)"));
        assert!(script.contains("pip3? install"));
        assert!(script.contains("brew install"));
        assert!(script.contains("exit 2"));
    }

    #[test]
    fn test_generate_edit_guard_script() {
        let script = docker_first_edit_guard_script();
        assert!(script.contains("/Users/"));
        assert!(script.contains("PNPM_STORE_DIR"));
        assert!(script.contains("node_modules"));
        assert!(script.contains("exit 2"));
        // Should only check Docker/CI files (allowlist approach)
        assert!(script.contains("Dockerfile"));
        // Should check existing file content too
        assert!(script.contains("existing file"));
    }

    #[test]
    fn test_uninstall_removes_airis_only() {
        let user_hook = json!({
            "matcher": "Bash",
            "hooks": [{"type": "command", "command": "my-custom-hook.sh"}]
        });
        let mut settings = json!({});
        merge_airis_hooks(&mut settings).unwrap();

        // Add a user hook
        settings["hooks"]["PreToolUse"]
            .as_array_mut()
            .unwrap()
            .push(user_hook.clone());

        // Uninstall
        remove_airis_hooks(&mut settings);

        let pre = settings["hooks"]["PreToolUse"].as_array().unwrap();
        assert_eq!(pre.len(), 1);
        assert!(!is_airis_entry(&pre[0])); // only user hook remains
    }
}
