use anyhow::{Context, Result, bail};
use colored::Colorize;
use std::fs;
use std::path::Path;

use crate::manifest::{DocsMode, MANIFEST_FILE, Manifest};

const CLAUDE_WRAPPER_TEMPLATE: &str = r#"# CLAUDE.md

This file is managed by airis-monorepo (manifest.toml).

## Configuration

All project-specific instructions, constraints, and development guidelines are defined in `manifest.toml`.

### Quick Reference

- **Commands**: See `[commands]` section for available tasks
- **Guards**: See `[guards]` section for blocked commands
- **Versioning**: See `[versioning]` section for version management
- **Apps**: See `[apps]` section for project configuration

### Accessing the Manifest

```bash
# View manifest
cat manifest.toml

# Query specific sections
airis manifest dev-apps
airis manifest rule verify
```

### Why This Approach?

By centralizing configuration in `manifest.toml`:
- ✅ Single source of truth
- ✅ No drift between docs and actual config
- ✅ Machine-readable by LLMs and tools
- ✅ Version-controlled alongside code

---

**This file was generated by `airis docs wrap CLAUDE.md`**
"#;

const CURSORRULES_WRAPPER_TEMPLATE: &str = r#"# .cursorrules

This file is managed by airis-monorepo (manifest.toml).

All project-specific rules and constraints are defined in `manifest.toml`.

## Configuration Sections

- `[commands]`: Available tasks and workflows
- `[guards]`: Blocked commands (deny/forbid/danger)
- `[remap]`: Command translations for safety
- `[versioning]`: Version management strategy
- `[apps]`: Project structure and configuration

## Accessing Configuration

```bash
# View full manifest
cat manifest.toml

# Query sections
airis manifest dev-apps
```

---

**Generated by `airis docs wrap .cursorrules`**
"#;

/// Wrap a documentation file to point to manifest.toml
pub fn wrap(target: &str) -> Result<()> {
    let manifest_path = Path::new(MANIFEST_FILE);

    if !manifest_path.exists() {
        bail!(
            "❌ {} not found. Run {} first.",
            MANIFEST_FILE.bold(),
            "airis init".bold()
        );
    }

    let mut manifest = Manifest::load(manifest_path)?;
    let target_path = Path::new(target);

    // Check if target already managed
    if manifest.docs.targets.contains(&target.to_string()) {
        println!(
            "ℹ️  {} is already managed in manifest.toml [docs.targets]",
            target.cyan()
        );
        return Ok(());
    }

    // Handle existing file
    if target_path.exists() {
        match manifest.docs.mode {
            DocsMode::Warn => {
                println!(
                    "⚠️  {} already exists. Cannot overwrite in 'warn' mode.",
                    target.yellow()
                );
                println!(
                    "   Change [docs.mode] to 'backup' in manifest.toml to enable overwrites."
                );
                return Ok(());
            }
            DocsMode::Backup => {
                // Create backup
                let backup_path = format!("{}.bak", target);
                fs::copy(target_path, &backup_path)
                    .with_context(|| format!("Failed to create backup: {}", backup_path))?;
                println!("📦 Backed up {} → {}", target.cyan(), backup_path.yellow());
            }
        }
    }

    // Generate wrapper content
    let wrapper_content = match target {
        "CLAUDE.md" => CLAUDE_WRAPPER_TEMPLATE,
        ".cursorrules" => CURSORRULES_WRAPPER_TEMPLATE,
        "GEMINI.md" => CLAUDE_WRAPPER_TEMPLATE, // Same template
        "AGENTS.md" => CLAUDE_WRAPPER_TEMPLATE, // Same template
        _ => {
            bail!(
                "❌ Unknown documentation file: {}. Supported: CLAUDE.md, .cursorrules, GEMINI.md, AGENTS.md",
                target.red()
            );
        }
    };

    // Write wrapper
    fs::write(target_path, wrapper_content)
        .with_context(|| format!("Failed to write {}", target))?;

    // Add to manifest.toml [docs.targets]
    manifest.docs.targets.push(target.to_string());
    manifest.save(manifest_path)?;

    println!("✅ {} wrapped and added to [docs.targets]", target.green());
    println!("   Original content replaced with manifest.toml reference.");

    Ok(())
}

/// List managed documentation files
pub fn list() -> Result<()> {
    let manifest_path = Path::new(MANIFEST_FILE);

    if !manifest_path.exists() {
        bail!(
            "❌ {} not found. Run {} first.",
            MANIFEST_FILE.bold(),
            "airis init".bold()
        );
    }

    let manifest = Manifest::load(manifest_path)?;

    if manifest.docs.targets.is_empty() {
        println!("ℹ️  No documentation files managed.");
        println!("   Use {} to add files.", "airis docs wrap <file>".cyan());
        return Ok(());
    }

    println!("📄 Managed documentation files:");
    println!("   Mode: {}", format!("{:?}", manifest.docs.mode).yellow());
    println!();
    for target in &manifest.docs.targets {
        let exists = Path::new(target).exists();
        let status = if exists { "✅" } else { "❌" };
        println!("   {} {}", status, target.cyan());
    }

    Ok(())
}
