use anyhow::{Context, Result};
use colored::Colorize;
use indexmap::IndexMap;
use std::env;
use std::fs;
use std::path::Path;

use crate::version_resolver::resolve_version;
use crate::commands::discover::discover_from_workspaces;
use crate::generators::package_json::generate_project_package_json;
use crate::manifest::{CatalogEntry, InjectValue, Manifest, ProjectDefinition, MANIFEST_FILE};
use crate::ownership::{get_ownership, Ownership};
use crate::templates::TemplateEngine;

/// CLI entry point for `airis gen`
/// Regenerates workspace files from existing manifest.toml
pub fn run(dry_run: bool) -> Result<()> {
    let manifest_path = Path::new(MANIFEST_FILE);

    if !manifest_path.exists() {
        println!("{}", "⛔ manifest.toml not found".bright_red());
        println!();
        println!("{}", "To create manifest.toml, use the MCP tool:".yellow());
        println!("  /airis:init");
        println!();
        println!("{}", "This analyzes your repository and generates an optimized manifest.".cyan());
        return Ok(());
    }

    println!("{}", "📖 Loading manifest.toml...".bright_blue());
    let manifest = Manifest::load(manifest_path)?;

    if dry_run {
        println!("{}", "🔍 Dry-run mode: showing what would be generated...".bright_blue());
        println!();
        preview_from_manifest(&manifest)?;
        println!();
        println!("{}", "ℹ️  No files were written (dry-run mode)".yellow());
        println!("{}", "To actually generate files, run:".bright_yellow());
        println!("  airis gen");
    } else {
        println!("{}", "🧩 Regenerating workspace files...".bright_blue());
        sync_from_manifest(&manifest)?;
    }

    Ok(())
}

/// Backup a file to .airis/backups/ before modification
/// Only backs up tool-owned and hybrid files
fn backup_file(path: &Path) -> Result<()> {
    if !path.exists() {
        return Ok(());
    }

    let ownership = get_ownership(path);
    if !matches!(ownership, Ownership::Tool | Ownership::Hybrid) {
        return Ok(());
    }

    // Create .airis/backups directory
    let backup_dir = Path::new(".airis/backups");
    fs::create_dir_all(backup_dir)
        .with_context(|| "Failed to create .airis/backups directory")?;

    // Create backup filename: replace / with _ for nested paths
    let path_str = path.to_string_lossy().replace('/', "_");
    let backup_path = backup_dir.join(format!("{}.latest", path_str));

    fs::copy(path, &backup_path)
        .with_context(|| format!("Failed to backup {} to {}", path.display(), backup_path.display()))?;

    Ok(())
}

/// Write a file with ownership-aware backup
fn write_with_backup(path: &Path, content: &str) -> Result<()> {
    backup_file(path)?;
    fs::write(path, content)
        .with_context(|| format!("Failed to write {}", path.display()))?;
    Ok(())
}

/// Preview what files would be generated (dry-run mode)
pub fn preview_from_manifest(manifest: &Manifest) -> Result<()> {
    use std::path::Path;

    println!("{}", "📋 Files that would be generated:".bright_yellow());
    println!();

    let has_workspace = manifest.has_workspace();

    // Check existing files vs new files
    let files_to_check = vec![
        ("package.json", has_workspace),
        ("Dockerfile", has_workspace),
        ("compose.yml", has_workspace),
        ("pnpm-workspace.yaml", has_workspace && !manifest.packages.workspaces.is_empty()),
    ];

    for (file, should_generate) in files_to_check {
        if !should_generate {
            continue;
        }

        let path = Path::new(file);
        let ownership = get_ownership(path);
        let status = if path.exists() {
            match ownership {
                Ownership::Tool => "exists → would overwrite (tool-owned)".green(),
                Ownership::Hybrid => "exists → would update (marker-protected)".green(),
                Ownership::User => "exists → would skip (user-owned)".yellow(),
            }
        } else {
            "would be created".green()
        };
        println!("   {} {}", file, status);
    }

    println!();
    println!("   {} Use `airis diff` to preview changes before generating.", "💡".cyan());

    // Show project info
    println!();
    println!("{}", "📦 Project info from manifest.toml:".bright_blue());
    println!("   Name: {}", manifest.project.id);
    if !manifest.project.description.is_empty() {
        println!("   Description: {}", manifest.project.description);
    }
    // CI workflows are project-owned (not generated by airis)
    println!("   Workspaces: {:?}", manifest.packages.workspaces);

    Ok(())
}

/// Sync generated files from manifest.toml contents
///
/// All tool-owned files are always overwritten (with backup to .airis/backups/).
/// The `force` parameter is retained for API compatibility but has no effect.
pub fn sync_from_manifest(manifest: &Manifest) -> Result<()> {
    sync_from_manifest_with_force(manifest, false)
}

/// Sync from manifest with explicit force flag
pub fn sync_from_manifest_with_force(manifest: &Manifest, force: bool) -> Result<()> {
    let has_workspace = manifest.has_workspace();
    let engine = TemplateEngine::new()?;
    let mut generated_files: Vec<String> = Vec::new();
    let mut inject_count = 0;

    // Node.js workspace files (only when [workspace] package_manager is set)
    if has_workspace {
        let resolved_catalog = resolve_catalog_versions(&manifest.packages.catalog)?;

        println!("{}", "🧩 Rendering templates...".bright_blue());
        generate_docker_compose(manifest, &engine, force)?;
        generate_package_json(manifest, &engine, &resolved_catalog, force)?;

        generated_files.extend([
            "package.json (with workspaces)".into(),
            "Dockerfile".into(),
            "compose.yml".into(),
        ]);

        if !manifest.packages.workspaces.is_empty() {
            generate_pnpm_workspace(manifest, &engine, force)?;
        }

        // Generate individual app package.json files (auto-discovery + explicit)
        {
            println!();
            println!("{}", "📦 Syncing app package.json files...".bright_blue());
            let workspace_root = env::current_dir().context("Failed to get current directory")?;

            // Collect workspace patterns from both v1 and v2 locations
            let workspace_patterns = if !manifest.packages.workspaces.is_empty() {
                &manifest.packages.workspaces
            } else {
                &manifest.workspace.workspaces
            };

            // Build set of explicitly defined app names (these take priority)
            let explicit_names: std::collections::HashSet<String> = manifest
                .app
                .iter()
                .map(|a| a.name.clone())
                .collect();

            // Auto-discover projects from workspace patterns
            let mut app_count = 0;
            if !workspace_patterns.is_empty() {
                let discovered = discover_from_workspaces(workspace_patterns, &workspace_root)?;
                let default_scope = manifest.workspace.scope.clone();

                for disc in &discovered {
                    if explicit_names.contains(&disc.name) {
                        continue; // Explicit [[app]] takes priority
                    }
                    let auto_app = ProjectDefinition {
                        name: disc.name.clone(),
                        path: Some(disc.path.clone()),
                        scope: default_scope.clone(),
                        framework: Some(disc.framework.to_string()),
                        ..Default::default()
                    };
                    generate_project_package_json(&auto_app, &workspace_root, &resolved_catalog)?;
                    app_count += 1;
                }
            }

            // Generate for explicitly defined apps
            for app in &manifest.app {
                generate_project_package_json(app, &workspace_root, &resolved_catalog)?;
                app_count += 1;
            }

            generated_files.push(format!("{} app package.json files", app_count));
        }

        // Generate production Dockerfiles for services with [app.deploy] enabled
        generate_service_dockerfiles(manifest, &engine)?;
        let deploy_count = manifest.app.iter()
            .filter(|a| a.deploy.as_ref().is_some_and(|d| d.enabled))
            .count();
        if deploy_count > 0 {
            generated_files.push(format!("{} service Dockerfiles (turbo prune)", deploy_count));
        }

        // Generate .npmrc for pnpm store isolation
        generate_npmrc(&engine)?;
        generated_files.push(".npmrc (pnpm store isolation)".into());

        // Generate .env.example if [env] section has required or optional vars
        if !manifest.env.required.is_empty() || !manifest.env.optional.is_empty() {
            generate_env_example(manifest, &engine)?;
            generated_files.push(".env.example".into());
        }

        // Generate .envrc for direnv
        generate_envrc(manifest, &engine)?;
        generated_files.push(".envrc".into());

        // Generate git hooks
        generate_git_hooks(&engine)?;
        generate_native_hooks()?;
        generated_files.extend([
            ".husky/pre-commit".into(),
            ".husky/pre-push".into(),
            "hooks/pre-commit".into(),
            "hooks/pre-push".into(),
        ]);

        // Inject values into files with airis:inject markers
        inject_count = inject_values(&manifest.inject, &resolved_catalog)?;

        // Sync pnpm-lock.yaml
        sync_lockfile(manifest)?;
    } else if !manifest.inject.is_empty() {
        // Inject values even without workspace
        let resolved_catalog = IndexMap::new();
        inject_count = inject_values(&manifest.inject, &resolved_catalog)?;
    }

    // CI/CD workflow generation (workspace-agnostic)
    if manifest.ci.enabled && !manifest.deploy_profiles().is_empty() {
        println!();
        println!("{}", "🚀 Generating CI/CD workflows...".bright_blue());
        generate_ci_workflow(manifest, &engine)?;
        generate_deploy_workflow(manifest, &engine)?;
    }

    // Summary
    println!();
    println!("{}", "✅ Generated files:".green());
    for file in &generated_files {
        println!("   - {}", file);
    }
    if inject_count > 0 {
        println!("   - {} files updated via airis:inject markers", inject_count);
    }

    let is_rust_project = !manifest.project.rust_edition.is_empty()
        || !manifest.project.binary_name.is_empty();
    if is_rust_project {
        println!();
        println!("{}", "ℹ️  Cargo.toml is not generated (it's the source of truth)".cyan());
        println!("   Use `airis bump-version` to sync versions");
    }

    if has_workspace {
        println!();
        println!("{}", "Next steps:".bright_yellow());
        println!("  1. Run `airis up` to start the workspace");
        println!("  2. Run `airis hooks install` to install Git hooks");
        println!("  3. Cache directories (.next, .swc, .turbo, node_modules) stay in Docker volumes");
    }

    Ok(())
}

fn generate_package_json(
    manifest: &Manifest,
    engine: &TemplateEngine,
    resolved_catalog: &IndexMap<String, String>,
    _force: bool,
) -> Result<()> {
    let path = Path::new("package.json");
    let content = engine.render_package_json(manifest, resolved_catalog)?;
    write_with_backup(path, &content)?;
    println!("   {} package.json (synced from manifest.toml)", "✓".green());
    Ok(())
}

fn generate_pnpm_workspace(
    manifest: &Manifest,
    engine: &TemplateEngine,
    _force: bool,
) -> Result<()> {
    let path = Path::new("pnpm-workspace.yaml");
    let content = engine.render_pnpm_workspace(manifest)?;

    // pnpm-workspace.yaml is Tool-owned — always overwrite from manifest.toml
    write_with_backup(path, &content)?;
    if path.exists() {
        println!("   {} pnpm-workspace.yaml (synced from manifest.toml)", "✓".green());
    }
    Ok(())
}

/// Resolve catalog version policies to actual version numbers
fn resolve_catalog_versions(
    catalog: &IndexMap<String, CatalogEntry>,
) -> Result<IndexMap<String, String>> {
    if catalog.is_empty() {
        return Ok(IndexMap::new());
    }

    println!("{}", "📦 Resolving catalog versions from npm registry...".bright_blue());

    let mut resolved: IndexMap<String, String> = IndexMap::new();

    for (package, entry) in catalog {
        let version = match entry {
            CatalogEntry::Policy(policy) => {
                let policy_str = policy.as_str();
                let version = resolve_version(package, policy_str)?;
                println!("  ✓ {} {} → {}", package, policy_str, version);
                version
            }
            CatalogEntry::Version(version) => {
                println!("  ✓ {} {}", package, version);
                version.clone()
            }
            CatalogEntry::Follow(follow_config) => {
                // For follow entries, we'll resolve them in a second pass
                let target = &follow_config.follow;
                if let Some(target_version) = resolved.get(target) {
                    println!("  ✓ {} (follow {}) → {}", package, target, target_version);
                    target_version.clone()
                } else {
                    anyhow::bail!(
                        "Cannot resolve '{}': follow target '{}' not found or not yet resolved",
                        package,
                        target
                    );
                }
            }
        };

        resolved.insert(package.clone(), version);
    }

    Ok(resolved)
}

fn generate_docker_compose(manifest: &Manifest, engine: &TemplateEngine, _force: bool) -> Result<()> {
    let dockerfile_content = engine.render_dockerfile(manifest)?;
    let compose_content = engine.render_docker_compose(manifest)?;

    let dockerfile_path = Path::new("Dockerfile");
    let compose_path = Path::new("compose.yml");

    write_with_backup(dockerfile_path, &dockerfile_content)?;
    println!("   {} Dockerfile (synced from manifest.toml)", "✓".green());

    write_with_backup(compose_path, &compose_content)?;
    println!("   {} compose.yml (synced from manifest.toml)", "✓".green());

    Ok(())
}

fn generate_env_example(manifest: &Manifest, engine: &TemplateEngine) -> Result<()> {
    let content = engine.render_env_example(manifest)?;
    let path = Path::new(".env.example");

    fs::write(path, &content)
        .with_context(|| "Failed to write .env.example")?;

    println!("   {} Generated .env.example from [env] section", "📄".green());

    Ok(())
}


fn generate_npmrc(engine: &TemplateEngine) -> Result<()> {
    let content = engine.render_npmrc()?;
    let path = Path::new(".npmrc");

    write_with_backup(path, &content)?;
    println!("   {} .npmrc (pnpm store isolation)", "✓".green());

    Ok(())
}

fn generate_envrc(manifest: &Manifest, engine: &TemplateEngine) -> Result<()> {
    let path = Path::new(".envrc");

    // Skip if .envrc already exists (hand-crafted version preferred)
    if path.exists() {
        println!(
            "   {} .envrc exists, skipping (hand-crafted version preferred)",
            "⏭️".cyan()
        );
        return Ok(());
    }

    let content = engine.render_envrc(manifest)?;
    fs::write(path, &content)
        .with_context(|| "Failed to write .envrc")?;
    println!("   {} Generated .envrc for direnv", "📁".green());

    Ok(())
}

fn generate_git_hooks(_engine: &TemplateEngine) -> Result<()> {
    let husky_dir = Path::new(".husky");
    fs::create_dir_all(husky_dir).context("Failed to create .husky directory")?;

    let pre_commit_content = include_str!("../../hooks/pre-commit");
    let pre_push_content = include_str!("../../hooks/pre-push");

    // Pre-commit hook
    let pre_commit_path = husky_dir.join("pre-commit");
    fs::write(&pre_commit_path, pre_commit_content)
        .with_context(|| "Failed to write .husky/pre-commit")?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(&pre_commit_path, fs::Permissions::from_mode(0o755))
            .with_context(|| "Failed to set .husky/pre-commit permissions")?;
    }

    // Pre-push hook
    let pre_push_path = husky_dir.join("pre-push");
    fs::write(&pre_push_path, pre_push_content)
        .with_context(|| "Failed to write .husky/pre-push")?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(&pre_push_path, fs::Permissions::from_mode(0o755))
            .with_context(|| "Failed to set .husky/pre-push permissions")?;
    }

    println!(
        "   {} Generated .husky/pre-commit and .husky/pre-push",
        "🔒".green()
    );

    Ok(())
}

/// Generate native hooks (hooks/pre-commit, hooks/pre-push) for `airis hooks install`.
/// Skips if the hooks/ directory already exists (preserves user customizations).
fn generate_native_hooks() -> Result<()> {
    let hooks_dir = Path::new("hooks");

    if hooks_dir.exists() {
        println!(
            "   {} hooks/ directory exists, skipping (user customizations preserved)",
            "⏭️".cyan()
        );
        return Ok(());
    }

    fs::create_dir_all(hooks_dir).context("Failed to create hooks/ directory")?;

    let pre_commit_content = include_str!("../../hooks/pre-commit");
    let pre_push_content = include_str!("../../hooks/pre-push");

    let pre_commit_path = hooks_dir.join("pre-commit");
    let pre_push_path = hooks_dir.join("pre-push");

    fs::write(&pre_commit_path, pre_commit_content)
        .with_context(|| "Failed to write hooks/pre-commit")?;
    fs::write(&pre_push_path, pre_push_content)
        .with_context(|| "Failed to write hooks/pre-push")?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(&pre_commit_path, fs::Permissions::from_mode(0o755))
            .with_context(|| "Failed to set hooks/pre-commit permissions")?;
        fs::set_permissions(&pre_push_path, fs::Permissions::from_mode(0o755))
            .with_context(|| "Failed to set hooks/pre-push permissions")?;
    }

    println!(
        "   {} Generated hooks/pre-commit and hooks/pre-push",
        "🔒".green()
    );
    println!(
        "   {} Run `airis hooks install` to install them to .git/hooks/",
        "💡".cyan()
    );

    Ok(())
}

// Note: generate_cargo_toml has been removed
// Cargo.toml is the source of truth for Rust projects and should not be auto-generated
// Use `airis bump-version` to sync versions between manifest.toml and Cargo.toml

fn generate_ci_workflow(manifest: &Manifest, engine: &TemplateEngine) -> Result<()> {
    let workflows_dir = Path::new(".github/workflows");
    fs::create_dir_all(workflows_dir).context("Failed to create .github/workflows directory")?;

    let ci_path = workflows_dir.join("ci.yml");

    // Skip if file exists without airis gen marker (hand-managed)
    if ci_path.exists() {
        let existing = fs::read_to_string(&ci_path).unwrap_or_default();
        if !existing.starts_with("# Auto-generated by airis gen") {
            println!(
                "   {} .github/workflows/ci.yml exists (manually managed — add '# Auto-generated by airis gen' header to enable)",
                "⚠".yellow()
            );
            return Ok(());
        }
    }

    let content = engine.render_ci_workflow(manifest)?;
    write_with_backup(&ci_path, &content)?;
    println!(
        "   {} .github/workflows/ci.yml",
        "✓".green()
    );
    Ok(())
}

fn generate_deploy_workflow(manifest: &Manifest, engine: &TemplateEngine) -> Result<()> {
    let workflows_dir = Path::new(".github/workflows");
    fs::create_dir_all(workflows_dir).context("Failed to create .github/workflows directory")?;

    let deploy_path = workflows_dir.join("deploy.yml");

    // Skip if file exists without airis gen marker (hand-managed)
    if deploy_path.exists() {
        let existing = fs::read_to_string(&deploy_path).unwrap_or_default();
        if !existing.starts_with("# Auto-generated by airis gen") {
            println!(
                "   {} .github/workflows/deploy.yml exists (manually managed — add '# Auto-generated by airis gen' header to enable)",
                "⚠".yellow()
            );
            return Ok(());
        }
    }

    let content = engine.render_deploy_workflow(manifest)?;
    write_with_backup(&deploy_path, &content)?;
    println!(
        "   {} .github/workflows/deploy.yml",
        "✓".green()
    );
    Ok(())
}

fn generate_service_dockerfiles(manifest: &Manifest, engine: &TemplateEngine) -> Result<()> {
    // Extract pnpm version from package_manager field (e.g., "pnpm@10.30.3" → "10.30.3")
    let pnpm_version = manifest.workspace.package_manager
        .split('@')
        .nth(1)
        .unwrap_or("latest");

    let deployable_apps: Vec<_> = manifest.app.iter()
        .filter(|a| a.deploy.as_ref().is_some_and(|d| d.enabled))
        .collect();

    if deployable_apps.is_empty() {
        return Ok(());
    }

    println!();
    println!("{}", "🐳 Generating service Dockerfiles (turbo prune)...".bright_blue());

    for app in &deployable_apps {
        let app_path = app.path.as_deref().unwrap_or(&app.name);
        let dockerfile_path = Path::new(app_path).join("Dockerfile");

        // Ensure directory exists
        if let Some(parent) = dockerfile_path.parent() {
            fs::create_dir_all(parent)
                .with_context(|| format!("Failed to create directory {}", parent.display()))?;
        }

        let content = engine.render_service_dockerfile(app, pnpm_version)?;
        write_with_backup(&dockerfile_path, &content)?;

        let variant = app.deploy.as_ref()
            .and_then(|d| d.variant.as_deref())
            .unwrap_or(match app.framework.as_deref() {
                Some("nextjs") => "nextjs",
                _ => "node",
            });

        println!(
            "   {} {}/Dockerfile (variant: {})",
            "✓".green(),
            app_path,
            variant,
        );
    }

    Ok(())
}

// ── Lockfile synchronization ──────────────────────────────────

/// Sync pnpm-lock.yaml after package.json updates.
/// Uses `--lockfile-only` to avoid installing into node_modules (fast).
/// Runs via Docker if mode is docker-first, otherwise directly.
fn sync_lockfile(manifest: &Manifest) -> Result<()> {
    use std::process::Command;

    // Only sync if pnpm-lock.yaml exists (skip for fresh projects)
    if !Path::new("pnpm-lock.yaml").exists() {
        return Ok(());
    }

    println!();
    println!("{}", "🔒 Syncing pnpm-lock.yaml...".bright_blue());

    let is_docker_first = matches!(manifest.mode, crate::manifest::Mode::DockerFirst);

    // Find a running service to exec into
    let docker_service = manifest.docker.workspace
        .as_ref()
        .map(|w| w.service.as_str())
        .filter(|s| !s.is_empty())
        .or_else(|| manifest.service.keys().next().map(|s| s.as_str()));

    let status = if is_docker_first {
        let svc = match docker_service {
            Some(s) => s,
            None => {
                println!(
                    "   {} no service found for lockfile sync (run `docker compose exec <service> pnpm install --lockfile-only`)",
                    "⚠".yellow()
                );
                return Ok(());
            }
        };
        // Docker-first: always run inside container. Host has no pnpm.
        Command::new("docker")
            .args(["compose", "exec", "-T", svc, "pnpm", "install", "--lockfile-only"])
            .status()
    } else {
        // Non-docker mode: run directly on host
        Command::new("pnpm")
            .args(["install", "--lockfile-only"])
            .status()
    };

    match status {
        Ok(s) if s.success() => {
            println!("   {} pnpm-lock.yaml synced", "✓".green());
        }
        Ok(_) => {
            println!(
                "   {} pnpm-lock.yaml sync failed (run `docker compose exec <service> pnpm install --lockfile-only`)",
                "⚠".yellow()
            );
        }
        Err(e) => {
            println!(
                "   {} pnpm-lock.yaml sync skipped: {}",
                "⚠".yellow(),
                e
            );
        }
    }

    Ok(())
}

// ── Value injection into user-owned files ─────────────────────

/// Scan workspace files for `# airis:inject <key>` markers and replace
/// the next line with the resolved value from `[inject]` in manifest.toml.
///
/// Returns the number of files modified.
fn inject_values(
    inject: &IndexMap<String, InjectValue>,
    resolved_catalog: &IndexMap<String, String>,
) -> Result<usize> {
    if inject.is_empty() {
        return Ok(0);
    }

    println!();
    println!(
        "{}",
        "💉 Injecting values from manifest [inject]...".bright_blue()
    );

    // Resolve all inject values to plain strings
    let values = resolve_inject_values(inject, resolved_catalog)?;

    let marker_re = regex::Regex::new(r"#\s*airis:inject\s+([\w.\-]+)")
        .context("Failed to compile inject marker regex")?;

    let mut modified_count = 0;

    // Walk workspace respecting .gitignore
    let walker = walkdir::WalkDir::new(".")
        .follow_links(false)
        .into_iter()
        .filter_entry(|e| {
            let name = e.file_name().to_str().unwrap_or("");
            // Skip .git directory, node_modules, dist, .next, .turbo
            !matches!(name, ".git" | "node_modules" | "dist" | ".next" | ".turbo" | ".pnpm" | ".cache" | "coverage")
        });

    for entry in walker {
        let entry = match entry {
            Ok(e) => e,
            Err(_) => continue,
        };

        if !entry.file_type().is_file() {
            continue;
        }

        let path = entry.path();

        // Skip binary files and known non-text
        let ext = path.extension().and_then(|e| e.to_str()).unwrap_or("");
        if matches!(
            ext,
            "png" | "jpg" | "jpeg" | "gif" | "ico" | "woff" | "woff2" | "ttf" | "eot" | "lock"
                | "zst" | "tar" | "gz"
        ) {
            continue;
        }

        // Quick check: skip files that don't contain our marker
        let content = match fs::read_to_string(path) {
            Ok(c) => c,
            Err(_) => continue,
        };

        if !content.contains("airis:inject") {
            continue;
        }

        let mut lines: Vec<String> = content.lines().map(String::from).collect();
        let mut file_modified = false;

        let mut i = 0;
        while i < lines.len().saturating_sub(1) {
            if let Some(caps) = marker_re.captures(&lines[i]) {
                let key = &caps[1];
                if let Some(value) = values.get(key) {
                    // Preserve indentation of the target line
                    let target = &lines[i + 1];
                    let indent_len = target.len() - target.trim_start().len();
                    let indent: String = target.chars().take(indent_len).collect();
                    let new_line = format!("{indent}{value}");

                    if lines[i + 1] != new_line {
                        lines[i + 1] = new_line;
                        file_modified = true;
                    }
                } else {
                    println!(
                        "   {} marker '{}' in {} has no matching [inject] key",
                        "⚠".yellow(),
                        key,
                        path.display()
                    );
                }
            }
            i += 1;
        }

        if file_modified {
            backup_file(path)?;
            fs::write(path, lines.join("\n") + "\n")
                .with_context(|| format!("Failed to write injected values to {}", path.display()))?;
            println!("   {} {}", "→".green(), path.display());
            modified_count += 1;
        }
    }

    if modified_count == 0 {
        println!(
            "   {} All injected values are already up to date",
            "✓".green()
        );
    }

    Ok(modified_count)
}

/// Resolve inject values: simple strings pass through, template values
/// have `{version}` replaced with the resolved catalog version.
fn resolve_inject_values(
    inject: &IndexMap<String, InjectValue>,
    resolved_catalog: &IndexMap<String, String>,
) -> Result<IndexMap<String, String>> {
    let mut values = IndexMap::new();

    for (key, val) in inject {
        let resolved = match val {
            InjectValue::Simple(s) => s.clone(),
            InjectValue::Template {
                template,
                from_catalog,
            } => {
                let version = resolved_catalog
                    .get(from_catalog.as_str())
                    .cloned()
                    .unwrap_or_else(|| {
                        let stripped = from_catalog.trim_start_matches('@');
                        resolved_catalog.get(stripped).cloned().unwrap_or_default()
                    });
                if version.is_empty() {
                    println!(
                        "   {} inject key '{}': catalog entry '{}' not found, skipping",
                        "⚠".yellow(),
                        key,
                        from_catalog
                    );
                    continue;
                }
                let clean_version = version.trim_start_matches('^').trim_start_matches('~');
                template.replace("{version}", clean_version)
            }
        };
        values.insert(key.clone(), resolved);
    }

    Ok(values)
}

