use anyhow::{Context, Result};
use colored::Colorize;
use serde_json::{Value, json};
use std::fs;
use std::path::Path;

/// Markers to identify airis-managed blocks in git hooks
const BEGIN_MARKER: &str = "# --- BEGIN AIRIS-WORKSPACE HOOKS ---";
const END_MARKER: &str = "# --- END AIRIS-WORKSPACE HOOKS ---";

/// Generate the pre-commit hook script dynamically
pub fn pre_commit_script() -> String {
    let mut script = String::from("#!/bin/bash\nset -e\n\n");
    script.push_str("# Generated by airis-workspace\n");
    script.push_str("# Prevents host pollution and leaks\n\n");
    
    // Check for staged .env files
    script.push_str("ENV_FILES=$(git diff --cached --name-only | grep -E '\\.env($|\\..*)' | grep -vE '\\.env\\.(example|template)$' || true)\n");
    script.push_str("if [ -n \"$ENV_FILES\" ]; then\n");
    script.push_str("    echo \"❌ Detected .env files staged for commit:\"\n");
    script.push_str("    echo \"$ENV_FILES\"\n");
    script.push_str("    echo \"   Remove them or convert to .env.example/.env.template.\"\n");
    script.push_str("    exit 1\n");
    script.push_str("fi\n\n");
    
    // Check for host node_modules
    script.push_str("if git diff --cached --name-only | grep -q '^node_modules/'; then\n");
    script.push_str("    echo \"❌ Host node_modules/ staged for commit.\"\n");
    script.push_str("    echo \"   Run: airis clean && airis install\"\n");
    script.push_str("    exit 1\n");
    script.push_str("fi\n\n");

    // Auto-bump version
    script.push_str("if command -v airis &> /dev/null; then\n");
    script.push_str("    echo \"🔄 Auto-bumping version...\"\n");
    script.push_str("    airis bump-version --auto\n");
    script.push_str("    git add manifest.toml Cargo.toml Cargo.lock 2>/dev/null || true\n");
    script.push_str("fi\n");
    
    script
}

/// Generate the pre-push hook script dynamically
pub fn pre_push_script() -> String {
    let mut script = String::from("#!/bin/bash\n\n");
    script.push_str("# Generated by airis-workspace\n");
    script.push_str("echo \"🛡️  Running environment hygiene checks...\"\n");
    script
}

/// Install a single Git hook with clear markers (non-destructive)
fn install_hook(git_hooks_dir: &Path, name: &str, content: &str) -> Result<()> {
    // 1. Ensure .airis/hooks exists and write implementation
    let airis_hooks_dir = Path::new(".airis/hooks");
    fs::create_dir_all(airis_hooks_dir).context("Failed to create .airis/hooks directory")?;
    
    let implementation_path = airis_hooks_dir.join(name);
    fs::write(&implementation_path, content)?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(&implementation_path, fs::Permissions::from_mode(0o755))?;
    }

    // 2. Prepare the block to inject into .git/hooks/
    let wrapper_block = format!(
        "\n{}\n./.airis/hooks/{}\n{}\n",
        BEGIN_MARKER, name, END_MARKER
    );
    
    let git_hook_path = git_hooks_dir.join(name);
    
    if git_hook_path.exists() {
        let existing = fs::read_to_string(&git_hook_path)?;
        
        if existing.contains(BEGIN_MARKER) {
            // Already has our block, replace it
            let mut new_content = String::new();
            let mut skip = false;
            for line in existing.lines() {
                if line == BEGIN_MARKER {
                    skip = true;
                    new_content.push_str(&wrapper_block.trim_start());
                } else if line == END_MARKER {
                    skip = false;
                    continue;
                } else if !skip {
                    new_content.push_str(line);
                    new_content.push('\n');
                }
            }
            fs::write(&git_hook_path, new_content)?;
        } else {
            // Append to existing
            let mut new_content = existing;
            if !new_content.ends_with('\n') {
                new_content.push('\n');
            }
            new_content.push_str(&wrapper_block);
            fs::write(&git_hook_path, new_content)?;
        }
    } else {
        // Create new
        let new_content = format!("#!/bin/sh\n{}", wrapper_block);
        fs::write(&git_hook_path, new_content)?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            fs::set_permissions(&git_hook_path, fs::Permissions::from_mode(0o755))?;
        }
    }

    Ok(())
}

/// Remove airis-managed blocks from a hook file
fn remove_hook_block(git_hooks_dir: &Path, name: &str) -> Result<()> {
    let path = git_hooks_dir.join(name);
    if !path.exists() {
        return Ok(());
    }

    let content = fs::read_to_string(&path)?;
    if !content.contains(BEGIN_MARKER) {
        return Ok(());
    }

    let mut new_content = String::new();
    let mut skip = false;
    for line in content.lines() {
        if line == BEGIN_MARKER {
            skip = true;
            continue;
        }
        if line == END_MARKER {
            skip = false;
            continue;
        }
        if !skip {
            new_content.push_str(line);
            new_content.push('\n');
        }
    }

    let trimmed = new_content.trim();
    if trimmed.is_empty() || trimmed == "#!/bin/sh" || trimmed == "#!/bin/bash" {
        fs::remove_file(&path)?;
    } else {
        fs::write(&path, new_content)?;
    }

    Ok(())
}

/// Uninstall all airis-managed hooks
pub fn uninstall() -> Result<()> {
    let git_dir = Path::new(".git");
    if !git_dir.exists() {
        return Ok(());
    }

    let hooks_dir = git_dir.join("hooks");
    remove_hook_block(&hooks_dir, "pre-commit")?;
    remove_hook_block(&hooks_dir, "pre-push")?;
    
    // Also remove from .airis
    let _ = fs::remove_dir_all(".airis/hooks");

    println!("✅ Git hooks uninstalled (airis-workspace blocks removed)");
    Ok(())
}

/// Install Git hooks and Claude Code hooks
pub fn install() -> Result<()> {
    let git_dir = Path::new(".git");

    if !git_dir.exists() {
        eprintln!("⚠️  Not a git repository. Skipping Git hook installation.");
    } else {
        let hooks_dir = git_dir.join("hooks");
        fs::create_dir_all(&hooks_dir).with_context(|| "Failed to create .git/hooks directory")?;

        install_hook(&hooks_dir, "pre-commit", &pre_commit_script())?;
        install_hook(&hooks_dir, "pre-push", &pre_push_script())?;

        println!("✅ Git hooks installed:");
        println!("   {} → {} (Wrapper in .git/hooks)", "pre-commit".green(), ".airis/hooks/pre-commit".dimmed());
        println!("   {} → {} (Wrapper in .git/hooks)", "pre-push".green(), ".airis/hooks/pre-push".dimmed());
    }

    // Claude Code hooks (Optional automation)
    install_claude_hooks()?;
    println!("\n✅ Claude Code hooks updated (~/.claude/settings.json)");
    Ok(())
}

// Reuse existing Claude hook logic...
fn remove_airis_entries(arr: &mut Vec<Value>) {
    arr.retain(|entry| {
        let dominated_by_airis = entry
            .get("hooks")
            .and_then(|h| h.as_array())
            .map(|hooks| {
                hooks.iter().any(|h| {
                    h.get("command")
                        .and_then(|c| c.as_str())
                        .map(|c| c.contains("airis-managed") || c.contains("# airis-managed"))
                        .unwrap_or(false)
                })
            })
            .unwrap_or(false);
        !dominated_by_airis
    });
}

fn install_claude_hooks() -> Result<()> {
    let home = dirs::home_dir().context("No home dir")?;
    let settings_path = home.join(".claude/settings.json");
    if !settings_path.exists() { return Ok(()); }

    let content = fs::read_to_string(&settings_path)?;
    let mut settings: Value = serde_json::from_str(&content)?;
    
    if let Some(hooks) = settings.get_mut("hooks") {
        if let Some(stop_arr) = hooks.get_mut("Stop").and_then(|v| v.as_array_mut()) {
            remove_airis_entries(stop_arr);
            stop_arr.push(json!({
                "matcher": "",
                "hooks": [{
                    "type": "command",
                    "command": "airis verify # airis-managed"
                }]
            }));
        }
    }

    fs::write(&settings_path, serde_json::to_string_pretty(&settings)? + "\n")?;
    Ok(())
}
