mod global;
mod local;
mod scripts;

#[cfg(test)]
mod tests;

pub use global::{install_global, status_global, uninstall_global, verify_global};
pub use local::{check_docker, install, status, uninstall};

/// Additional commands blocked in strict mode
const STRICT_MODE_DENY: &[&str] = &[
    "cargo", "rustc", "python", "python3", "pip", "pip3", "uv", "go", "java", "javac", "gradle",
    "mvn",
];

/// Commands allowed in hybrid mode (local builds)
const HYBRID_MODE_ALLOW: &[&str] = &["cargo", "rustc", "python", "python3", "pip", "pip3", "uv"];

const GUARDS_DIR: &str = ".airis/bin";

const GLOBAL_GUARD_MARKER: &str = "Auto-generated by airis guards --global install";
