mod global;
mod local;
mod scripts;

#[cfg(test)]
mod tests;

pub use global::{install_global, status_global, uninstall_global, verify_global};
pub use local::{check_allow, check_docker, install, status, uninstall};

const GUARDS_DIR: &str = ".airis/bin";

const GLOBAL_GUARD_MARKER: &str = "Auto-generated by airis guards --global install";
