use std::fs;
use std::io::BufRead;
use std::path::Path;

use anyhow::{Result, bail};

use super::GLOBAL_GUARD_MARKER;
use crate::manifest::GuardLevel;

/// Validate that a command name is safe for use in guard scripts.
fn validate_guard_cmd(cmd: &str) -> Result<()> {
    if cmd.is_empty() {
        bail!("Guard command name cannot be empty");
    }
    if !cmd
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || matches!(c, '.' | '-' | '_' | '+'))
    {
        bail!(
            "Guard command name contains invalid characters: \"{}\". Only [a-zA-Z0-9._+-] allowed.",
            cmd
        );
    }
    Ok(())
}

/// Ensure a guard script path is safe to write to.
pub(super) fn ensure_safe_guard_path(path: &Path) -> Result<()> {
    if path.is_symlink() {
        fs::remove_file(path)?;
    } else if path.exists() {
        let metadata = fs::symlink_metadata(path)?;
        if !metadata.is_file() {
            bail!("Guard path {} is not a regular file.", path.display());
        }
    }
    Ok(())
}

/// Install a global guard script with specific level
pub(super) fn install_global_guard(bin_dir: &Path, cmd: &str, level: GuardLevel) -> Result<()> {
    validate_guard_cmd(cmd)?;
    let script_path = bin_dir.join(cmd);
    ensure_safe_guard_path(&script_path)?;

    let level_str = match level {
        GuardLevel::Off => "off",
        GuardLevel::Warn => "warn",
        GuardLevel::Enforce => "enforce",
    };

    let content = format!(
        r#"#!/usr/bin/env bash
# {GLOBAL_GUARD_MARKER}
# DO NOT EDIT - managed by airis global guards

LEVEL="{level}"

# Helper: find the real command
find_real_cmd() {{
    PATH=$(echo "$PATH" | tr ':' '\n' | grep -v '\.airis/bin' | tr '\n' ':' | sed 's/:$//') which "$1" 2>/dev/null
}}

REAL_CMD=$(find_real_cmd {cmd})

# 1. Inside Docker/CI: always allow
if [[ -f /.dockerenv ]] || grep -qsE 'docker|containerd' /proc/1/cgroup 2>/dev/null || [[ "${{DOCKER_CONTAINER:-}}" == "true" ]] || [[ "${{CI:-}}" == "true" ]]; then
    if [[ -n "$REAL_CMD" ]]; then exec "$REAL_CMD" "$@"; else exit 127; fi
fi

# 2. Check repo-level opt-out
if command -v airis &>/dev/null && airis guards check-allow {cmd} 2>/dev/null; then
    if [[ -n "$REAL_CMD" ]]; then exec "$REAL_CMD" "$@"; else exit 127; fi
fi

# 3. Apply Policy
case "$LEVEL" in
    warn)
        echo "⚠️  AIRIS: '{cmd}' is being run on the host. Consider using 'airis run' or 'airis shell'."
        if [[ -n "$REAL_CMD" ]]; then exec "$REAL_CMD" "$@"; else exit 127; fi
        ;;
    enforce)
        echo "❌ '{cmd}' is blocked on this machine (Docker-First)."
        echo ""
        echo "Use airis commands instead:"
        echo "  airis up / airis run / airis shell"
        echo ""
        echo "To allow this command in this repo, add to manifest.toml:"
        echo "  [guards]"
        echo "  allow = [\"{cmd}\"]"
        exit 1
        ;;
    *)
        if [[ -n "$REAL_CMD" ]]; then exec "$REAL_CMD" "$@"; else exit 127; fi
        ;;
esac
"#,
        GLOBAL_GUARD_MARKER = GLOBAL_GUARD_MARKER,
        level = level_str,
        cmd = cmd
    );

    fs::write(&script_path, content)?;
    make_executable(&script_path)?;
    Ok(())
}

pub(super) fn make_executable(_path: &Path) -> Result<()> {
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = fs::metadata(_path)?.permissions();
        perms.set_mode(0o755); // rwxr-xr-x
        fs::set_permissions(_path, perms)?;
    }
    Ok(())
}

pub(super) fn is_global_guard(path: &Path) -> Result<bool> {
    if !path.exists() { return Ok(false); }
    let file = fs::File::open(path)?;
    let reader = std::io::BufReader::new(file);
    for line in reader.lines().take(5).flatten() {
        if line.contains(GLOBAL_GUARD_MARKER) {
            return Ok(true);
        }
    }
    Ok(false)
}

pub(super) fn is_airis_guard(path: &Path) -> Result<bool> {
    if !path.exists() { return Ok(false); }
    let file = fs::File::open(path)?;
    let reader = std::io::BufReader::new(file);
    for line in reader.lines().take(5).flatten() {
        if line.contains("Auto-generated by airis guards install") {
            return Ok(true);
        }
    }
    Ok(false)
}

pub(super) fn install_deny_guard(dir: &Path, cmd: &str, _msg: Option<&String>) -> Result<()> {
    install_global_guard(dir, cmd, GuardLevel::Enforce)
}

pub(super) fn install_wrap_guard(dir: &Path, cmd: &str, wrapper: &str) -> Result<()> {
    validate_guard_cmd(cmd)?;
    let script_path = dir.join(cmd);
    let content = format!("#!/usr/bin/env bash\nexec {} \"$@\"\n", wrapper);
    fs::write(&script_path, content)?;
    make_executable(&script_path)
}
