use std::fs;
use std::io::BufRead;
#[cfg(unix)]
use std::os::unix::fs::PermissionsExt;
use std::path::Path;

use anyhow::{Context, Result, bail};
use colored::Colorize;

use super::GLOBAL_GUARD_MARKER;

/// Validate that a command name is safe for use in guard scripts.
/// Only allows alphanumeric characters, dots, hyphens, underscores, and plus signs.
fn validate_guard_cmd(cmd: &str) -> Result<()> {
    if cmd.is_empty() {
        bail!("Guard command name cannot be empty");
    }
    if !cmd
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || matches!(c, '.' | '-' | '_' | '+'))
    {
        bail!(
            "Guard command name contains invalid characters: \"{}\". Only [a-zA-Z0-9._+-] allowed.",
            cmd
        );
    }
    Ok(())
}

/// Validate that a wrapper path is safe for use in guard scripts.
/// Allows command names with arguments (spaces), absolute paths, but rejects shell metacharacters.
fn validate_wrapper_path(wrapper: &str) -> Result<()> {
    if wrapper.is_empty() {
        bail!("Guard wrapper path cannot be empty");
    }
    // Reject shell metacharacters that could enable injection
    let dangerous_chars = ['`', '$', '(', ')', ';', '&', '|', '<', '>', '\n', '\r', '\\', '!', '{', '}'];
    if let Some(bad) = wrapper.chars().find(|c| dangerous_chars.contains(c)) {
        bail!(
            "Guard wrapper contains dangerous character '{}': \"{}\". Shell metacharacters are not allowed.",
            bad,
            wrapper
        );
    }
    Ok(())
}

/// Ensure a guard script path is safe to write to.
///
/// Rejects symlinks and non-regular files to prevent symlink attacks where
/// an attacker replaces a guard script with a symlink to a malicious binary.
/// Returns the validated path, or an error if the path is unsafe.
pub(super) fn ensure_safe_guard_path(path: &Path) -> Result<()> {
    // Check symlink BEFORE following it (lstat, not stat)
    if path.is_symlink() {
        let target = fs::read_link(path)
            .map(|t| t.display().to_string())
            .unwrap_or_else(|_| "unknown".to_string());
        // Remove the symlink to prevent execution
        fs::remove_file(path)
            .with_context(|| format!("Failed to remove symlink at {}", path.display()))?;
        eprintln!(
            "🚨 {} Symlink detected at {} → {}. Removed for security.",
            "SECURITY".red().bold(),
            path.display(),
            target
        );
    } else if path.exists() {
        let metadata = fs::symlink_metadata(path)?;
        let file_type = metadata.file_type();
        if !file_type.is_file() {
            bail!(
                "Guard path {} is not a regular file (type: {:?}). Refusing to overwrite.",
                path.display(),
                file_type
            );
        }
    }
    Ok(())
}

pub(super) fn install_deny_guard(
    guards_dir: &Path,
    cmd: &str,
    custom_message: Option<&String>,
) -> Result<()> {
    validate_guard_cmd(cmd)?;
    let script_path = guards_dir.join(cmd);
    ensure_safe_guard_path(&script_path)?;

    let message = if let Some(msg) = custom_message {
        msg.clone()
    } else {
        format!(
            "'{}' should run inside Docker. Redirecting to 'airis install'...",
            cmd
        )
    };

    // Sanitize message to prevent heredoc delimiter collision
    let safe_message = message.replace("AIRIS_ERR", "AIRIS_E_R_R");

    let content = format!(
        r#"#!/usr/bin/env bash
# Auto-generated by airis guards install
# DO NOT EDIT - managed by manifest.toml [guards] section

# 1. Check if this is an install command (install, add, remove, update)
IS_INSTALL=false
for arg in "$@"; do
    if [[ "$arg" == "install" || "$arg" == "add" || "$arg" == "remove" || "$arg" == "update" || "$arg" == "i" ]]; then
        IS_INSTALL=true
        break
    fi
done

# 2. Redirect to 'airis install' if it looks like a dependency change
if [ "$IS_INSTALL" = true ]; then
    echo "🔄 '{cmd} $@' → airis install $@"
    exec airis install "$@"
else
    # For other commands, just block with a helpful message
    cat <<'AIRIS_ERR'
❌ ERROR: {message}
Hint: Use 'airis shell' to run commands inside the container.
AIRIS_ERR
    exit 1
fi
"#,
        cmd = cmd,
        message = safe_message,
    );

    fs::write(&script_path, content)
        .with_context(|| format!("Failed to write guard script for '{}'", cmd))?;

    make_executable(&script_path)?;

    Ok(())
}

pub(super) fn install_wrap_guard(guards_dir: &Path, cmd: &str, wrapper: &str) -> Result<()> {
    validate_guard_cmd(cmd)?;
    validate_wrapper_path(wrapper)?;
    let script_path = guards_dir.join(cmd);
    ensure_safe_guard_path(&script_path)?;

    let content = format!(
        r#"#!/usr/bin/env bash
# Auto-generated by airis guards install
# DO NOT EDIT - managed by manifest.toml [guards.wrap] section

# Wrapper: {} → {}
exec {} "$@"
"#,
        cmd, wrapper, wrapper
    );

    fs::write(&script_path, content)
        .with_context(|| format!("Failed to write guard script for '{}'", cmd))?;

    make_executable(&script_path)?;

    Ok(())
}

pub(super) fn install_global_guard(bin_dir: &Path, cmd: &str) -> Result<()> {
    validate_guard_cmd(cmd)?;
    let script_path = bin_dir.join(cmd);
    ensure_safe_guard_path(&script_path)?;

    // Global guard script that:
    // 1. Inside Docker/CI: pass through to real command
    // 2. On host: check repo-level opt-out via `airis guards check-allow`
    // 3. On host (no opt-out): block (Docker-First enforcement)
    let content = format!(
        r#"#!/usr/bin/env bash
# {GLOBAL_GUARD_MARKER}
# DO NOT EDIT - managed by airis global guards

# Helper: find the real command (excluding .airis/bin from PATH)
find_real_cmd() {{
    PATH=$(echo "$PATH" | tr ':' '\n' | grep -v '\.airis/bin' | tr '\n' ':' | sed 's/:$//') which "$1" 2>/dev/null
}}

# Docker container: allow (filesystem checks first, env var as fallback)
if [[ -f /.dockerenv ]] || grep -qsE 'docker|containerd' /proc/1/cgroup 2>/dev/null || [[ "${{DOCKER_CONTAINER:-}}" == "true" ]]; then
    REAL_CMD=$(find_real_cmd {cmd})
    if [[ -n "$REAL_CMD" && -x "$REAL_CMD" ]]; then
        exec "$REAL_CMD" "$@"
    fi
    exit 127
fi

# CI environment: allow
if [[ "${{CI:-}}" == "true" ]] || [[ -n "${{GITHUB_ACTIONS:-}}" ]] || [[ -n "${{GITLAB_CI:-}}" ]]; then
    REAL_CMD=$(find_real_cmd {cmd})
    if [[ -n "$REAL_CMD" && -x "$REAL_CMD" ]]; then
        exec "$REAL_CMD" "$@"
    fi
    exit 127
fi

# Host: check repo-level opt-out (uses Rust TOML parser for correctness)
if command -v airis &>/dev/null; then
    if airis guards check-allow {cmd} 2>/dev/null; then
        REAL_CMD=$(find_real_cmd {cmd})
        if [[ -n "$REAL_CMD" && -x "$REAL_CMD" ]]; then
            exec "$REAL_CMD" "$@"
        fi
        exit 127
    fi
fi

# Host: block
echo "❌ '{cmd}' is blocked on this machine (Docker-First)."
echo ""
echo "Use airis commands instead:"
echo "  airis up      # Start all services (docker compose up + build)"
echo "  airis shell   # Enter container shell"
echo ""
echo "To allow '{cmd}' in this repo, add to .airis/guards.toml:"
echo "  [guards]"
echo "  allow = [\"{cmd}\"]"
echo ""
echo "To manage guards:"
echo "  airis guards --global status     # Check status"
echo "  airis guards --global uninstall  # Remove guards"
exit 1
"#,
        GLOBAL_GUARD_MARKER = GLOBAL_GUARD_MARKER,
        cmd = cmd
    );

    fs::write(&script_path, content)
        .with_context(|| format!("Failed to write global guard script for '{}'", cmd))?;

    make_executable(&script_path)?;

    Ok(())
}

pub(super) fn make_executable(_path: &Path) -> Result<()> {
    #[cfg(unix)]
    {
        let mut perms = fs::metadata(_path)?.permissions();
        perms.set_mode(0o755); // rwxr-xr-x
        fs::set_permissions(_path, perms)?;
    }
    Ok(())
}

/// Check if a file is an airis local guard (contains our marker)
pub(super) fn is_airis_guard(path: &Path) -> Result<bool> {
    let file = fs::File::open(path)?;
    let reader = std::io::BufReader::new(file);

    // Check first 5 lines for the marker
    for line in reader.lines().take(5).flatten() {
        if line.contains("Auto-generated by airis guards install") {
            return Ok(true);
        }
    }

    Ok(false)
}

/// Check if a file is an airis global guard (contains our marker)
pub(super) fn is_global_guard(path: &Path) -> Result<bool> {
    let file = fs::File::open(path)?;
    let reader = std::io::BufReader::new(file);

    // Check first 5 lines for the marker
    for line in reader.lines().take(5).flatten() {
        if line.contains(GLOBAL_GUARD_MARKER) {
            return Ok(true);
        }
    }

    Ok(false)
}
