use super::scripts::*;
use super::*;

use std::fs;
use std::path::PathBuf;

use crate::manifest::{GlobalConfig, Mode};
use local::{RepoGuards, merge_deny_list};

#[test]
fn test_strict_mode_deny_list() {
    // Strict mode should block cargo, python, etc.
    assert!(STRICT_MODE_DENY.contains(&"cargo"));
    assert!(STRICT_MODE_DENY.contains(&"python"));
    assert!(STRICT_MODE_DENY.contains(&"go"));
}

#[test]
fn test_strict_mode_adds_to_deny_list() {
    // Simulate strict mode adding commands
    let mut deny_list: Vec<String> = vec!["npm".to_string(), "yarn".to_string()];

    for cmd in STRICT_MODE_DENY {
        if !deny_list.contains(&cmd.to_string()) {
            deny_list.push(cmd.to_string());
        }
    }

    // Should now contain both original and strict mode commands
    assert!(deny_list.contains(&"npm".to_string()));
    assert!(deny_list.contains(&"cargo".to_string()));
    assert!(deny_list.contains(&"python".to_string()));
}

#[test]
fn test_global_config_default() {
    let config = GlobalConfig::default();
    assert_eq!(config.version, 1);
    assert!(config.guards.deny.contains(&"npm".to_string()));
    assert!(config.guards.deny.contains(&"yarn".to_string()));
    assert!(config.guards.deny.contains(&"pnpm".to_string()));
    assert!(config.guards.deny.contains(&"bun".to_string()));
    assert!(config.guards.deny.contains(&"npx".to_string()));
}

#[test]
fn test_global_config_paths() {
    // Just verify that path functions don't panic
    let config_path = GlobalConfig::config_path();
    assert!(config_path.is_ok());

    let bin_dir = GlobalConfig::bin_dir();
    assert!(bin_dir.is_ok());

    // Verify paths contain expected components
    let config_path = config_path.unwrap();
    assert!(config_path.to_string_lossy().contains(".airis"));
    assert!(config_path.to_string_lossy().contains("global-config.toml"));

    let bin_dir = bin_dir.unwrap();
    assert!(bin_dir.to_string_lossy().contains(".airis"));
    assert!(bin_dir.to_string_lossy().ends_with("bin"));
}

#[test]
fn test_global_config_serialization() {
    let config = GlobalConfig::default();
    let toml_str = toml::to_string_pretty(&config).unwrap();

    // Verify it can be deserialized back
    let parsed: GlobalConfig = toml::from_str(&toml_str).unwrap();
    assert_eq!(parsed.version, config.version);
    assert_eq!(parsed.guards.deny.len(), config.guards.deny.len());
}

#[test]
fn test_is_airis_guard_marker() {
    use std::io::Write;

    let dir = tempfile::tempdir().unwrap();
    let guard_file = dir.path().join("npm");

    // Write a file with the guard marker
    let mut f = fs::File::create(&guard_file).unwrap();
    writeln!(f, "#!/usr/bin/env bash").unwrap();
    writeln!(f, "# Auto-generated by airis guards install").unwrap();
    writeln!(f, "echo 'blocked'").unwrap();

    assert!(is_airis_guard(&guard_file).unwrap());

    // Write a file without the marker
    let other_file = dir.path().join("other");
    let mut f = fs::File::create(&other_file).unwrap();
    writeln!(f, "#!/usr/bin/env bash").unwrap();
    writeln!(f, "echo 'hello'").unwrap();

    assert!(!is_airis_guard(&other_file).unwrap());
}

#[test]
fn test_is_global_guard_marker() {
    use std::io::Write;

    let dir = tempfile::tempdir().unwrap();
    let guard_file = dir.path().join("npm");

    // Write a file with the global guard marker
    let mut f = fs::File::create(&guard_file).unwrap();
    writeln!(f, "#!/usr/bin/env bash").unwrap();
    writeln!(f, "# {}", GLOBAL_GUARD_MARKER).unwrap();
    writeln!(f, "echo 'blocked'").unwrap();

    assert!(is_global_guard(&guard_file).unwrap());

    // Write a file with the local guard marker (should not match)
    let local_file = dir.path().join("local");
    let mut f = fs::File::create(&local_file).unwrap();
    writeln!(f, "#!/usr/bin/env bash").unwrap();
    writeln!(f, "# Auto-generated by airis guards install").unwrap();
    writeln!(f, "echo 'blocked'").unwrap();

    assert!(!is_global_guard(&local_file).unwrap());
}

#[test]
fn test_install_deny_guard_default_message() {
    let dir = tempfile::tempdir().unwrap();
    install_deny_guard(dir.path(), "npm", None).unwrap();

    let script_path = dir.path().join("npm");
    assert!(script_path.exists());

    let content = fs::read_to_string(&script_path).unwrap();

    // Should contain the shebang
    assert!(content.starts_with("#!/usr/bin/env bash"));
    // Should contain the auto-generated marker
    assert!(content.contains("Auto-generated by airis guards install"));
    // Should contain the redirection logic
    assert!(content.contains("IS_INSTALL=true"));
    assert!(content.contains("airis install"));
    // Should exit with code 1 for non-install commands
    assert!(content.contains("exit 1"));
}

#[test]
fn test_install_deny_guard_with_custom_message() {
    let dir = tempfile::tempdir().unwrap();
    let custom_msg = "Please use 'airis install' instead of yarn.".to_string();
    install_deny_guard(dir.path(), "yarn", Some(&custom_msg)).unwrap();

    let script_path = dir.path().join("yarn");
    assert!(script_path.exists());

    let content = fs::read_to_string(&script_path).unwrap();

    // Should contain the custom message
    assert!(content.contains("Please use 'airis install' instead of yarn."));
    // Should still contain the redirection logic (custom message is for non-install commands)
    assert!(content.contains("IS_INSTALL=true"));
    // Should still exit with code 1
    assert!(content.contains("exit 1"));
}

#[test]
fn test_install_wrap_guard() {
    let dir = tempfile::tempdir().unwrap();
    let wrapper = "docker compose exec workspace pnpm";
    install_wrap_guard(dir.path(), "pnpm", wrapper).unwrap();

    let script_path = dir.path().join("pnpm");
    assert!(script_path.exists());

    let content = fs::read_to_string(&script_path).unwrap();

    // Should contain the shebang
    assert!(content.starts_with("#!/usr/bin/env bash"));
    // Should contain the auto-generated marker for wrap section
    assert!(content.contains("guards.wrap"));
    // Should contain the exec wrapper line with "$@" for argument forwarding
    assert!(content.contains(&format!("exec {} \"$@\"", wrapper)));
    // Should contain the comment showing the mapping
    assert!(content.contains(&format!("# Wrapper: pnpm → {}", wrapper)));
    // Should NOT contain "exit 1" (wrap lets through)
    assert!(!content.contains("exit 1"));
}

#[cfg(unix)]
#[test]
fn test_script_permissions() {
    use std::os::unix::fs::PermissionsExt;

    let dir = tempfile::tempdir().unwrap();

    // Test deny guard permissions
    install_deny_guard(dir.path(), "npm", None).unwrap();
    let perms = fs::metadata(dir.path().join("npm")).unwrap().permissions();
    assert_eq!(perms.mode() & 0o777, 0o755);

    // Test wrap guard permissions
    install_wrap_guard(dir.path(), "pnpm", "docker compose exec workspace pnpm").unwrap();
    let perms = fs::metadata(dir.path().join("pnpm")).unwrap().permissions();
    assert_eq!(perms.mode() & 0o777, 0o755);
}

#[cfg(unix)]
#[test]
fn test_make_executable_sets_755() {
    use std::os::unix::fs::PermissionsExt;

    let dir = tempfile::tempdir().unwrap();
    let file_path = dir.path().join("test_script");

    // Create a file with default permissions
    fs::write(&file_path, "#!/usr/bin/env bash\necho hello").unwrap();

    // Verify it is not yet 755 (default is typically 644)
    let perms_before = fs::metadata(&file_path).unwrap().permissions();
    assert_ne!(perms_before.mode() & 0o777, 0o755);

    // Apply make_executable
    make_executable(&file_path).unwrap();

    let perms_after = fs::metadata(&file_path).unwrap().permissions();
    assert_eq!(perms_after.mode() & 0o777, 0o755);
}

#[test]
fn test_full_install_with_tempdir() {
    let _guard = crate::test_lock::DIR_LOCK.lock().unwrap();
    let original_dir = std::env::current_dir().unwrap();
    let dir = tempfile::tempdir().unwrap();
    std::env::set_current_dir(dir.path()).unwrap();

    let result = std::panic::catch_unwind(|| {
        // Write a minimal manifest.toml with deny, wrap, and deny_with_message entries
        let manifest_content = r#"
version = 1
[project]
id = "test"

[workspace]
name = "test-workspace"

[guards]
deny = ["npm", "yarn"]

[guards.wrap]
pnpm = "docker compose exec workspace pnpm"

[guards.deny_with_message]
bun = "bun is not supported. Use pnpm via airis."
"#;
        fs::write("manifest.toml", manifest_content).unwrap();

        // Run install
        install().unwrap();

        // Verify guards directory was created
        let guards_dir = PathBuf::from(GUARDS_DIR);
        assert!(guards_dir.exists(), ".airis/bin should exist");

        // Verify deny guards
        let npm_script = guards_dir.join("npm");
        assert!(npm_script.exists(), "npm guard should exist");
        let npm_content = fs::read_to_string(&npm_script).unwrap();
        assert!(npm_content.contains("exit 1"));
        assert!(npm_content.contains("IS_INSTALL=true"));
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            assert_eq!(
                fs::metadata(&npm_script).unwrap().permissions().mode() & 0o777,
                0o755
            );
        }

        let yarn_script = guards_dir.join("yarn");
        assert!(yarn_script.exists(), "yarn guard should exist");
        let yarn_content = fs::read_to_string(&yarn_script).unwrap();
        assert!(yarn_content.contains("exit 1"));

        // Verify wrap guard
        let pnpm_script = guards_dir.join("pnpm");
        assert!(pnpm_script.exists(), "pnpm wrap guard should exist");
        let pnpm_content = fs::read_to_string(&pnpm_script).unwrap();
        assert!(pnpm_content.contains("exec docker compose exec workspace pnpm \"$@\""));
        assert!(!pnpm_content.contains("exit 1"));

        // Verify deny_with_message guard
        let bun_script = guards_dir.join("bun");
        assert!(
            bun_script.exists(),
            "bun deny_with_message guard should exist"
        );
        let bun_content = fs::read_to_string(&bun_script).unwrap();
        assert!(bun_content.contains("bun is not supported. Use pnpm via airis."));
        assert!(bun_content.contains("exit 1"));
    });

    std::env::set_current_dir(original_dir).unwrap();
    result.unwrap();
}

// ── symlink attack protection tests ──

#[cfg(unix)]
#[test]
fn test_ensure_safe_guard_path_removes_symlink() {
    let dir = tempfile::tempdir().unwrap();
    let target = dir.path().join("malicious");
    fs::write(&target, "#!/bin/bash\necho pwned").unwrap();

    let guard_path = dir.path().join("npm");
    std::os::unix::fs::symlink(&target, &guard_path).unwrap();
    assert!(guard_path.is_symlink());

    // ensure_safe_guard_path should remove the symlink
    ensure_safe_guard_path(&guard_path).unwrap();
    assert!(!guard_path.exists(), "symlink should have been removed");
    // Target should still exist (not the symlink's target)
    assert!(target.exists(), "symlink target should not be removed");
}

#[cfg(unix)]
#[test]
fn test_install_deny_guard_replaces_symlink() {
    let dir = tempfile::tempdir().unwrap();
    let target = dir.path().join("malicious");
    fs::write(&target, "#!/bin/bash\necho pwned").unwrap();

    let guard_path = dir.path().join("npm");
    std::os::unix::fs::symlink(&target, &guard_path).unwrap();

    // install_deny_guard should succeed (removes symlink, writes real file)
    install_deny_guard(dir.path(), "npm", None).unwrap();

    assert!(!guard_path.is_symlink(), "should no longer be a symlink");
    assert!(guard_path.is_file(), "should be a regular file");
    let content = fs::read_to_string(&guard_path).unwrap();
    assert!(content.contains("Auto-generated by airis guards install"));
}

#[cfg(unix)]
#[test]
fn test_install_wrap_guard_replaces_symlink() {
    let dir = tempfile::tempdir().unwrap();
    let target = dir.path().join("malicious");
    fs::write(&target, "#!/bin/bash\necho pwned").unwrap();

    let guard_path = dir.path().join("pnpm");
    std::os::unix::fs::symlink(&target, &guard_path).unwrap();

    install_wrap_guard(dir.path(), "pnpm", "docker compose exec workspace pnpm").unwrap();

    assert!(!guard_path.is_symlink());
    let content = fs::read_to_string(&guard_path).unwrap();
    assert!(content.contains("guards.wrap"));
}

#[test]
fn test_ensure_safe_guard_path_allows_regular_file() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("npm");
    fs::write(&path, "existing content").unwrap();

    // Should succeed for regular files
    ensure_safe_guard_path(&path).unwrap();
    assert!(path.exists());
}

#[test]
fn test_ensure_safe_guard_path_allows_nonexistent() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("nonexistent");

    // Should succeed for non-existent paths
    ensure_safe_guard_path(&path).unwrap();
}

// ── merge_deny_list tests ──

#[test]
fn test_merge_basic_global_deny() {
    let global = GlobalConfig::default();
    let repo = RepoGuards::default();

    let result = merge_deny_list(&global, &repo, &[], &[], &Mode::DockerFirst);

    assert!(result.contains(&"npm".to_string()));
    assert!(result.contains(&"pnpm".to_string()));
    assert!(result.contains(&"npx".to_string()));
}

#[test]
fn test_merge_repo_allow_removes_from_global() {
    let global = GlobalConfig::default();
    let repo = RepoGuards {
        deny: vec![],
        allow: vec!["npm".to_string(), "npx".to_string()],
    };

    let result = merge_deny_list(&global, &repo, &[], &[], &Mode::DockerFirst);

    assert!(!result.contains(&"npm".to_string()));
    assert!(!result.contains(&"npx".to_string()));
    // Others should remain
    assert!(result.contains(&"yarn".to_string()));
    assert!(result.contains(&"pnpm".to_string()));
}

#[test]
fn test_merge_manifest_deny_adds() {
    let global = GlobalConfig::default();
    let repo = RepoGuards::default();
    let manifest_deny = vec!["pip".to_string(), "python".to_string()];

    let result = merge_deny_list(&global, &repo, &manifest_deny, &[], &Mode::DockerFirst);

    assert!(result.contains(&"pip".to_string()));
    assert!(result.contains(&"python".to_string()));
    assert!(result.contains(&"npm".to_string()));
}

#[test]
fn test_merge_manifest_allow_removes() {
    let global = GlobalConfig::default();
    let repo = RepoGuards::default();
    let manifest_allow = vec!["npm".to_string()];

    let result = merge_deny_list(&global, &repo, &[], &manifest_allow, &Mode::DockerFirst);

    assert!(!result.contains(&"npm".to_string()));
    assert!(result.contains(&"yarn".to_string()));
}

#[test]
fn test_merge_repo_deny_adds() {
    let global = GlobalConfig::default();
    let repo = RepoGuards {
        deny: vec!["cargo".to_string()],
        allow: vec![],
    };

    let result = merge_deny_list(&global, &repo, &[], &[], &Mode::DockerFirst);

    assert!(result.contains(&"cargo".to_string()));
    assert!(result.contains(&"npm".to_string()));
}

#[test]
fn test_merge_strict_mode_adds_extra() {
    let global = GlobalConfig::default();
    let repo = RepoGuards::default();

    let result = merge_deny_list(&global, &repo, &[], &[], &Mode::Strict);

    assert!(result.contains(&"cargo".to_string()));
    assert!(result.contains(&"go".to_string()));
    assert!(result.contains(&"java".to_string()));
    assert!(result.contains(&"npm".to_string()));
}

#[test]
fn test_merge_allow_nonexistent_command_is_noop() {
    let global = GlobalConfig::default();
    let repo = RepoGuards {
        deny: vec![],
        allow: vec!["nonexistent_cmd".to_string()],
    };

    let result = merge_deny_list(&global, &repo, &[], &[], &Mode::DockerFirst);

    // Should still have defaults, no crash
    assert!(result.contains(&"npm".to_string()));
}

#[test]
fn test_merge_no_duplicates() {
    let global = GlobalConfig::default();
    let repo = RepoGuards {
        deny: vec!["npm".to_string()], // Already in global
        allow: vec![],
    };

    let result = merge_deny_list(&global, &repo, &[], &[], &Mode::DockerFirst);

    let npm_count = result.iter().filter(|c| *c == "npm").count();
    assert_eq!(npm_count, 1, "npm should appear exactly once");
}

#[test]
fn test_merge_global_allow_removes_from_deny() {
    let mut global = GlobalConfig::default();
    global.guards.allow = vec!["npm".to_string()];
    let repo = RepoGuards::default();

    let result = merge_deny_list(&global, &repo, &[], &[], &Mode::DockerFirst);

    assert!(!result.contains(&"npm".to_string()));
    assert!(result.contains(&"yarn".to_string()));
}

#[test]
fn test_install_without_manifest_uses_global() {
    let _guard = crate::test_lock::DIR_LOCK.lock().unwrap();
    let original_dir = std::env::current_dir().unwrap();
    let dir = tempfile::tempdir().unwrap();
    std::env::set_current_dir(dir.path()).unwrap();

    let result = std::panic::catch_unwind(|| {
        // No manifest.toml, no .airis/guards.toml
        // Should still work with global defaults
        install().unwrap();

        let guards_dir = PathBuf::from(GUARDS_DIR);
        assert!(guards_dir.exists(), ".airis/bin should exist");

        // Should have guards from global defaults
        assert!(guards_dir.join("npm").exists());
        assert!(guards_dir.join("pnpm").exists());
    });

    std::env::set_current_dir(original_dir).unwrap();
    result.unwrap();
}

#[test]
fn test_install_with_repo_guards_toml() {
    let _guard = crate::test_lock::DIR_LOCK.lock().unwrap();
    let original_dir = std::env::current_dir().unwrap();
    let dir = tempfile::tempdir().unwrap();
    std::env::set_current_dir(dir.path()).unwrap();

    let result = std::panic::catch_unwind(|| {
        // Create .airis/guards.toml with allow for npm
        fs::create_dir_all(".airis").unwrap();
        fs::write(
            ".airis/guards.toml",
            r#"
[guards]
deny = ["pip"]
allow = ["npm"]
"#,
        )
        .unwrap();

        install().unwrap();

        let guards_dir = PathBuf::from(GUARDS_DIR);

        // npm should NOT be blocked (repo allow)
        assert!(!guards_dir.join("npm").exists(), "npm should be allowed");
        // pip should be blocked (repo deny)
        assert!(guards_dir.join("pip").exists(), "pip should be denied");
        // pnpm should be blocked (global deny, not in allow)
        assert!(guards_dir.join("pnpm").exists(), "pnpm should be denied");
    });

    std::env::set_current_dir(original_dir).unwrap();
    result.unwrap();
}

#[test]
fn test_install_with_broken_repo_guards_toml() {
    let _guard = crate::test_lock::DIR_LOCK.lock().unwrap();
    let original_dir = std::env::current_dir().unwrap();
    let dir = tempfile::tempdir().unwrap();
    std::env::set_current_dir(dir.path()).unwrap();

    let result = std::panic::catch_unwind(|| {
        // Broken TOML
        fs::create_dir_all(".airis").unwrap();
        fs::write(".airis/guards.toml", "this is not valid toml [[[").unwrap();

        // Should error with helpful message, not panic
        let res = install();
        assert!(res.is_err(), "Should return error for broken TOML");
    });

    std::env::set_current_dir(original_dir).unwrap();
    result.unwrap();
}

#[test]
fn test_global_guard_script_contains_check_allow() {
    let dir = tempfile::tempdir().unwrap();
    install_global_guard(dir.path(), "npm").unwrap();

    let content = fs::read_to_string(dir.path().join("npm")).unwrap();

    // Should contain the airis guards check-allow call
    assert!(content.contains("airis guards check-allow npm"));
    // Should contain the find_real_cmd helper
    assert!(content.contains("find_real_cmd"));
    // Should contain opt-out instructions
    assert!(content.contains(".airis/guards.toml"));
}

// ── bash syntax validation tests ──

fn assert_valid_bash(path: &std::path::Path) {
    let output = std::process::Command::new("bash")
        .arg("-n")
        .arg(path)
        .output()
        .expect("failed to run bash -n");
    assert!(
        output.status.success(),
        "bash syntax error in {}: {}",
        path.display(),
        String::from_utf8_lossy(&output.stderr)
    );
}

#[cfg(unix)]
#[test]
fn test_deny_guard_script_is_valid_bash() {
    let dir = tempfile::tempdir().unwrap();
    install_deny_guard(dir.path(), "npm", None).unwrap();
    assert_valid_bash(&dir.path().join("npm"));
}

#[cfg(unix)]
#[test]
fn test_deny_guard_with_custom_message_is_valid_bash() {
    let dir = tempfile::tempdir().unwrap();
    let msg = "Use 'docker compose exec <service> pnpm ...' instead. Docker First!".to_string();
    install_deny_guard(dir.path(), "pnpm", Some(&msg)).unwrap();
    assert_valid_bash(&dir.path().join("pnpm"));
}

#[cfg(unix)]
#[test]
fn test_wrap_guard_script_is_valid_bash() {
    let dir = tempfile::tempdir().unwrap();
    install_wrap_guard(dir.path(), "pnpm", "docker compose exec workspace pnpm").unwrap();
    assert_valid_bash(&dir.path().join("pnpm"));
}

#[cfg(unix)]
#[test]
fn test_global_guard_script_is_valid_bash() {
    let dir = tempfile::tempdir().unwrap();
    install_global_guard(dir.path(), "npm").unwrap();
    assert_valid_bash(&dir.path().join("npm"));
}

// ── deny_with_message edge cases ──

#[cfg(unix)]
#[test]
fn test_deny_guard_message_with_single_quotes() {
    let dir = tempfile::tempdir().unwrap();
    let msg = "Use 'airis install' instead of 'npm install'.".to_string();
    install_deny_guard(dir.path(), "npm", Some(&msg)).unwrap();

    let content = fs::read_to_string(dir.path().join("npm")).unwrap();
    // Single quotes inside <<'AIRIS_ERR' heredoc are safe
    assert!(content.contains("Use 'airis install' instead of 'npm install'."));
    assert_valid_bash(&dir.path().join("npm"));
}

#[cfg(unix)]
#[test]
fn test_deny_guard_message_airis_err_delimiter_collision() {
    let dir = tempfile::tempdir().unwrap();
    let msg = "Error code: AIRIS_ERR_001 — use Docker instead.".to_string();
    install_deny_guard(dir.path(), "npm", Some(&msg)).unwrap();

    let content = fs::read_to_string(dir.path().join("npm")).unwrap();
    // Sanitizer replaces "AIRIS_ERR" with "AIRIS_E_R_R" in message body
    assert!(
        content.contains("AIRIS_E_R_R"),
        "sanitized delimiter should appear in message"
    );
    // Heredoc structure itself must remain intact (opening + closing delimiters)
    let delimiter_count = content.matches("AIRIS_ERR").count();
    assert!(
        delimiter_count >= 2,
        "heredoc delimiters should be intact, found {} occurrences",
        delimiter_count
    );
    assert_valid_bash(&dir.path().join("npm"));
}

#[cfg(unix)]
#[test]
fn test_deny_guard_message_with_shell_special_chars() {
    let dir = tempfile::tempdir().unwrap();
    // Characters that would break unquoted strings but are safe in <<'AIRIS_ERR' heredoc
    let msg = "Use \"docker compose\" — not $npm! <hint>: see docs & wiki".to_string();
    install_deny_guard(dir.path(), "npm", Some(&msg)).unwrap();
    assert_valid_bash(&dir.path().join("npm"));
}

// ── command name / wrapper validation rejection tests ──

#[test]
fn test_deny_guard_rejects_command_with_spaces() {
    let dir = tempfile::tempdir().unwrap();
    let result = install_deny_guard(dir.path(), "npm install", None);
    assert!(result.is_err());
    let msg = result.unwrap_err().to_string();
    assert!(msg.contains("invalid characters"), "got: {msg}");
}

#[test]
fn test_deny_guard_rejects_command_with_path_traversal() {
    let dir = tempfile::tempdir().unwrap();
    let result = install_deny_guard(dir.path(), "../../../etc/passwd", None);
    assert!(result.is_err());
    let msg = result.unwrap_err().to_string();
    assert!(msg.contains("invalid characters"), "got: {msg}");
}

#[test]
fn test_deny_guard_rejects_empty_command() {
    let dir = tempfile::tempdir().unwrap();
    let result = install_deny_guard(dir.path(), "", None);
    assert!(result.is_err());
    let msg = result.unwrap_err().to_string();
    assert!(msg.contains("cannot be empty"), "got: {msg}");
}

#[test]
fn test_wrap_guard_rejects_shell_injection() {
    let dir = tempfile::tempdir().unwrap();

    let injections = [
        ("backtick", "docker `rm -rf /`"),
        ("dollar", "docker $HOME/evil"),
        ("semicolon", "docker; rm -rf /"),
        ("pipe", "docker | cat /etc/passwd"),
        ("ampersand", "docker & malicious"),
        ("subshell", "docker $(whoami)"),
    ];

    for (label, wrapper) in injections {
        let result = install_wrap_guard(dir.path(), "pnpm", wrapper);
        assert!(
            result.is_err(),
            "wrapper with {} should be rejected: {}",
            label,
            wrapper
        );
        let msg = result.unwrap_err().to_string();
        assert!(
            msg.contains("dangerous character"),
            "{}: expected 'dangerous character', got: {}",
            label,
            msg
        );
    }
}

#[test]
fn test_deny_guard_accepts_valid_command_names() {
    let dir = tempfile::tempdir().unwrap();
    let valid_names = [
        "npm",
        "python3",
        "docker-compose",
        "g++",
        "node_modules",
        "python3.12",
    ];

    for name in valid_names {
        let result = install_deny_guard(dir.path(), name, None);
        assert!(
            result.is_ok(),
            "valid command '{}' was rejected: {:?}",
            name,
            result.err()
        );
    }
}

// ── design invariant: docker must never be in deny lists ──

#[test]
fn test_docker_never_in_deny_lists() {
    // airis internally uses `docker run` and `docker compose exec` (lockfile.rs).
    // If "docker" were in any deny list, airis would block itself.
    let global = GlobalConfig::default();
    assert!(
        !global.guards.deny.contains(&"docker".to_string()),
        "docker must not be in global deny — airis uses it internally"
    );

    for cmd in STRICT_MODE_DENY {
        assert_ne!(
            *cmd, "docker",
            "docker must not be in STRICT_MODE_DENY — airis uses it internally"
        );
    }
}

// ── realistic end-to-end integration test ──

#[cfg(unix)]
#[test]
fn test_full_install_agiletec_style_manifest() {
    let _guard = crate::test_lock::DIR_LOCK.lock().unwrap();
    let original_dir = std::env::current_dir().unwrap();
    let dir = tempfile::tempdir().unwrap();
    std::env::set_current_dir(dir.path()).unwrap();

    let result = std::panic::catch_unwind(|| {
        // Mirrors the actual agiletec manifest.toml guards section
        let manifest_content = r#"
version = 1
[project]
id = "test"

[workspace]
name = "agiletec-style"

[guards]
deny = ["npm", "yarn", "npx", "pnpm", "node", "python3", "pip3", "pip", "uv"]

[guards.deny_with_message]
docker-compose = "Use 'docker compose' (with space) or 'airis up' instead."
pnpm = "Use 'docker compose exec <service> pnpm ...' instead. Docker First!"
npm = "Use 'docker compose exec <service> pnpm ...' instead. Docker First!"
node = "Use 'docker compose exec <service> node ...' instead."
python3 = "Use 'docker compose exec <service> python3 ...' instead."
pip3 = "Use 'docker compose exec <service> pip3 ...' instead."
"#;
        fs::write("manifest.toml", manifest_content).unwrap();
        install().unwrap();

        let guards_dir = PathBuf::from(GUARDS_DIR);
        assert!(guards_dir.exists());

        // All deny commands should have guard files
        for cmd in [
            "npm", "yarn", "npx", "pnpm", "node", "python3", "pip3", "pip", "uv",
        ] {
            assert!(
                guards_dir.join(cmd).exists(),
                "guard for '{}' should exist",
                cmd
            );
        }

        // docker-compose is only in deny_with_message (not in deny)
        assert!(
            guards_dir.join("docker-compose").exists(),
            "docker-compose guard should exist"
        );

        // deny_with_message should take precedence (overwrites deny scripts)
        let pnpm_content = fs::read_to_string(guards_dir.join("pnpm")).unwrap();
        assert!(
            pnpm_content.contains("Docker First!"),
            "pnpm should have custom deny_with_message"
        );

        let npm_content = fs::read_to_string(guards_dir.join("npm")).unwrap();
        assert!(
            npm_content.contains("Docker First!"),
            "npm should have custom deny_with_message"
        );

        let dc_content = fs::read_to_string(guards_dir.join("docker-compose")).unwrap();
        assert!(dc_content.contains("docker compose"));
        assert!(dc_content.contains("airis up"));

        // All generated scripts must be valid bash
        for entry in fs::read_dir(&guards_dir).unwrap() {
            let path = entry.unwrap().path();
            if path.is_file() {
                assert_valid_bash(&path);
            }
        }

        // Guard count: 9 from deny + 1 unique from deny_with_message (docker-compose)
        // deny_with_message also has bun which isn't in deny = total 11
        // Wait — no bun in this manifest. Let's count properly:
        // deny: npm, yarn, npx, pnpm, node, python3, pip3, pip, uv = 9 files
        // deny_with_message: docker-compose, pnpm, npm, node, python3, pip3
        //   pnpm/npm/node/python3/pip3 overwrite existing deny scripts = no new files
        //   docker-compose is NEW = +1 file
        // Total unique commands: 9 + 1 = 10 files
        //
        // But install() also creates a guard for commands in deny_with_message
        // that overlap with deny — the count depends on unique file names.
        let guard_files: Vec<_> = fs::read_dir(&guards_dir)
            .unwrap()
            .filter_map(|e| {
                let e = e.ok()?;
                if e.path().is_file() {
                    Some(e.file_name().to_string_lossy().to_string())
                } else {
                    None
                }
            })
            .collect();

        // Unique command set: deny(9) + global default deny(bun) + deny_with_message only(docker-compose)
        let expected = [
            "npm",
            "yarn",
            "npx",
            "pnpm",
            "node",
            "python3",
            "pip3",
            "pip",
            "uv",
            "bun",
            "docker-compose",
        ];
        for cmd in expected {
            assert!(
                guard_files.contains(&cmd.to_string()),
                "missing guard for '{}'",
                cmd
            );
        }
        assert_eq!(
            guard_files.len(),
            expected.len(),
            "unexpected guard files: {:?}",
            guard_files
        );
    });

    std::env::set_current_dir(original_dir).unwrap();
    result.unwrap();
}
