use super::scripts::*;
use super::*;

use std::fs;
use std::path::PathBuf;

use crate::manifest::{GlobalConfig, GuardLevel};

#[test]
fn test_global_config_default() {
    let config = GlobalConfig::default();
    assert_eq!(config.version, 1);

    // Test through get_level instead of direct field access
    assert_eq!(config.guards.get_level("npm"), GuardLevel::Enforce);
    assert_eq!(config.guards.get_level("yarn"), GuardLevel::Enforce);
    assert_eq!(config.guards.get_level("pnpm"), GuardLevel::Enforce);
    assert_eq!(config.guards.get_level("bun"), GuardLevel::Enforce);
    assert_eq!(config.guards.get_level("npx"), GuardLevel::Enforce);
}

#[test]
fn test_global_config_paths() {
    let config_path = GlobalConfig::config_path();
    assert!(config_path.is_ok());

    let bin_dir = GlobalConfig::bin_dir();
    assert!(bin_dir.is_ok());

    let config_path = config_path.unwrap();
    assert!(config_path.to_string_lossy().contains(".airis"));
    assert!(config_path.to_string_lossy().contains("global-config.toml"));

    let bin_dir = bin_dir.unwrap();
    assert!(bin_dir.to_string_lossy().contains(".airis"));
    assert!(bin_dir.to_string_lossy().ends_with("bin"));
}

#[test]
fn test_global_config_serialization() {
    let config = GlobalConfig::default();
    let toml_str = toml::to_string_pretty(&config).unwrap();

    let parsed: GlobalConfig = toml::from_str(&toml_str).unwrap();
    assert_eq!(parsed.version, config.version);
}

#[test]
fn test_is_airis_guard_marker() {
    use std::io::Write;

    let dir = tempfile::tempdir().unwrap();
    let guard_file = dir.path().join("npm");

    let mut f = fs::File::create(&guard_file).unwrap();
    writeln!(f, "#!/usr/bin/env bash").unwrap();
    writeln!(f, "# Auto-generated by airis guards install").unwrap();
    writeln!(f, "echo 'blocked'").unwrap();

    assert!(is_airis_guard(&guard_file).unwrap());

    let other_file = dir.path().join("other");
    let mut f = fs::File::create(&other_file).unwrap();
    writeln!(f, "#!/usr/bin/env bash").unwrap();
    writeln!(f, "echo 'hello'").unwrap();

    assert!(!is_airis_guard(&other_file).unwrap());
}

#[test]
fn test_install_deny_guard_default_message() {
    let dir = tempfile::tempdir().unwrap();
    install_deny_guard(dir.path(), "npm", None).unwrap();

    let script_path = dir.path().join("npm");
    assert!(script_path.exists());

    let content = fs::read_to_string(&script_path).unwrap();
    assert!(content.starts_with("#!/usr/bin/env bash"));
    // Deny guards route through install_global_guard, which writes the
    // global-install marker. Match on the shared "airis guards" prefix.
    assert!(content.contains("Auto-generated by airis guards"));
}

#[test]
fn test_install_wrap_guard() {
    let dir = tempfile::tempdir().unwrap();
    let wrapper = "docker compose exec workspace pnpm";
    install_wrap_guard(dir.path(), "pnpm", wrapper).unwrap();

    let script_path = dir.path().join("pnpm");
    assert!(script_path.exists());

    let content = fs::read_to_string(&script_path).unwrap();
    assert!(content.starts_with("#!/usr/bin/env bash"));
    assert!(content.contains(&format!("exec {} \"$@\"", wrapper)));
}

#[cfg(unix)]
#[test]
fn test_script_permissions() {
    use std::os::unix::fs::PermissionsExt;

    let dir = tempfile::tempdir().unwrap();

    install_deny_guard(dir.path(), "npm", None).unwrap();
    let perms = fs::metadata(dir.path().join("npm")).unwrap().permissions();
    assert_eq!(perms.mode() & 0o777, 0o755);

    install_wrap_guard(dir.path(), "pnpm", "docker compose exec workspace pnpm").unwrap();
    let perms = fs::metadata(dir.path().join("pnpm")).unwrap().permissions();
    assert_eq!(perms.mode() & 0o777, 0o755);
}

#[test]
fn test_full_install_with_tempdir() {
    let _guard = crate::test_lock::DIR_LOCK.lock().unwrap();
    let original_dir = std::env::current_dir().unwrap();
    let dir = tempfile::tempdir().unwrap();
    std::env::set_current_dir(dir.path()).unwrap();

    let result = std::panic::catch_unwind(|| {
        let manifest_content = r#"
version = 1
[project]
id = "test"

[workspace]
name = "test-workspace"

[guards]
deny = ["npm", "yarn"]

[guards.wrap]
pnpm = "docker compose exec workspace pnpm"

[guards.deny_with_message]
bun = "bun is not supported. Use pnpm via airis."
"#;
        fs::write("manifest.toml", manifest_content).unwrap();

        install().unwrap();

        let guards_dir = PathBuf::from(GUARDS_DIR);
        assert!(guards_dir.exists());

        assert!(guards_dir.join("npm").exists());
        assert!(guards_dir.join("pnpm").exists());
        assert!(guards_dir.join("bun").exists());
    });

    std::env::set_current_dir(original_dir).unwrap();
    result.unwrap();
}
