//! Manifest.toml content generation from discovery results

use anyhow::Result;
use indexmap::IndexMap;

use crate::commands::discover::{ComposeLocation, DiscoveryResult};

/// Format an IndexMap as a TOML inline table
/// e.g., { "dev" = "next dev", "build" = "next build" }
pub(super) fn format_inline_table(map: &IndexMap<String, String>) -> String {
    let pairs: Vec<String> = map
        .iter()
        .map(|(k, v)| {
            format!(
                "\"{}\" = \"{}\"",
                escape_toml_string(k),
                escape_toml_string(v)
            )
        })
        .collect();
    format!("{{ {} }}", pairs.join(", "))
}

/// Escape special characters in TOML strings
pub(super) fn escape_toml_string(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}

/// Generate manifest.toml content from discovery results
pub(super) fn generate_manifest_content(discovery: &DiscoveryResult) -> Result<String> {
    // Initialize with header and base sections
    let mut lines = vec![
        "# Auto-generated by airis init".to_string(),
        "# Edit this file to configure your workspace".to_string(),
        "".to_string(),
        "version = 1".to_string(),
        "mode = \"docker-first\"".to_string(),
        "".to_string(),
        // Project section
        "[project]".to_string(),
        "id = \"workspace\"".to_string(),
        "description = \"Auto-discovered workspace\"".to_string(),
        "".to_string(),
        // Workspace section
        "[workspace]".to_string(),
        "name = \"workspace\"".to_string(),
        "".to_string(),
        // Packages section
        "[packages]".to_string(),
        "workspaces = [\"apps/*\", \"libs/*\"]".to_string(),
        "".to_string(),
    ];

    // Catalog from discovery
    if !discovery.catalog.is_empty() {
        lines.push("[packages.catalog]".to_string());
        for (name, version) in &discovery.catalog {
            lines.push(format!("\"{}\" = \"{}\"", name, version));
        }
        lines.push("".to_string());
    }

    // App definitions (using [[app]] array format for package.json generation)
    if !discovery.apps.is_empty() {
        for app in &discovery.apps {
            lines.push("[[app]]".to_string());
            lines.push(format!("name = \"{}\"", app.name));
            lines.push(format!("path = \"{}\"", app.path));
            lines.push("kind = \"app\"".to_string());
            lines.push(format!("framework = \"{}\"", app.framework));

            // Scripts as inline table
            if !app.scripts.is_empty() {
                let scripts_str = format_inline_table(&app.scripts);
                lines.push(format!("scripts = {}", scripts_str));
            }

            // Dependencies as inline table
            if !app.deps.is_empty() {
                let deps_str = format_inline_table(&app.deps);
                lines.push(format!("deps = {}", deps_str));
            }

            // Dev dependencies as inline table
            if !app.dev_deps.is_empty() {
                let dev_deps_str = format_inline_table(&app.dev_deps);
                lines.push(format!("dev_deps = {}", dev_deps_str));
            }

            lines.push("".to_string());
        }
    }

    // Library definitions (using [[app]] with kind = "lib")
    if !discovery.libs.is_empty() {
        for lib in &discovery.libs {
            lines.push("[[app]]".to_string());
            lines.push(format!("name = \"{}\"", lib.name));
            lines.push(format!("path = \"{}\"", lib.path));
            lines.push("kind = \"lib\"".to_string());

            // Scripts as inline table
            if !lib.scripts.is_empty() {
                let scripts_str = format_inline_table(&lib.scripts);
                lines.push(format!("scripts = {}", scripts_str));
            }

            // Dependencies as inline table
            if !lib.deps.is_empty() {
                let deps_str = format_inline_table(&lib.deps);
                lines.push(format!("deps = {}", deps_str));
            }

            // Dev dependencies as inline table
            if !lib.dev_deps.is_empty() {
                let dev_deps_str = format_inline_table(&lib.dev_deps);
                lines.push(format!("dev_deps = {}", dev_deps_str));
            }

            lines.push("".to_string());
        }
    }

    // Orchestration section (docker-compose paths)
    let workspace_compose = discovery
        .compose_files
        .iter()
        .find(|c| c.location == ComposeLocation::Workspace || c.location == ComposeLocation::Root);
    let supabase_compose = discovery
        .compose_files
        .iter()
        .find(|c| c.location == ComposeLocation::Supabase);
    let traefik_compose = discovery
        .compose_files
        .iter()
        .find(|c| c.location == ComposeLocation::Traefik);

    if workspace_compose.is_some() || supabase_compose.is_some() || traefik_compose.is_some() {
        lines.push("[orchestration.dev]".to_string());

        if let Some(_) = workspace_compose {
            // Always normalize to compose.yaml at root
            lines.push("workspace = \"compose.yaml\"".to_string());
        }

        if let Some(compose) = supabase_compose {
            lines.push(format!("supabase = [\"{}\"]", compose.path));
        }

        if let Some(compose) = traefik_compose {
            lines.push(format!("traefik = \"{}\"", compose.path));
        }

        lines.push("".to_string());
    }

    // Guards section (docker-first defaults)
    lines.push("[guards]".to_string());
    lines.push("deny = [\"npm\", \"yarn\", \"pnpm\"]".to_string());
    lines.push("".to_string());

    // Commands section
    lines.push("[commands]".to_string());
    lines.push("install = \"docker compose run --rm node pnpm install\"".to_string());
    lines.push("dev = \"docker compose up\"".to_string());
    lines.push("build = \"docker compose run --rm node pnpm build\"".to_string());
    lines.push("test = \"docker compose run --rm node pnpm test\"".to_string());
    lines.push("".to_string());

    // Versioning section
    lines.push("[versioning]".to_string());
    lines.push("strategy = \"conventional-commits\"".to_string());

    Ok(lines.join("\n"))
}
