use anyhow::{Context, Result};
use colored::Colorize;
use std::fs;
use std::path::Path;

use crate::manifest::Manifest;
use crate::templates::TemplateEngine;

use super::write_with_backup;

pub(super) fn generate_ci_workflow(manifest: &Manifest, engine: &TemplateEngine) -> Result<()> {
    let workflows_dir = Path::new(".github/workflows");
    fs::create_dir_all(workflows_dir).context("Failed to create .github/workflows directory")?;

    let ci_path = workflows_dir.join("ci.yml");

    // Skip if file exists without airis gen marker (hand-managed)
    if ci_path.exists() {
        let existing = fs::read_to_string(&ci_path).unwrap_or_default();
        if !existing.starts_with("# Auto-generated by airis gen") {
            println!(
                "   {} .github/workflows/ci.yml exists (manually managed — add '# Auto-generated by airis gen' header to enable)",
                "⚠".yellow()
            );
            return Ok(());
        }
    }

    let content = engine.render_ci_workflow(manifest)?;
    write_with_backup(&ci_path, &content)?;
    println!("   {} .github/workflows/ci.yml", "✓".green());
    Ok(())
}

pub(super) fn generate_deploy_workflow(manifest: &Manifest, engine: &TemplateEngine) -> Result<()> {
    let workflows_dir = Path::new(".github/workflows");
    fs::create_dir_all(workflows_dir).context("Failed to create .github/workflows directory")?;

    let deploy_path = workflows_dir.join("deploy.yml");

    // Skip if file exists without airis gen marker (hand-managed)
    if deploy_path.exists() {
        let existing = fs::read_to_string(&deploy_path).unwrap_or_default();
        if !existing.starts_with("# Auto-generated by airis gen") {
            println!(
                "   {} .github/workflows/deploy.yml exists (manually managed — add '# Auto-generated by airis gen' header to enable)",
                "⚠".yellow()
            );
            return Ok(());
        }
    }

    let content = engine.render_deploy_workflow(manifest)?;
    write_with_backup(&deploy_path, &content)?;
    println!("   {} .github/workflows/deploy.yml", "✓".green());
    Ok(())
}

pub(super) fn generate_e2e_workflow(manifest: &Manifest, engine: &TemplateEngine) -> Result<()> {
    let workflows_dir = Path::new(".github/workflows");
    fs::create_dir_all(workflows_dir).context("Failed to create .github/workflows directory")?;

    let path = workflows_dir.join("e2e-staging.yml");

    // Skip if file exists without airis gen marker (hand-managed)
    if path.exists() {
        let existing = fs::read_to_string(&path).unwrap_or_default();
        if !existing.starts_with("# Auto-generated by airis gen") {
            println!(
                "   {} .github/workflows/e2e-staging.yml exists (manually managed — add '# Auto-generated by airis gen' header to enable)",
                "⚠".yellow()
            );
            return Ok(());
        }
    }

    let content = engine.render_e2e_workflow(manifest)?;
    write_with_backup(&path, &content)?;
    println!("   {} .github/workflows/e2e-staging.yml", "✓".green());
    Ok(())
}

pub(super) fn generate_release_workflow(
    manifest: &Manifest,
    engine: &TemplateEngine,
) -> Result<()> {
    let workflows_dir = Path::new(".github/workflows");
    fs::create_dir_all(workflows_dir).context("Failed to create .github/workflows directory")?;

    let path = workflows_dir.join("release.yml");

    // Skip if file exists without airis gen marker (hand-managed)
    if path.exists() {
        let existing = fs::read_to_string(&path).unwrap_or_default();
        if !existing.starts_with("# Auto-generated by airis gen") {
            println!(
                "   {} .github/workflows/release.yml exists (manually managed — add '# Auto-generated by airis gen' header to enable)",
                "⚠".yellow()
            );
            return Ok(());
        }
    }

    let content = engine.render_release_workflow(manifest)?;
    write_with_backup(&path, &content)?;
    println!("   {} .github/workflows/release.yml", "✓".green());
    Ok(())
}
