// Guard script content generation for Claude Code hooks

pub fn playwright_cli_command() -> &'static str {
    r#"---
description: Browser automation via playwright-cli (snapshot → action → verify)
allowed-tools: Bash, Read
---

# playwright-cli

Use `playwright-cli` for browser automation. Prefer snapshot-driven refs over CSS selectors.

## Workflow
1. `playwright-cli open <url>` — open browser
2. `playwright-cli snapshot` — get element refs
3. `playwright-cli click <ref>` / `playwright-cli fill <ref> <text>` — interact
4. `playwright-cli screenshot` — verify result visually

## Core Commands
| Command | Usage |
|---------|-------|
| `open [url]` | Open browser (optionally navigate) |
| `snapshot` | Capture accessibility tree with refs |
| `click <ref>` | Click element by ref |
| `fill <ref> <text>` | Fill input field |
| `type <text>` | Type into focused element |
| `select <ref> <val>` | Select dropdown option |
| `screenshot [ref]` | Screenshot page or element |
| `hover <ref>` | Hover over element |
| `press <key>` | Press keyboard key |
| `goto <url>` | Navigate to URL |
| `eval <js> [ref]` | Run JS on page/element |
| `console` | View console messages |
| `network` | List network requests |

## Auth Persistence
- `state-save [file]` — save cookies/storage to file
- `state-load <file>` — restore auth state from file

## Tips
- Always `snapshot` before interacting — refs change after DOM updates
- Use `screenshot` to verify visual state, not just DOM
- For SPAs, wait after navigation: `playwright-cli snapshot` retries internally
"#
}

pub fn docker_first_guard_script() -> &'static str {
    r##"#!/usr/bin/env bash
# Auto-generated by airis guards --hooks
# Blocks host-level package manager usage in Claude Code

INPUT=$(cat)
COMMAND=$(python3 -c "
import json, sys
data = json.loads(sys.stdin.read())
print(data.get('tool_input', {}).get('command', ''))
" <<< "$INPUT")

# Allow commands through docker compose exec
if echo "$COMMAND" | grep -qE '^docker (compose |)exec'; then
  exit 0
fi

BLOCKED=(
  '^npm (install|i |ci|add|update|remove|uninstall)'
  '^yarn (install|add|remove)'
  '^pnpm (install|i |add|remove|update)'
  '^pip3? install'
  '^brew install'
  '^apt(-get)? install'
  '^cargo install'
)

for pattern in "${BLOCKED[@]}"; do
  if echo "$COMMAND" | grep -qE "$pattern"; then
    cat >&2 <<EOF
BLOCKED: Docker-First violation

  Command: $COMMAND

This installs packages directly on the host.
Use docker compose exec instead:

  docker compose exec <service> $COMMAND

Why: Docker-First ensures reproducible environments.
Host pollution causes "works on my machine" bugs.
EOF
    exit 2
  fi
done

exit 0
"##
}

pub fn docker_first_edit_guard_script() -> &'static str {
    r##"#!/usr/bin/env bash
# Auto-generated by airis guards --hooks
# Blocks Docker-First violations in Edit/Write tool calls.
# Checks BOTH the new content being written AND the existing file content.

set -euo pipefail

INPUT=$(cat)
FILE_PATH=$(python3 -c "
import json, sys
data = json.loads(sys.stdin.read())
print(data.get('tool_input', {}).get('file_path', ''))
" <<< "$INPUT")

BASENAME=$(basename "$FILE_PATH")

# Only check Docker/CI target files by name pattern
# Skip everything else (source code, docs, configs, scripts, etc.)
if [[ ! "$BASENAME" =~ ^(Dockerfile|Dockerfile\..+|compose\.ya?ml|docker-compose\.ya?ml|ci\.ya?ml|deploy\.ya?ml)$ ]]; then
  exit 0
fi

NEW_CONTENT=$(python3 -c "
import json, sys
data = json.loads(sys.stdin.read())
# Write tool uses 'content', Edit tool uses 'new_string'
print(data.get('tool_input', {}).get('content', '') or data.get('tool_input', {}).get('new_string', ''))
" <<< "$INPUT")

# Check function: scans text for violations
# Args: $1=text_to_check, $2=source_label ("new content" or "existing file")
check_violations() {
  local text="$1"
  local source="$2"

  # Host-specific absolute paths
  if echo "$text" | grep -qE '(/Users/[a-z]|~/)'; then
    cat >&2 <<BLOCK
BLOCKED: Host path in Docker/CI file ($source)

  Host-specific path (/Users/..., ~/) detected in $BASENAME.
  This WILL fail in CI.

  Fix: Use container-internal paths only.
  - pnpm store: PNPM_STORE_DIR=/pnpm/store (named volume)
  - node_modules: /app/node_modules (named volume)
  - /home/app is OK (container user), /Users/kazuki is NOT

  If this violation is in existing code, fix it before making other changes.
BLOCK
    return 1
  fi

  # Local .pnpm-store path
  if echo "$text" | grep -qE '\.pnpm-store|\.pnpm/store|node_modules/\.pnpm'; then
    cat >&2 <<BLOCK
BLOCKED: Local pnpm store path in Docker/CI file ($source)

  .pnpm-store or .pnpm/store are host-local paths.
  Use PNPM_STORE_DIR=/pnpm/store with a named volume.

  If this violation is in existing code, fix it before making other changes.
BLOCK
    return 1
  fi

  # Bind mount of node_modules (compose files only)
  if [[ "$BASENAME" =~ ^(compose\.ya?ml|docker-compose\.ya?ml)$ ]]; then
    if echo "$text" | grep -qE '\./node_modules\s*:|\./\.pnpm'; then
      cat >&2 <<BLOCK
BLOCKED: Bind mount of node_modules in compose file ($source)

  node_modules MUST use named volumes, not bind mounts.

  Correct: node_modules:/app/node_modules   (named volume)
  Wrong:   ./node_modules:/app/node_modules  (bind mount)

  If this violation is in existing code, fix it before making other changes.
BLOCK
      return 1
    fi
  fi

  # PNPM_STORE_DIR pointing to host paths
  if echo "$text" | grep -qE "PNPM_STORE_DIR\s*=\s*[\"']?\.(\/|pnpm)|PNPM_STORE_DIR\s*=\s*[\"']?(/Users|/home|~/)"; then
    cat >&2 <<BLOCK
BLOCKED: PNPM_STORE_DIR set to host-local path ($source)

  PNPM_STORE_DIR must point to a named volume mount.

  Correct: PNPM_STORE_DIR=/pnpm/store
  Wrong:   PNPM_STORE_DIR=./.pnpm-store

  If this violation is in existing code, fix it before making other changes.
BLOCK
    return 1
  fi

  return 0
}

# Check new content being written
check_violations "$NEW_CONTENT" "new content" || exit 2

# Check existing file content (catches pre-existing violations)
if [[ -f "$FILE_PATH" ]]; then
  EXISTING=$(cat "$FILE_PATH" 2>/dev/null || true)
  if [[ -n "$EXISTING" ]]; then
    check_violations "$EXISTING" "existing file" || exit 2
  fi
fi

exit 0
"##
}

pub fn stop_test_check_script() -> &'static str {
    r#"#!/usr/bin/env bash
# Auto-generated by airis guards --hooks
# Runs quick test check when Claude finishes responding

# Only run inside airis projects (manifest.toml present)
find_manifest() {
  local dir="$PWD"
  while [[ "$dir" != "/" ]]; do
    [[ -f "$dir/manifest.toml" ]] && echo "$dir" && return 0
    dir="$(dirname "$dir")"
  done
  return 1
}

ROOT=$(find_manifest) || exit 0
cd "$ROOT"

# Detect project type and run tests
if [[ -f Cargo.toml ]]; then
  cargo test 2>&1 | tail -5
  STATUS=$?
elif [[ -f pyproject.toml ]]; then
  if command -v pytest &>/dev/null; then
    pytest --tb=no -q 2>&1 | tail -5
    STATUS=$?
  else
    exit 0
  fi
elif [[ -f package.json ]]; then
  if command -v npm &>/dev/null; then
    npm test 2>&1 | tail -10
    STATUS=$?
  else
    exit 0
  fi
else
  exit 0
fi

if [[ $STATUS -ne 0 ]]; then
  echo "" >&2
  echo "STOP: Tests are failing. Fix them before declaring work done." >&2
  exit 2
fi

exit 0
"#
}
