//! Next.js web project scaffolding

use anyhow::{Context, Result};
use colored::Colorize;
use std::fs;
use std::path::Path;

/// Generate a Next.js web project
pub fn generate_web_project(project_dir: &Path, name: &str) -> Result<()> {
    fs::create_dir_all(project_dir.join("src/app"))
        .context("Failed to create src/app directory")?;

    // package.json
    let package_json = format!(
        r#"{{
  "name": "{}",
  "version": "0.1.0",
  "private": true,
  "scripts": {{
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  }},
  "dependencies": {{
    "next": "catalog:",
    "react": "catalog:",
    "react-dom": "catalog:"
  }},
  "devDependencies": {{
    "typescript": "catalog:",
    "@types/node": "catalog:",
    "@types/react": "catalog:",
    "@types/react-dom": "catalog:"
  }}
}}
"#,
        name
    );
    fs::write(project_dir.join("package.json"), package_json)?;

    // next.config.js
    let next_config = r#"/** @type {import('next').NextConfig} */
const nextConfig = {
  output: 'standalone',
}

module.exports = nextConfig
"#;
    fs::write(project_dir.join("next.config.js"), next_config)?;

    // tsconfig.json — extends base, Next.js-specific options
    let tsconfig = r#"{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "noEmit": true,
    "module": "esnext",
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./src/*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
"#;
    fs::write(project_dir.join("tsconfig.json"), tsconfig)?;

    // src/app/layout.tsx
    let layout = format!(
        r#"export const metadata = {{
  title: '{}',
  description: 'Generated by airis new',
}}

export default function RootLayout({{
  children,
}}: {{
  children: React.ReactNode
}}) {{
  return (
    <html lang="en">
      <body>{{children}}</body>
    </html>
  )
}}
"#,
        name
    );
    fs::write(project_dir.join("src/app/layout.tsx"), layout)?;

    // src/app/page.tsx
    let page = format!(
        r#"export default function Home() {{
  return (
    <main style={{ padding: '2rem' }}>
      <h1>{}</h1>
      <p>Welcome to your new Next.js app!</p>
    </main>
  )
}}
"#,
        name
    );
    fs::write(project_dir.join("src/app/page.tsx"), page)?;

    // .gitignore
    let gitignore = r#"node_modules/
.next/
out/
*.log
.env
.env.local
"#;
    fs::write(project_dir.join(".gitignore"), gitignore)?;

    println!("  {} package.json", "✓".green());
    println!("  {} next.config.js", "✓".green());
    println!("  {} tsconfig.json", "✓".green());
    println!("  {} src/app/layout.tsx", "✓".green());
    println!("  {} src/app/page.tsx", "✓".green());
    println!("  {} .gitignore", "✓".green());

    Ok(())
}
