//! File ownership model for airis
//!
//! Defines who "owns" each file type and how airis should handle them:
//! - Tool: fully managed by airis, safe to backup and overwrite
//! - User: never touch, owned by the user

use std::path::Path;

/// Ownership level for a file
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Ownership {
    /// Fully managed by airis - safe to backup and overwrite
    Tool,
    /// User-owned - never modify or delete
    User,
}

/// Get the ownership level for a given file path
pub fn get_ownership(path: &Path) -> Ownership {
    let path_str = path.to_string_lossy();

    // Exact matches first
    match path_str.as_ref() {
        // Tool-owned: fully generated from manifest
        "package.json" => Ownership::Tool,
        "pnpm-workspace.yaml" => Ownership::Tool,
        "tsconfig.json" => Ownership::Tool,
        "tsconfig.base.json" => Ownership::Tool,
        "airis.lock" => Ownership::Tool,

        // User-owned: never touch
        "Dockerfile" => Ownership::User,
        "compose.yml" => Ownership::User,
        "docker-compose.yml" => Ownership::User,
        ".env.example" => Ownership::User,
        "manifest.toml" => Ownership::User,
        "pnpm-lock.yaml" => Ownership::User,
        "tsconfig.build.json" => Ownership::User,
        "eslint.config.mjs" => Ownership::User,
        "vitest.config.ts" => Ownership::User,
        "README.md" => Ownership::User,
        "CHANGELOG.md" => Ownership::User,
        "PROJECT_INDEX.md" => Ownership::User,
        "AGENTS.md" => Ownership::User,
        "CLAUDE.md" => Ownership::User,
        "GEMINI.md" => Ownership::User,

        _ => {
            // Pattern matches
            if path_str.starts_with(".github/workflows/") {
                // Tool-owned if generated by airis gen, otherwise user-owned
                if let Ok(content) = std::fs::read_to_string(path)
                    && content.contains("# Auto-generated by airis gen")
                {
                    return Ownership::Tool;
                }
                Ownership::User
            } else if (path_str.starts_with("apps/") || path_str.starts_with("libs/"))
                && path_str.ends_with("/package.json")
            {
                // In the new deterministic model, app package.json files are tool-owned
                // if they are part of the manifest.
                Ownership::Tool
            } else if path_str.starts_with(".airis/") {
                // .airis internal files are tool-owned
                Ownership::Tool
            } else {
                // Default: user-owned (safe default)
                Ownership::User
            }
        }
    }
}

/// Check if a file should be backed up before modification
#[allow(dead_code)]
pub fn should_backup(ownership: Ownership) -> bool {
    matches!(ownership, Ownership::Tool)
}

/// Check if airis can overwrite a file
#[allow(dead_code)]
pub fn can_overwrite(ownership: Ownership) -> bool {
    matches!(ownership, Ownership::Tool)
}

/// Check if airis should fully regenerate a file
#[allow(dead_code)]
pub fn should_regenerate(ownership: Ownership) -> bool {
    matches!(ownership, Ownership::Tool)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_tool_owned_files() {
        assert_eq!(get_ownership(Path::new("package.json")), Ownership::Tool);
        assert_eq!(
            get_ownership(Path::new("pnpm-workspace.yaml")),
            Ownership::Tool
        );
        assert_eq!(get_ownership(Path::new("tsconfig.json")), Ownership::Tool);
        assert_eq!(
            get_ownership(Path::new("tsconfig.base.json")),
            Ownership::Tool
        );
        assert_eq!(get_ownership(Path::new("airis.lock")), Ownership::Tool);
        
        // App package.json files are now tool-owned
        assert_eq!(
            get_ownership(Path::new("apps/dashboard/package.json")),
            Ownership::Tool
        );
    }

    #[test]
    fn test_user_owned_files() {
        assert_eq!(get_ownership(Path::new("manifest.toml")), Ownership::User);
        assert_eq!(get_ownership(Path::new("pnpm-lock.yaml")), Ownership::User);
        assert_eq!(get_ownership(Path::new("Dockerfile")), Ownership::User);
        assert_eq!(get_ownership(Path::new("compose.yml")), Ownership::User);
        assert_eq!(get_ownership(Path::new("CLAUDE.md")), Ownership::User);
    }

    #[test]
    fn test_default_is_user() {
        assert_eq!(get_ownership(Path::new("random-file.txt")), Ownership::User);
    }
}
